### ISSUE TITLE
ExpressionBuilder - UpdateItem builds tooltips for all expressions every time

### ISSUE THREAD

**Issue by bowring** [CIRDLES/Squid#102]
Every time a new expression  is selected in the list , a large number of items (20-ish) are processed with the updateItem method ... very inefficient. (line 2410)

**Comment by mgaonach** [comment]
Actually this fixes that problem but creates an other. The method updateItem seems to have a very mysterious way of working...

**Comment by bowring** [comment]
can you put in a check for the selected item to do tooltip only for it?
