### ISSUE TITLE
A few suggestions from the GSC SHRIMP lab.  I'll start with trivial things: 

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#108]
Squid3 Version: 0.3.0
Java Version: 1.8.0_171
OS: Windows 7 6.1

Issue details: 
- [x] add DENOMINATOR and NUMERATOR to the axes of the ratio builder grid.  
- [ ] Grey out the "expression" accordion when in edit mode. 
- [ ] Add functionality to set the default folder when opening/saving the different files (.xml, .squid etc)

**Comment by bowring** [comment]
Great start!

A couple helpful notes:

It is easier if each of these items is its own issue, but don't backtrack here.

The expression accordion needs to be active so you can drag and drop expressions into the editor!  Am I missing something in your issue?

A use-case describing a suggested series of events would be helpful in understanding the third issue.

**Comment by NicoleRayner** [comment]
Hi Jim,

Thanks for the helpful notes – one of my aims was to just flag some kind of issue so I could practice interacting with it.  Good to know to keep issues separate, I also now see that it might be useful for me to include which menu item is implicated in the issue (Expression Builder, Audit session etc).  I will do that in the future.  And NOW I notice that I should be responding to your queries etc in GitHub not replying to your emails.  Here is my response to the above:

Issue #2 Good point that expressions need to be active.  The issue I was trying to resolve with this suggestion is that I don’t “remember” that I am in edit mode and then I want to go see the details of another expression, and I click on it, nothing “happens” and I get confused about what I have done wrong. I am basically just looking for a more obvious visual clue that I am in edit mode.  I know there are the “edit” and “save” buttons that are either active/inactive but for whatever reason it isn’t obvious to me.  With a bit of practice this will become second nature, so not worth huge efforts to resolve, but might be a source of consternation for others at the start.  Maybe there is some other simple way to indicate this – for example you edit the magnet calibration on the SHRIMP, there is an “edit” button, and it flashes while you are in edit mode.  
Issue #3 Our xml files are always in the same place.  Instead of browsing to it every time I launch SQ3, can I set the default folder, so when I click on “open Prawn file” I am already in the right folder.  Likewise with Import Squid task – they are in a different folder from the xml files.  Currently I have set those two root folders in my Favourites, to keep browsing to a minimum.
