### ISSUE TITLE
Defining masses from Prawn xml file - two decimal places needed for species ID

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#119]
When I open a new prawn xml file, the species are identified by their closest integer mass.  This results in "duplicate" masses for species that are close to one another (e.g. 204 and 204.1 aka background).  The masses in the prawn file are given to 6 decimal places, so it must be rounding and that is causing the problem.  Please display the masses from the prawn file with 2 decimal places (if it were only 1 decimal place in some cases if it rounded up/down it might confuse masses, more than that is overkill).  
![prawnfile audit _ masses in prawn file vs task](https://user-images.githubusercontent.com/40035242/41870836-2ce6e078-788b-11e8-8c61-c206b42188b9.JPG)

**Comment by bowring** [comment]
The goal here is to name the mass stations in a meaningful way that will correspond to isotope names used in the task.  The mass stations could for instance be named "A", "B" ,... and the Squid3 math would work if the expressions referred to ratios ["A/B"], etc.

The problem in identifying the masses more closely than the integers is that the masses vary from run to run especially after the first decimal place, so we will need to specify which parameter of which run we will use to label the mass stations.  For example, the second parameter in a run table entry  for Zr2O is <par name="amu" value="195.748246" /> and another entry is "<par name="amu" value="195.752884" />".  The corresponding entries in the first scan for each of these is "<par name="trim_mass" value="195.747102" />" and "<par name="trim_mass" value="195.751544" />".

Thoughts?

**Comment by NicoleRayner** [comment]
I don't understand the last 2 sentences above: For example, the second parameter in a run table entry for Zr2O is and another entry is "". The corresponding entries in the first scan for each of these is "" and "".

**Comment by bowring** [comment]
apparently mark-down wiped out the contents ... standby

**Comment by bowring** [comment]
look at it in edit mode ... while I fix

**Comment by NicoleRayner** [comment]
So in all those examples, they would all round to 195.75.  It might be that SQUID2.5's threshold is 0.01amu, not 0.1 as I said above.

**Comment by cwmagee** [comment]
Sorry to use email, but on my phone in a central Oregon hotel...

Anyway, a better solution to this issue is to display masses to 5
significant figures. So you can distinguish 205.97 from 205.94 or 15.999
from 16.003.

Because the mass spectrometer has a nominal mass resolution of one part in
ten thousand,  5 digits should be sufficient to distinguish between any
peaks that the instrument can detect.

Cheers,
Chuck

**Comment by NicoleRayner** [comment]
Five sig figs is a good solution. I have confirmed that SQUID2.5 (and 3.0) determines the masses in the Prawn file (.pd or .xml) by looking at the first analysis in the file.  The masses are summarized at the start of each analysis (before the scan by scan counts/masses etc are given).  And it is this "summary mass" that Squid2.5 (and SQUID3.0) read in.  This is as good a value to use for the mass ID as any other. FYI - this "summary mass" = the mass recorded for each isotope in the LAST scan.  I guess the outstanding question is what limits are put in place to determine if the masses in a prawn file and a task "match".

**Comment by bowring** [comment]
Resolved as of release v0.4.0.
