### ISSUE TITLE
Bugs in Audit raw data plots

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#147]
The last analysis in a squid xml file is not selectable+ a label does not show when selected from the audit plots.  More critically the plots do not update properly after an analysis is removed.  The DATA pertaining to the selected analysis is removed from further processing, it is just that it is still REPRESENTED in the audit plot.  The data points for the LAST analysis are what are removed from the audit plot.

**Comment by bowring** [comment]
Strangely related as a side effect to issue #148.
