### ISSUE TITLE
SQUID3 crashes when I select 10493 as the reference material

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#148]
I was trying to use SQUID3  to reduce some brand new data but it kept "crashing" on me.  The symptoms were:  non-responsivness when I tried to "manage isotopes" - i.e. apply task labels to mass labels.  If when to a different menu then came back it seemed to "take".  However then when I went to Expressions or Visualizations, all I got was the blue welcome screen.  No error message.   It was tough to suss out what was triggering this problem but it seems only occur when I select 10493 as the reference material (this is our lab  number for Temora 2).  If I select 6266 as the ref material, no problem.  I tried renaming some of the 6266 analyses to 6267 (as a test to see if the ref mat name was the problem) but everything worked fine.   I tried different versions of our GSC tasks and the problem always occurs when 10493 is the ref mat, regardless of task. I am at a loss about what could be going on.  Find attached a zip file containing the xml and task that is giving me grief.
[922_1_2018_Aug_10_10.38.zip](https://github.com/CIRDLES/Squid/files/2287313/922_1_2018_Aug_10_10.38.zip)
[SquidTask_Z6266 = 11pk (FIXED slope) - mass frac.GSC.zip](https://github.com/CIRDLES/Squid/files/2287316/SquidTask_Z6266.11pk.FIXED.slope.-.mass.frac.GSC.zip)

**Comment by bowring** [comment]
This data set uncovered an edge condition in LudwigLibrary's implementation of the VBA robReg (robust regression) where exactly 13 data points  threw an error!  There are exactly 13 spots in 10493 and they contribute to Expo via robReg.  Nice catch!
