### ISSUE TITLE
Remaining bug in Audit Raw Data - see closed issue #147

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#152]
The Audit Raw Data plots still do not update properly.  When a spot is removed (using right click menu), the **_plots_** in this window do not update (although the correct data point is removed from further processing).  The attached video demonstrates this by removing a data point where the duoplasmatron went out (primary beam intensity to 0).  This is a very distinct data point, and when I remove it from the prawn file, it persists in the Audit Data plot (but it gets renamed to the next point in the list)
[Video_2018-08-21_135445.zip](https://github.com/CIRDLES/Squid/files/2307454/Video_2018-08-21_135445.zip)

**Comment by bowring** [comment]
Nice catch.  It turns out this was only a problem with primary beam and qt1y and qt1z - the correct spot was removed but the grapher for these three was not using updated data.  Fixed in next release.
