### ISSUE TITLE
Built in expressions vs SQUID3 expressions?

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#162]
Are these the same thing?  As far as I can tell they are.  For consistent user experience, consider rationalizing the labelling in the expression manager (check boxes vs drop down menus)
![expressions built in vs squid 3](https://user-images.githubusercontent.com/40035242/44807831-90f2a580-ab98-11e8-96d6-0fa4559005e5.JPG)

**Comment by bowring** [comment]
Yes, thanks for the observation!
