### ISSUE TITLE
Audit raw data plotting when scan number varies

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#169]
I noticed today that in the xml file that I was working with that the vertical red lines on the audit raw data plots did not line up with individual analyses.  This is most obvious when looking at the primary beam intensity plot as each analysis is a little plateau.  As you can see below, sometimes the red vertical line splits the plateau
![spot audit misalignment](https://user-images.githubusercontent.com/40035242/45099634-c1d15e00-b0f5-11e8-8422-05c9abddb1c9.JPG)
I discovered that the problem was that the FIRST analysis in the run had 5 scans and the rest had 6.  The spacing for the red lines appears to be set by the first analysis.  If I delete that one from the run, things snap into place.  
![all lined up](https://user-images.githubusercontent.com/40035242/45099852-48863b00-b0f6-11e8-8f99-776296b6f525.JPG)
Presumably if an analysis mid-run had a different number of scans it would go off again.

**Comment by bowring** [comment]
Good catch - currently we are only supporting uniformly structured runs as in all runs have same number of scans; This issue puts handling of data sets with varying scan counts on the front burner.  Please supply an example PRAWN file and task so we can proceed to solve this problem.

**Comment by NicoleRayner** [comment]
Here you go.  First analysis is 5 scans, rest are 6.
[923_1_2018_Aug_20_14.35.zip](https://github.com/CIRDLES/Squid/files/2357465/923_1_2018_Aug_20_14.35.zip)
