### ISSUE TITLE
Opening a recent .squid file - first view is of "Manage Task", not "Manage Project"

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#170]
This might just be my personal preference, so I am willing to adjust if other users requested this and prefer it, but I noticed this morning that when I open a recent .squid project file the first thing I am shown is the Manage Task view.  Why not the Manage Project view, which is the root window of the menu item I just used (Project --> Open recent SQUID project)? There is a lot of helpful info in there (like the number of scans) but you are never shown this window when you open a .squid file, you have to browse back to the start of the sequential menu list to get there.

**Comment by bowring** [comment]
Great idea!
