### ISSUE TITLE
Bugs related Squid3 on Korean language versions of Squid

### ISSUE THREAD

**Issue by cwmagee** [CIRDLES/Squid#176]
We had two problems with Squid 3 running on Korean versions of Java today. 
Both in windows. 
On one (Java 1.8 Win unknown) Squid would crash before opening screen- a blank window appeared then disappeared
On the other (Java 1.81, windows 8), everything worked except the display of the reference material mean calibrations (Concordia worked fine). The graph was absent, but the calculated stats were still shown. Hopefully some of the Koreans will find this thread and add further information.

**Comment by bowring** [comment]
closing for lack of input
