### ISSUE TITLE
Window border truncated

### ISSUE THREAD

**Issue by TPestaj** [CIRDLES/Squid#177]
Squid3 Version: 1.0.1
Java Version: 1.8.0_181
OS: Windows 7 6.1

Issue details:
It seems the right-hand side of all(?) SQUID screens are truncated on my monitor.  Is this a result of using the monitor in portrait mode?  (I use 1050x1680 screen resolution.)

![image](https://user-images.githubusercontent.com/43234276/45776248-5b355f80-bc20-11e8-8dd4-45042868bdba.png)
![image](https://user-images.githubusercontent.com/43234276/45776258-612b4080-bc20-11e8-9223-1767620c3462.png)

Contact me if you need further information.
Tom

**Comment by bowring** [comment]
We are not supporting portrait mode at this resolution at this time.
