### ISSUE TITLE
Menu labels truncated

### ISSUE THREAD

**Issue by TPestaj** [CIRDLES/Squid#178]
Squid3 Version: 1.0.1
Java Version: 1.8.0_181
OS: Windows 7 6.1

Issue details:
Some main menu labels are truncated such that they aren't helpful.  Perhaps this is also a result of my chosen monitor orientation (see previous issue).  Can the labels be intelligently resized such that there is a 'lower limit' to the size that will still be useful but legible (ie do not allow infinite resizing simply to show full label text)?

![image](https://user-images.githubusercontent.com/43234276/45776736-cf243780-bc21-11e8-83be-de85ee6b2aca.png)

**Comment by bowring** [comment]
Squid is 1250 x 750.  We are not supporting smaller sizes for now.
