### ISSUE TITLE
Explanation of options?

### ISSUE THREAD

**Issue by TPestaj** [CIRDLES/Squid#179]
It may be helpful to have informative 'tips' appear to briefly explain options upon hovering mouse over the item (radio buttons and check boxes in Task Parameters, for instance).  This paradigm is already used in SHRIMP control software so most users would be familiar with this kind of information-delivery.

**Comment by bowring** [comment]
Great idea - please  consider contributing the needed language - aimed at geochronologists!

**Comment by bowring** [comment]
closing for lack of responses
