### ISSUE TITLE
'Busy' visual cue

### ISSUE THREAD

**Issue by TPestaj** [CIRDLES/Squid#180]
Squid3 Version: 1.0.1
Java Version: 1.8.0_181
OS: Windows 7 6.1

Issue details:
Apologies for yet another trivial gripe, but as a relatively new user of SQUID I'm not yet used to times when it takes a while to do what I ask of it.  It would be helpful to have some kind of visual feedback telling me my command has been acknowledged and it is working on it.  Something like the Windows hourglass, or a 'Please wait...' text box to show that the software is doing something.

**Comment by bowring** [comment]
For now, we rely on the hourglass / beachball busy cursor icon supplied by the operating system.  Phase II may address this issue.
