### ISSUE TITLE
Unable to generate report in SQUID3 v1.0.1 

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#182]
UPDATE:  I got it to work but I had to create a different report first (e.g a Report Table per Squid2.x) - that worked and THEN when I made a Report Table - by sample for ET-REDUX it worked.  I don't think the folder gets created when you to the Report Table for Redux.  But, rest of issue for suggestion on better file location for the reports anyway.

Processing a recent pd data file.  Everything looks great, really like it!  However I am unable to generate a report for the unknowns.  The SQUID reports folder is there, there is no DataTable subfolder.  I

On a related note I would much prefer if the default location for the generated reports was in the same folder as the .squid file from which it was derived (or in the same folder that the .xml file was taken from - which are one and the same in our labs case).  I would also prefer that the file name of the report is  preceded by the  project name to make each unique.   I may have already suggested this in a previous issue. UPDATE - now that I can see the report I can see that you implemented the unique naming.  Thanks.  

[927_1_2018_Oct_23_15.16.zip](https://github.com/CIRDLES/Squid/files/2515320/927_1_2018_Oct_23_15.16.zip)

**Comment by bowring** [comment]
Thanks for the feedback.  I opened the file and experienced your issue until I visited the menu item PrawnFile / Manage Sample Naming to accept the default division of samples into groups.  Then the report for ET_Redux is generated when asked.  Obviously, the report should generate if you have not divided the samples into groups, so this is a bug of sorts and a good catch.  

Please make a separate issue of the default location suggestion (thanks in advance)!

**Comment by NicoleRayner** [comment]
Will add a separate issue about the file location.  
I have a question about what you mean by you had to "visit the Manage Sample Naming item in order to accept the default division of samples into groups".  Does one merely have to visit this item in order to "accept" the default division or actually do something.  I noted that when I went to visualizations/Unknowns/Concordia the first time I had one "super sample"  I clicked around a bit to try and remind myself how to get the samples to break out (including visiting the Manage Sample Naming window, but everything looked in order so I didn't DO anything) and when I went back to the concordia I had the option of plotting by sample.

**Comment by bowring** [comment]
Visiting is all that is required with the idea that the user will confirm / change the selections as part of the workflow - this means if a bogus grouping appears by default when visiting then it sticks unless changed.  The notion is that the user will be proactive and follow the "breadcrumbs" or steps provided.

**Comment by bowring** [comment]
No changes required.  Request help making video of using Squid3 workflow.
