### ISSUE TITLE
Problem with the data when I open as Project in ET-REDUX

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#183]
New project from legacy Data Table -> Squid3 UPb data-> Select .csv file to import ->Save as .redux project when I open the project the values are all misaligned with the wrong column headers in the .redux file

Attached are the source data report (data/column headers are correct) and the resulting redux. 

[IP927test2.zip](https://github.com/CIRDLES/Squid/files/2516037/IP927test2.zip)

[927_1_2018_Oct_23_15.16_UnknownsBySampleReportTableForET_Redux.zip](https://github.com/CIRDLES/Squid/files/2516038/927_1_2018_Oct_23_15.16_UnknownsBySampleReportTableForET_Redux.zip)

**Comment by bowring** [comment]
Great catch - again ahead of the curve!  The output to ET_Redux was hard-coded for 12 ratios as an illustrative case for the workshop.  If you add 2 ratios using Manage Ratios menu item (does not matter which), the report will produce correctly!  Obviously will be fixed soon...

**Comment by bowring** [comment]
Repaired as of ET_Redux v3.6.72 Maintenance Release.
