### ISSUE TITLE
saving SQUID3 .csv file is slow in ET-REDUX

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#184]
When I import the SQUID3 .csv file and then "Save and Close", the save process is quite slow (a couple of minutes).  Hoping/wondering if you can implement the same fix that resolved the slow save in SQUID3.  If this is not an easy fix, the current delay is could be lived with but it would help to have an hourglass/spinning wheel to indicate that it is still working on it.

**Comment by bowring** [comment]
Fixed in next ET_Redux release.
