### ISSUE TITLE
Request re. Visualizations - Concordia:Select all/select none ellipses 

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#186]
I would like the ability to select all/select none of the ellipses for a given sample with a single click.  I think that if the sample name is clicked ON, the default should be that all spots within that sample are clicked ON and likewise if the sample name is UNchecked, all the individual spots should be UNchecked.

**Comment by bowring** [comment]
Good idea - will require some thought and discussion relative to meaning of checkboxes.

**Comment by NicoleRayner** [comment]
Not sure if there is a way to re-open a closed issue so I am trying by making a comment here.
Right now if a sample is unchecked the ellipses are still there but grey. Especially in cases where there are multiple samples in a squid file I would like a way to make the ellipses disappear altogether.  We can discuss the best way to go about this.
