### ISSUE TITLE
default file location for Data Reports

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#187]
I would like it if the default folder for the Data Report tables was set to be the same folder housing the source XXXX.squid file.  

This requires saving a .squid file before exporting a report.  I think this is a common sense/intuitive thing to do (it is for me).  However depending on others thoughts/complexity in programming I could also see the usefulness in setting the default folder to be the one containing the original .xml file.  This would get complicated in cases where 2 .xml files are being joined, so probably not ideal.

**Comment by bowring** [comment]
Great ideas - let's study in more detail with a few use cases including these.

**Comment by bowring** [comment]
This is done as of v1.5.0 and the file-writing dialog announces the location.
