### ISSUE TITLE
Extraneous footnote in REDUX table

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#188]
Thanks for the tip on using 12 ratios to get SQUID data into redux.  I did that and modified the table to my taste.  There is a footnote "d" for each of the isotope ratios that isn't meaningful and thus throws off the lettering of remaining footnotes.  The .redux file is attached if you wish to test.
![squid redux table](https://user-images.githubusercontent.com/40035242/47584636-168c9a80-d929-11e8-898f-090848d32bed.JPG)
[IP927test3.zip](https://github.com/CIRDLES/Squid/files/2520374/IP927test3.zip)

**Comment by bowring** [comment]
Repaired in next release of ET_Redux.
