### ISSUE TITLE
Output of custom expressions exported into report tables

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#191]
As discussed today - the ability to export the results of all custom expressions into report tables would be helpful for further stages of data manipulation/visualization (eg. the ability to plot using heatmap for a variety of different trace elements which may be added/subtracted from a SHRIMP runtable over time).

**Comment by bowring** [comment]
This issue is handled by the current Report Builder.  If further refinements are needed, please make new issues.
