### ISSUE TITLE
mapping of SQUID3 report output to ET-REDUX  report columns

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#193]
I've reviewed the existing SQUID3 report output for ET-REDUX and compared it with available report categories and columns in ET-REDUX.  I have a few suggestions for re-mapping some of the columns (e.g. 207*/206* should be in the PbcCorr Isotopic Ratio category) as well as adding some new columns to existing categories (e.g. 204/206 and error added to isotopic ratios category).  
Attached is a .xlsx file containing the SQUID3 report with suggested edits to mapping shown by grey columns with red lettering.  The proposed category is given at the top.

I'm also tentatively proposing another category "QA/QC parameters" to be included in the ET-REDUX report format.  The columns to be mapped to this category are shown in green.  My thinking is that if I am using ET-REDUX to visualize I want to be able to refer to these values to double check that my calibration is representative (e.g. UO/U is "normal", total Zr cps are "normal") before I start doing regressions etc. 

[927_1_2018_Oct_23_15.16_UnknownsBySampleReportTableForET_Redux.xlsx](https://github.com/CIRDLES/Squid/files/2539299/927_1_2018_Oct_23_15.16_UnknownsBySampleReportTableForET_Redux.xlsx)

**Comment by bowring** [comment]
We will need to chat on Skype about the details, but these are my concerns: 
1) It seems that QA/QC should include ALL CPS as we have no guarantees as to which isotopes are included in an analysis
2) Should ALL Raw Nuclide Ratios be included in Composition/Measured Ratios Category for the same reason?

**Comment by bowring** [comment]
Customized reports addresses these issues.
