### ISSUE TITLE
Japanese language testing

### ISSUE THREAD

**Issue by cwmagee** [CIRDLES/Squid#194]
This issue is a placeholder to see if there are problems using SQUID with Japanese language operating systems and/or Java.

**Comment by bowring** [comment]
Great!  Keep me posted and let me know if you have any questions or concerns.

**Comment by cwmagee** [comment]
I have email confirmation that Squid 3 works properly on Japanese Java.

**Comment by bowring** [comment]
ええ!

**Comment by bowring** [comment]
ええ!
