### ISSUE TITLE
Can't run Squid (or Topsoil) on Linux

### ISSUE THREAD

**Issue by pvermees** [CIRDLES/Squid#197]
I get:

> java -jar Squid3-1.0.1.jar
Error: Could not find or load main class org.cirdles.squid.gui.SquidUI
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

Operating system: Ubuntu 18.04.3
Java version: openjdk 10.0.2 2018-07-17

Similar errors occur when starting Topsoil:

> java -jar topsoil-v2.0.7.jar 
Error: Could not find or load main class org.cirdles.topsoil.app.MainWindow
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

I haven't tried the Oracle JRE this time, but when I did it so a couple of years ago to get Topsoil to work, it didn't help.

**Comment by bowring** [comment]
I haven't fired up Linux in awhile, but I know the JavaFX package is not automatically included.  You will need Java 1.8 and JavaFX as a start to run Squid and Topsoil.  I will look into this further as I have time.

**Comment by bowring** [comment]
Update: I created a brand new Ubuntu 18 in VMWare on my 64 bit Mac, assigning 4gb memory.
I executed these two commands:
sudo apt install openjdk-8-jre-headless
sudo apt-get install openjfx

Both Squid and Topsoil loaded and ran nicely.

Cheers, Jim

**Comment by bowring** [comment]
Note: the report files do not open automatically in LibreOffice, even though they are .csv, so find them in the Squid3_Reports folder located in same directory as jar file.

**Comment by pvermees** [comment]
I had Java version 10 installed on my computer. Downgrading to 8 fixed the issue:

/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java -jar Squid3-1.0.1.jar

Thanks a lot!
