### ISSUE TITLE
Squid Lab Data bugs

### ISSUE THREAD

**Issue by bowring** [CIRDLES/Squid#211]
While making the parameter models live relative to the data reduction, I discovered a couple bugs in the lab manager:

1) when a new model has the same name and version as an existing model, a warning should be posted, but instead Squid simply makes and shows an identical copy.

2) when opening the lab manager, each models dropdown box should show the current default model as selected.

**Comment by ryanbarrett1515** [comment]
When the user opens squid, the default models will be selected in the drop down menus.
If the user then changes the models selected in those drop down menus and then closes squid lab data (without closing the squid application) those models will remain selected. Do you want me to change this?

**Comment by bowring** [comment]
fixed in pull request #225
