### ISSUE TITLE
Getting concentrations into New Reference Material Model

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#231]
How do I get U and Th concentrations into a RM model when editing it for the first time?  It says there is no data in the table.

**Comment by bowring** [comment]
This is a bug - the workaround for now is to edit a copy of an existing model.  Please note that reference material models are not yet live - their values are not used in the math - the needed values are set currently by editing the expressions (in expression mahager) listined on the left as 'Reference Material Values'.  It is our intent to go live with reference material models soon, so please continue to build them in anticipation.  The next release (dues soon) - Squidv1.1.0 - will have live models for Physical constants and Common Lead.

**Comment by cwmagee** [comment]
For reference materials with multiple published values, is there a way to determine which values are being used?

**Comment by bowring** [comment]
Note: reference material models are not yet live (used in reduction) .  The architecture of these models provides for the user to create their own named and versioned reference material complete with TIMS ratios and uncertainties and concentrations and academic references, etc.  The model then calculates the 'apparent ages', which will be used in Squid3 when the models go live.  Thus, for each reference material, the user (or community) creates a different model: such as 'Temora McGee" and "Temora GA", etc.  These models are then available for general use.  The Squid architecture will also provide for importing reference material (and other parameter) models into Squid when they are found in a Squid project file or when simply supplied as an 'xml' model file.

Thus, a direct answer to your question is that one would simply open the model in question and view the ratio and other details.

Note: we are in the process of developing a 'dates only' reference material model that will have only ages and no supporting TIMS ratios to satisfy the transition from Squid2 as mentioned in issue #235.

**Comment by bowring** [comment]
fixed in pull request #244
