### ISSUE TITLE
OP File Handling

### ISSUE THREAD

**Issue by bowring** [CIRDLES/Squid#242]
OP file handling is now in beta and will need review and tweaking as we get more files to play with.

**Comment by cwmagee** [comment]
![image](https://user-images.githubusercontent.com/11417991/54730779-d03d1e00-4bde-11e9-89b5-bdeee4b78abc.png)

Tried importing op data (session 100158) and a standard ILC ten peak task...

**Comment by cwmagee** [comment]
Clearly it thinks that my Temora zircons are BR266-aged.

**Comment by sbodorkos** [comment]
In 'Manage Current Task', check your Reference Material Parameter Models - you will find "GA accepted BR266" (or something like that) is selected, by default. In the last week, I have built a "TEMORA2 dates only" RM Parameter Model, which you might like to use... I attach a ZIP of it here:

[TEMORA2 dates only v.1.0.zip] https://github.com/CIRDLES/Squid/files/2990720/TEMORA2.dates.only.v.1.0.zip)

Once you have downloaded and unzipped it, in Squid3, go to Resources... Parameter Models... Reference Material Models, and in the window that opens, in the File menu, select Import... from XML. With luck, you'll then be able to select TEMORA2 as your Isotopic RM.

I also have a similar M127 model (age and concentration) if that'd be useful...

**Comment by cwmagee** [comment]
Dunno if this is a bug or a feature, but after importing it, it doesn't appear in the dropdown menu until after I click away from, and then back to  Task-->Manage Current Task

**Comment by cwmagee** [comment]
Using your Temora parameter model, it now doesn't display a concordia diagram at all.

**Comment by cwmagee** [comment]
Changing back didn't help- still no display.
I will try reloading the .squid file

**Comment by cwmagee** [comment]
So I reloaded the squid file, went visualizations->ReferenceMaterials-> Concordia, and it reverted to the opening splash screen with the cool squid and the various languages. IS there a way to flag this as a bug, or do I need to open a new issue to do that?
-C

**Comment by bowring** [comment]
you should make an issue that includes your raw data file and the steps you are trying to follow so we can repeat them and see what's up

**Comment by bowring** [comment]
With the absence of a response from @cwmagee , I am confident these issue have been resolved via other issues, so I am closing this.
