### ISSUE TITLE
I seem to have already broken my new toy - opening a .squid file 

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#279]
I brought in a recent .xlm file and our usual task and was able to play about with it.  I also made two new Parameter models - GSC 6266 and GSC surface common Pb.  All was looking great.  I then saved the new squid project as .squid.  Everything looked normal in Project Manager, went to Expression Manager and the window was grey.  Tried to go back to Project manager and now all I get is the blue welcome page, no functionality.  Quit and re-opened said .squid file  - same behaviour.  

[915_1_2018_MAY_08_10.26.squid.zip](https://github.com/CIRDLES/Squid/files/2933242/915_1_2018_MAY_08_10.26.squid.zip)

**Comment by bowring** [comment]
remove your two duplicates in 1242 by renaming them and then visit the data / samples to see you groups and all will be well.  I will make this more robust!
