### ISSUE TITLE
Task Designer - Create New button WITHIN the designer

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#284]
Instead of having "New Task from Task Designer" be a separate menu item, have a "Create New " button WITHIN the designer. This way you are not making a new Task from outside the designer (and thus blind to what you are actually creating)

**Comment by bowring** [comment]
Is there a scenario where you have a stabilized design and each time you open squid with a new data file you just want to use the design by clicking the existing menu item to make a task from your design - should we have both options?

**Comment by NicoleRayner** [comment]
It seems to me, since the Task Designer is “sticky” that default task is already in there and it is more intuitive to just go into the designer and say “Create”.  I really don’t like the idea of a blind Create and I find it kind of confusing why these activities that are nested (you need a design before you create) are separated out.  This double-menu thing seems to be a structure that is in ET-REDUX too (although I can’t quite remember where) and as a beginner user there I always look at it and think “what am I supposed to do here?”  It is one extra click and I think worth it.  Mileage may vary for others....

**Comment by bowring** [comment]
You convinced me ;-)

**Comment by cwmagee** [comment]
Depending on how robust tasks end up being, I suspect that the vast majority of task writing will consist of minor changes to existing tasks, rather than writing brand new ones from a blank slate.
