### ISSUE TITLE
Parameter Models lockdown precludes SQUID 2.50 comparisons

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#285]
I've been trying to configure Parameter Models that will allow me to intercompare SQUID 2.50 and Squid3 results. This has involved the construction of new Reference Material Models, where I am trying to use Reference Dates mode. 

Basically, I need to be able to specify that '238-U/235-U' (currently greyed out and hidden in the Data tab) = 137.88, in conjunction with my Reference Dates. Can't be done at present, which is a function of the data modelling.

Noah says Ref_238U235U is a property of the RM, and that's true in the strict sense, but the everyday reality is that the value is **not** measured during 'routine' characterisation of an RM, not in the way that all the other ratios in the 'Data' list are measured. Essentially the former is assumed, and the latter (set) are measured and calculated on the basis of that assumption. 

There are broader science implications associated with that reality, but those are a separate issue...

**Comment by bowring** [comment]
@ryanbarrett1515 - please put 238U/235U on its own tab that is available to both flavors of reference material model.

**Comment by bowring** [comment]
fixed in #288
