### ISSUE TITLE
Nesting of Related Activities: Manage Spots and Reference Materials

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#292]
In the Data menu, we ask users to define their Isotopic RM and their Concentration CM by specifying the appropriate prefixes... this seems to me to be the logical place in which to map a parameter model to each of those prefixes. Because the choice of parameter model for RMs is much more strongly controlled by the materials actually analysed, than by the choice of Task.

Below is an annotated screenshot depicting a way in which this activity could be nested. 

![image](https://user-images.githubusercontent.com/17473203/54565453-6e37b980-4a22-11e9-9c4f-559893184016.png)

One of the key aspects (and this is a recurring theme in Squid3 as it stands) is the need for an alphabetised list of all the (compliant) RM options, so the user is not working 'blind'. In real use, there is potential for this list to be pretty long, so we could provide some simple assistance to the user, by auto-highlighting the Parameter Model that is the closest alphabetical match to the user-specified prefix. (For the screenshot scenario, either the first model that starts with T, or if none, the model with the name preceding T in the alphabet. It follows from this that the primary element of parameter model names for RMs needs to be the name/identity of the material, with lab/version/reference secondary.)

It would be helpful to have a 'mini-viewer' in each case, providing a non-editable view of the most relevant Parameter Model values, for easy reference (should be enough for the user to determine whether the highlighted Parameter Model is the one they want to use, or whether they need to keep browsing through other Parameter Models that possibly have very similar names). 

The button 'View Full Parameter Model' would open the Reference Material Models window (as accessed via menu Resources..., item Parameter Models...), for the highlighted Parameter Model, in non-editable mode, so that all its parameters could be browsed in detail, if desired.

The button 'Select This Parameter Model' would formalise the user's choice. These controls would **replace** the green-highlighted controls that are currently on the Manage Current Task screen. (As a precaution, this button could be greyed-out whenever the user has "0 spots selected".)

Finally, on balance, I think it would be nice if the user-specified prefixes in the Data: Manage Spots and Reference Materials screens were persistent i.e. when this screen is opened, the prefixes should be pre-populated with whatever was last used (yes, even if it results in 0 spots selected!). This will be convenient for those of us that rarely switch RMs. And for those that do switch frequently, re-specifying their prefixes is really not much different from the current requirement to specify them from scratch each time.

**Comment by cwmagee** [comment]
A few points:
I assume a parameter model is just a selection of reference values packaged up for use by the project? 

To make isotopic reference materials generalizable beyond the U-Pb system, you could replace the three "ratios" shown there ("206Pb/238U date" etc) with the first three appropriate ratios in the parameter model. If you want to get fancy, you could make your code smart by displaying the first three ratios which involve elements that are actually in the run table. (So, for example, for a Temora parameter model, if the run table included 16O and 18O, you would show the Temora 18O/16O ratio, if the run table included U and 206Pb, you would show the 206Pb/U ratio)

**Comment by bowring** [comment]
implemented in v1.1.4
