### ISSUE TITLE
Fragility testing

### ISSUE THREAD

**Issue by cwmagee** [CIRDLES/Squid#296]
I'm trying to load and manipulate some old datasets which have already been published, to see what usability issues appear when I try looking at data which I know once worked...

**Comment by cwmagee** [comment]
Concordia line doesn't plot in Tera-Wasserburg Visualization.
Also, with the mouse wheel zooming, you might want to limit the SW corner of the plot to not zoom below zero. While there might be some exceptional circumstances where you want to look for negative ratios, plotting non-physical analyses generally isn't something most people want to do:
![image](https://user-images.githubusercontent.com/11417991/54801729-61ce8d80-4cbc-11e9-88d2-479cdecacbd5.png)

**Comment by cwmagee** [comment]
With Report Tables -> Quick View report tables: 
These would be a lot more useful if the spot labels and column headers were anchored, instead of scrolling out of view.

**Comment by cwmagee** [comment]
We need a "no concentration standard" option for data set which don't have a concentration standard.

**Comment by bowring** [comment]
it would be helpful if you made an issue out of each item and supplied data files and and settings you used in each case

**Comment by cwmagee** [comment]
Separate issue for concentration standardless data:
https://github.com/CIRDLES/Squid/issues/302
