### ISSUE TITLE
editing function files - defining a default value for an argument

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#304]
looking at the definition for sqbiweight - requires 2 arguments, the variable and tuning constant.  When using this in via Isoplot in Excel tuning is optional.   (Although possibly when left blank the default tuning is 6 - see image below).  Is there a way of setting an argument to a default value within the .java file? Or just leave as comment in definition for user to figure out?  

In this case I would wish to define arg1=6 but I can think of other cases where this will be helpful e.g PbCanDriftCorr must = false for wtdmean to work.... 
![image](https://user-images.githubusercontent.com/40035242/55425121-b17c4700-554f-11e9-9868-25eaa5c4d938.png)

**Comment by sbodorkos** [comment]
Hi Nicole, sadly not true, and the reason why it is (tediously) necessary to work right through the nested functions for things like BiWt and WtdAv, right up until the code actually delivers the values back. If you execute "=biweight(Range)" in a spreadsheet, you'll find you replicate the result with "=biweight(Range,9)", not "=biweight(Range,6)". There are two potential causes for this:  

1. The user-defined function you invoke in a spreadsheet is functionally different to the one invoked directly in the VBA "back-end".
2. Although Tuning is set to 6 by default in the code in your screenshot, there exists downstream VBA code that resets it to 9. Just for fun, I think the documentation of the default (in the Isoplot 3.75-4.15 manual) is incorrect... but I haven't rechecked that recently.
  
Unfortunately, this sort of thing is pervasive in Ludwig's code. Biweight was one of the very first things @bowring and I looked at, and we had a disproportionate amount of trouble with the arithmetic. One of the "issues" we identified is that neither of the candidate Tuning values has any real "natural precedence" (which might have helped define a default), even for frequent users of the function. We thought it might be clearer and simpler to simply demand the user specify their Tuning value every time.  

Easy enough to revisit. For what it's worth, I explicitly set Tuning = 9 every time I use it... but I haven't had a lot of exposure to what others do.

**Comment by sbodorkos** [comment]
...and regarding my option 2, the other possibility is that the default Tuning is set to 9 by some **upstream** function/subroutine (i.e. one that calls BiWt), so by the time you reach the code in your screenshot, Tuning is always pre-populated, and the line "VIM Tuning, 6" is always obsolete. You could evaluate that (if you care enough!!) by adding a Watch to the Tuning (inside Public Function BiWt), and executing "=biweight(Range)" with no Tuning value specified.

**Comment by NicoleRayner** [comment]
Very bad indeed.  There are two issues here,  - a mathematical rigour issue when trying to exactly replicate SQUID2.x but also an ease of use issue for the "less experienced" user.  Certainly we can leave tuning as a editable argument, but now I'm thinking about what the best way would be to provide guidance for unfamiliar users.  I see two options: 1) a comment in the definition - "when in doubt use 9" or 2) a default value embedded in the expression (probably also accompanied by a comment in the definition).  I don't think I have a preference here (maybe leaning towards #2) but wondering what you think.

**Comment by sbodorkos** [comment]
@NicoleRayner yes, agreed. 

I also discussed this with @bowring last week, and he suggested that we could implement different 'flavours' of the function where the tuning was explicit, things like "=biweight6(Range)" and "=biweight9(Range)". These would be in addition to the current function of form "=biweight(Range, Tuning)". 

If we go this way, we will need to think about whether there is a broader pattern that needs following in 'LudwigLibrary' fiunctions (e.g. WtdAv1 and WtdAv2 for explicit specification of the magnitude of the input uncertainties?).
