### ISSUE TITLE
SQUID 2.50 Tasks not importing correctly

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#306]
This issue relates to the "four horsemen" (i.e. "Special U-Th-Pb") expressions for my test Task "Zrn 10pk Perm2 ConcU" ([SquidTask_Zrn 10pk Perm2 ConcU.GA.zip](https://github.com/CIRDLES/Squid/files/3052067/SquidTask_Zrn.10pk.Perm2.ConcU.GA.zip)) The first screenshot shows its (correct) expression-set, as viewed in SQUID 2.50's Task Editor:

![image](https://user-images.githubusercontent.com/17473203/55690168-398ba200-59d1-11e9-8f56-931f217addee.png)

The second screenshot shows this Task imported into Squid3 (Side-note 1: it'd be really nice to be able to Save these imported Tasks; I lose a lot of time because I have to use a lot of different SQUID 2.50 tasks to do the arithmetic testing, and every time I switch Tasks I need to re-import from scratch). 

This shot comes from "Task-->Manage Current Task" (Side-note 2: I suggest suppressing the 'breadcrumbs' across the top of all these screens, at least temporarily. At present they are inaccurate pretty much everywhere!)

![image](https://user-images.githubusercontent.com/17473203/55690228-d51d1280-59d1-11e9-9237-cb84c6f40519.png)

It is clear that expression for Uncor_208Pb232Th_CalibConst (yellow) is not being addressed correctly. I am working my way through all the Perms at the moment, and might be able to shed light on the overall pattern once I have done a few more... or it might be obvious to @bowring what's going wrong...

For what I am trying to do, I think I can work around this manually, at least for the moment... The version of Squid3 is 1.1.3.

**Comment by NicoleRayner** [comment]
Hi @sbodorkos ,  a little work around so to deal with the fact that you can't save an imported task is to save the squid project and then when you want to use that task again open the .project file and replace the data.

**Comment by sbodorkos** [comment]
@NicoleRayner thanks, that is a really good idea. I guess I have always been a bit unclear on how to use Projects (I make one at the beginning of each Squid3 session because I have to, but I usually don't bother Saving them). Now it's clear that at least for as long as I am relying on SQUID 2.50 Tasks, I should be creating and maintaining one Project per Task... cheers
