### ISSUE TITLE
Squid3 v1.1.6: Reference CRM values mismapped as RM values

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#310]
This is only a little one, but it has stopped me in my tracks for the moment (though that doesn't matter; I have identified a larger issue as well, to be documented separately). Below is my Spot Naming and Reference Materials screen, all set up the way I want:

![image](https://user-images.githubusercontent.com/17473203/56167662-1a69c180-601c-11e9-8b35-8cedf14f7ed4.png)

But when I generated my Report Table, I found **all** my Concentration data (U and Th) were zeroes. This was confusing because my Task had no Unhealthy Expressions. But I found at least part of the problem when I checked the RM values, specifically Ref_Th_Concen (as I am trying to test a Th-centric Task):

![image](https://user-images.githubusercontent.com/17473203/56168131-97496b00-601d-11e9-82f9-cdf9041c8e45.png)

It shows me a zero (in contrast to the value of 418 ppm I was expecting, from my first screenshot), but helpfully points me at the Notes, and the Notes explain the problem. The explanatory sentence "Reference Th content of CM" is correct, but it is clear that the value is being taken from the wrong Model (see my first screenshot). "TEMORA2 dates only" is my **Isotopic** RM model, whereas Ref_Th_Concen should be taken from my **Concentration** RM model.

Same problem with Ref_U_Concen.

**Comment by bowring** [comment]
Please supply models.

**Comment by sbodorkos** [comment]
Can't find them. Squid3 must know where they are, if the screenshot is any indication... but it isn't telling me! I am searching all my hard drives and network drives using Windows Explorer - no joy yet.

**Comment by sbodorkos** [comment]
[M127 values only v.1.0.zip](https://github.com/CIRDLES/Squid/files/3082490/M127.values.only.v.1.0.zip)
[TEMORA2 dates only v.1.0.zip](https://github.com/CIRDLES/Squid/files/3082493/TEMORA2.dates.only.v.1.0.zip)
