### ISSUE TITLE
CSV report (RM Squid 2.*-style) rounds 4cor_208Pb232Th_Age_RM to 4 significant figures

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#326]
This is a very minor one, relating to the **reporting** of **4cor_208Pb232Th_Age_RM** (and by association, its 1sigma absolute uncertainty). Everything looks fine when inside Squid3; below is the relevant Expression Manager window, which shows the full double-precision values in the Peek. These are correct in detail (i.e. "perfectly" matched to SQUID 2.50).

![image](https://user-images.githubusercontent.com/17473203/58133453-3427a580-7c67-11e9-9d0f-16a90acd6ddc.png)

However, when the data is output to a Report Table (in my case, via Custom Report Tables... Reference Materials... Report Table per Squid2.*), these data have undergone symmetrical arithmetic rounding to 4 significant figures:

![image](https://user-images.githubusercontent.com/17473203/58133959-b795c680-7c68-11e9-86ba-2e8dd5a0ee7f.png)

This issue persists across all 8 permutations of (Perm2/Perm4 + 204corr/207corr + Ucentric/Thcentric). It did not surface during Perm1 testing because in Perm1, neither SQUID 2.50 nor Squid3 perform calculations that give rise to 208Pb/232Th ages. I have not yet done any Perm3-based testing, but based on what I have seen, I would expect the problem to persist there.

It seems to be isolated; I have not yet found any other expression that is affected.

**Comment by bowring** [comment]
I found the culprit - a specification to show 4 instead of 15 digits in the report at those columns - a typo/bug.  Repaired in next release.
