### ISSUE TITLE
Non-issue: Results of comparisons for Perm2 and Perm4

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#327]
I did these two Perms together because the arithmetic for dual-calibration Tasks is essentially invariant; the only determining factor is which calibration (Pb/Th or Pb/U) is evaluated first. There were a total of 8 permutations to be tested:

1. Perm2 + 204corrected + Thcentric
2. Perm2 + 204corrected + Ucentric
3. Perm2 + 207corrected + Thcentric
4. Perm2 + 207corrected + Ucentric
5. Perm4 + 204corrected + Thcentric
6. Perm4 + 204corrected + Ucentric
7. Perm4 + 207corrected + Thcentric
8. Perm4 + 207corrected + Ucentric

Discrepancies arising were broadly similar to those documented for Perm1, and for the same reasons (i.e. the issues are Perm-independent). In general, I will not revisit these, other than to explain "after-market" adjustments to the SQUID 2.50 workbooks, implemented universally in order to minimise disagreement with Squid3 results in a transparent way.

### SQUID 2.50 source files and outputs

**Building blocks**
My comparison uses an edited version of SQUID 2.50.11.02.03 (VBA code has been modified in order to fix bugs and minimise discrepancies in the results of double-precision arithmetic between VBA and Java). If you're confident in your ability to switch versions of SQUID 2.50 in Excel 2003 and you want to try it out, it is included in this ZIP, together with the 4 relevant Tasks (spanning Perm2/Perm4 and Thcentric/Ucentric), and my (GA Session 180050) 10-peak zircon XML test file: [SQUID2.50+FourPerm2and4Tasks+180050XML.zip](https://github.com/CIRDLES/Squid/files/3205478/SQUID2.50%2BFourPerm2and4Tasks%2B180050XML.zip).

**Results**
If you'd rather just fast-forward to my SQUID 2.50 results based on that combination of files, they are here. The first set comprises 8 "live" Excel SQUID-workbooks corresponding to the 8 cases defined in the list above: [180050_SQ2.50_Perm2and4_notfrozen.zip](https://github.com/CIRDLES/Squid/files/3205383/180050_SQ2.50_Perm2and4_notfrozen.zip). The second set comprises the same 8 SQUID-books in "frozen" format i.e. with formulae stripped, and all cells containing evaluated results: [180050_SQ2.50_Perm2and4_frozen.zip](https://github.com/CIRDLES/Squid/files/3205385/180050_SQ2.50_Perm2and4_frozen.zip).

**"After market" adjustments included in these Results**
The suffixes "BM_BX[BZ]_CR" refer to the SQUID 2.50 Excel-columns where I have made adjustments to improve agreement with Squid3. The BM and CR adjustments are invariant across all 8 cases under consideration; the BX[BZ] adjustment is an invariant substitution, the location of which depends on whether the originating Task is Perm2 or Perm4.

_Column BM (magic number):_ In Perm2 and Perm4, this column contains the concentration of the "secondary parent" element (e.g. Th when the concentration RM is defined in terms of its U content, and vice versa). In Perm2 and Perm4 Tasks in SQUID 2.50, this involves invocation of the hard-coded 'magic number' 0.9678, which turns out to be a coefficient linking present-day Th abundance to present-day U abundance by reference to present-day 238U/235U (noting that Squid3 models present-day 238U/235U as a property of the reference material, rather than a universal physical constant).

For the purpose of this comparison, in the SQUID 2.50 workbooks, I have manually replaced the magic number 0.9678 with the full double-precision quotient of the analogous expression in Squid3:

![image](https://user-images.githubusercontent.com/17473203/58139311-8378d080-7c7d-11e9-9d98-aded6ce0b13e.png)

Without this adjustment, secondary element (ppm) values between SQUID 2.50 and Squid3 usually diverge at the first or second decimal place; afterwards. After adjustment, the ppm difference is usually smaller than 1e-10.

_Column BX[BZ] (12 significant-figure rounding):_ This dataset contains an interesting one-off complication that illustrates some unintended consequences of universal 12-significant-figure rounding in both SQUID 2.50 and Squid3, implemented by @bowring and I in an attempt to get "best possible" agreement between isotopic ratios and NU-switched Task equation, with the aim of minimising downstream divergence.

The issue relates to the %err values associated with Uncor_208Pb232Th_CalibConst, which in this dataset encompass values both above and below 1%. After rounding, values above 1% have 11 decimal places; those below have 12. This means that when values diverge between SQUID 2.50 and Squid3 at the final digit (of the rounded data), the cell-by-cell difference is a full order of magnitude greater when the values being compared are greater than 1%, than is the case when the compared values are less than 1%. This is true even in the "1.01% vs 0.99%" case.

In the current dataset, the magnitude of SQUID 2.50 vs Squid3 "final-digit" divergences is 1e-12 for 8 of the first 23 TEMORA analyses (1, 2, 4, 11, 14, 18, 19, 21), because the compared values span the range 0.60% to 0.98%. But for the final analysis (Tem.24.1) has a value of 1.52%, so its "final-digit" divergence is 1e-11, and that analysis alone outweighs all of the other 8 in terms of its effect on the %err values for the common-Pb corrected 208Pb/232Th, which in turn influences the inverse-variance weighted mean A value, which in turn affects all the downstream "built-in" expressions. This result in widespread and contradictory (albeit minor) discrepancies when comparing the SQUID 2.50 and Squid3 datasets.

To mitigate the issue, I manually pasted the Squid3 value (1.52247762935) over the top of the SQUID 2.50 value (1.52247762934) for the %err associated with 'Uncorr Pb/Th const' in analysis Tem.24.1. This resolves the immediate problem, but it also underlines the need to abandon 12-significant-figure rounding in both SQUID 2.50 and Squid3 as soon as practicable.
 
_Column CR (Pb76 function output):_ This is the same issue as outlined in Perm1: the LudwigLibrary function "=Pb76(416.8)" yields a value of 0.0551127497968983 in Squid3, and 
0.0551127497968982 in SQUID 2.50. In this comparison, I manually pasted the Squid3 value over the top of the SQUID 2.50 value for "Std_76" (i.e. RefRad_207Pb206Pb). This minimises (but does not completely eliminate) the systematic errors downstream.

### Squid3 source files and outputs

**Building Blocks**
The version of Squid3 I used is 1.1.8. Here are the 4 relevant Project files (spanning Perm2/Perm4 and Thcentric/Ucentric): [Sq3 118 180050 PERM2+4 CONCTh+U.zip](https://github.com/CIRDLES/Squid/files/3205492/Sq3.118.180050.PERM2%2B4.CONCTh%2BU.zip).

**Results**
If you'd rather just fast-forward to my Squid3 results based on that combination of files, they are here. This ZIP ([118 180050 Sq3 Perm2and4 CSVs.zip](https://github.com/CIRDLES/Squid/files/3205611/118.180050.Sq3.Perm2and4.CSVs.zip)) comprises 8 CSV files, corresponding to the 8 cases defined above, generated in Squid3 (after setting the index isotope in Visualisations... Reference Material... Weighted Means) via Report Tables... Reference Materials... Custom Report Tables... per Squid 2.x. 

### SQUID 2.50 vs Squid3 comparison: Perm2 and Perm4

Finally, the results of the actual comparison are here: [RM_Comparers_Perm2+4_Th+Ucentric.zip](https://github.com/CIRDLES/Squid/files/3205622/RM_Comparers_Perm2%2B4_Th%2BUcentric.zip). There are 8 XLS files, one for each case defined above, and each file comprises five worksheets:

1. "250_StdData": This is where the SQUID 2.50 dataset is Pasted and described. Cell A3 is the permutation number ("2" or "4"), Cell A4 indicates the index isotope ("4" = 204Pb, "7" = 207Pb), Cell A5 indicates the parent element by which the CONCENTRATION reference material is defined ("U" or "Th"). These values need to be entered manually, because SQUID 2.50 output varies depending on these settings. At cell A7, the rectangular array of SQUID 2.50 StandardData values (including the single row of column-headers) is Pasted (via sequential Paste as Values, then Paste Formats).
2. "250_Comprehensive": This sheet has no user input. It maps the data columns from "250_StdData" to the superset of Unique Expression-Names defined for Reference Materials by @NicoleRayner and I (see column L of [ExpressionNames.AcrossPerms_v5_NR+SB.xlsx](https://github.com/CIRDLES/Squid/files/3155904/ExpressionNames.AcrossPerms_v5_NR%2BSB.xlsx)). In general, yellow cells in row 7 represent entries from that 'unique name list' that contain 'row-by-row' data (as opposed to 'summary of column' data). Green cells in row 7 indicate uncertainties associated with the yellow cells (where those exist: note that the XLSX above does not explicitly consider the uncertainties associated with many (but not all) of the uniquely named expressions), with uncertainties labelled with magnitude and whether percentage or absolute. Orange cells represent Unique Expression names that pertain to 'summary of column' data (which I have postponed comparing, because of course those results will depend on the veracity or otherwise of the row-by-row data, which should therefore be considered first).
3. "Sq3_RMReport": This is where the Squid3 dataset is Pasted and described. As for "250_StdData", cell A3 is the permutation number ("2" or "4"), Cell A4 indicates the index isotope ("4" = 204Pb, "7" = 207Pb), Cell A5 indicates the parent element by which the CONCENTRATION reference material is defined ("U" or "Th"). The rectangular array of Squid3 data is Pasted in TWO PARTS (via sequential Paste as Values, then Paste Formats): (a) At **cell A7**, the single-row header and data for column A, and (b) at **cell B3**, the multi-row headers (starting with 'Spot Fundamentals' and rectangular array of Squid3 ReferenceMaterial data. This two-step process should yield a rectangular array of numeric data.
4. "Sq3_Comprehensive": This sheet has no user input. As for "250_Comprehensive", it maps the data columns from "Sq3_RMReport" to the superset of Unique Expression-Names defined for Reference Materials.
5. "CellByCell": This is where the magic happens... a cell-by-cell comparison of the two "...Comprehensive" sheets. Where the two counterpart cells both contain numbers, the SQUID 2.50 value is **subtracted** from the corresponding Squid3 number.

**Comment by sbodorkos** [comment]
### New issues discovered in the Perm2/Perm4 comparisons

There are only two, and only one of those relates to the proper function of Squid3:

**Column 4cor_208Pb232Th_AgeRM and its 1sigma abs:** Raised (and since addressed) in issue #326 .

**One-off (Tem.24.1) "Uncor_208Pb232Th_CalibConst_%err":** Issue arising from 12-significant-figure rounding as described in previous post. Because the Tem.24.1 value is effectively an order of magnitude larger than all the other discrepant values in the same column, it has quite a discernible effect on downstream calculation (because it affects WtdMeanA and thus everything that depends on that). 

I have manually mitigated this by replacing the SQUID 2.50-calculated value (1.5224776293**4**) with the Squid3-calculated value (1.5224776293**5**) in each and every comparison carried out in Perm2 and Perm4 (Perm1 is not affected). Perm3 comparisons have not been done yet, but will need the same mitigation.
 
### Issues shared with Perm1

These are re-summarised below, drawn together in one place for completeness (the Perm1-related descriptions are a bit dispersed):

**Columns 4cor_207Pb235U_RM, its %err, and 4cor_ErrCorrel_RM:** These comparisons are poor when the index isotope is **not** 204Pb, because SQUID 2.50 compromises the calculation of 4cor_207Pb235U_RM. Essentially, SQUID 2.50 performs the following:

4cor_207Pb235U_RM = (4cor_207Pb206Pb_RM) * (**Xcor**_206Pb238U_RM) * (Ref_238U235U)

which yields a compromised ("hybrid") result when X = 7 or (in the case of Perm1 **only**) 8. In Squid3, we do not permit 4cor_207Pb235U_RM to be populated with hybrid expressions of this type; instead, its evaluation is contingent upon valid evaluation of 4cor_206Pb238U_RM. The values for "4cor_207Pb235U_RM_%err", and 4corErrorCorrel_RM, represent the downstream effects of the 4cor_207Pb235U_RM calculation. None of these discrepancies need addressing, because the analogous SQUID 2.50 vs Squid3 comparison is "clean" when the index isotope is 204Pb. 

**Columns 204Pb206Pb_OvCtCorFrom207Pb and 7cor_Com206Pb_Pct_RM:** Minor but systematic discrepancies arise from "edge effects" in the double-precision arithmetic, relating to the evaluation of RefRad_207Pb206Pb i.e. reference 207Pb*/206Pb* of TEMORA2, via the LudwigLibrary function of the form "=Pb76(416.8)". 

The Squid3 solution (via Peek in Expression Manager) is 0.055112749796898**3**; the SQUID 2.50 solution in Excel 2003 is 0.055112749796898**2**. 

I have mitigated (but not completely eliminated) this effect by pasting the Squid3 value over the top of the SQUID 2.50 expression, in the "live" SQUID 2.50 workbooks.

**Comment by sbodorkos** [comment]
@bowring this is the end of the Perm2/Perm4-based comparisons; I don't intend to add anything further. I will make a separate "non-issue" for the results of the Perm3 comparisons, so feel free to close this one whenever you're ready.

**Comment by bowring** [comment]
Great progress!  New version has report fix.
