### ISSUE TITLE
New XML file (from updated SHRIMP control software)

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#336]
Hi Jim @bowring, bit of a spot-fire here in the early part of the week. Our SHRIMP control software has been upgraded (meaning a new XML file: this ZIP contains a mini-example [190034_GA5019_19061810.22.zip](https://github.com/CIRDLES/Squid/files/3301443/190034_GA5019_19061810.22.zip)) as part of ASI's efforts to test the new ion-counting system, which is to be part of SHRIMP V. 

That's not as much fun as it sounds, and an unforeseen wrinkle is that the XML file attached here is not parseable by SQUID 2.50. I am still trying to work out why that is (there is no meaningful error-trapping in this section of the VBA code), but I suspect it will be due to a basic deficiency in the parsing (Ludwig basically read them as text files).

No matter what, it would be good to get our XML schema updated with respect to this file, because I'd like to confirm that Squid3 really can validate and process it (I don't envisage any real issues), especially if the SQUID 2.50 issue rolls on. In addition, the XML files being collected during the current GA-based testing phase contain some (accidental) irregularities in the SBM data, which should be very efficient in highlighting the holes in our Squid3 error-trapping related to SBM-normalisation (and there are plenty of holes - we passed over the bad-data cases in order to get other, more worthwhile things done).

**Comment by bowring** [comment]
I have updated our schema to validate this file and open it with Squid3, showing 4 spots.  Note that the file does not validate against its own supplied schema at: http://shrimp.anu.edu.au/prawn_file.xsd.

This change will appear with the next release.

**Comment by sbodorkos** [comment]
Yes, it is all happening on the run - the first iteration of data collected had no SBM data at all (not even zeroes) because the control software was still being written when they started collecting data. I will remind Peter to update the schema when I talk to him next (which is why I am working on the SQUID 2.50 XML-parsing issue - when I find it, I will ask him to implement a SQUID 2.50-tolerant fix while I have his attention, rather than me trying to develop and distribute some after-market solution to all the SQUID 2.50 users out there).

**Comment by sbodorkos** [comment]
@bowring, further to our discussion a couple of hours ago, attached a ZIP containing 3 larger XML files (session 190033) written using same format/schema as the micro-file 190034 that started this thread. By suffix:

- **minus1st** = XML file in which the first two spots have 9 mass-stations, and all the others have 10. SQUID 2.50 does not handle this; interesting to see what Squid3 does.
- **minusFirst3** = XML file in which all remaining runs have 10 mass-stations. Squid3 ought to parse and process this, however, SQUID 2.50 does not, because the newline-bug precludes effective parsing.
- **minusFirst3_newlines** = XML with extra line-feeds added so there is only one parameter per line (no other modifications). SQUID 2.50 handles this file fine, and for Squid3, handling ought to be identical to the "_minusFirst3" file.

I did not trigger any SBM-related error messages in SQUID 2.50, so maybe you won't encounter any issues in Squid3 either. But it will be interesting to see. I'm sure @cwmagee mentioned the occurrence of "zero-SBM" patches somewhere in this run (even after the first 3 spots were excised).

[190033_GA5019_19061714.26_3newXMLs.zip](https://github.com/CIRDLES/Squid/files/3306120/190033_GA5019_19061714.26_3newXMLs.zip)

**Comment by bowring** [comment]
The two files with all 10 mas-stations opened just fine.  minus1st choked Squid3 as designed - we decided early on to initially only support a uniform number of mass stations - if we want to handle this, we will need an algorithm such as simplistically cutting out all the tenth mass stations? Or asking the user to make some sort of decision?  I am adding for the time being a message to the user that Squid3 is detected the problem.

**Comment by bowring** [comment]
PS. It turns out only the first 2 runs (M127) have 9 mass stations.  By catching the problem, Squid3 can ignore the 10 th mass station on the remaining runs and a choice of Tem as reference material makes everything seem correct when a 9-mass default task is applied.  Obviously room for improvement as we explore exotic use cases.

**Comment by cwmagee** [comment]
The first two remaining, because the first one is already cut. 
In the spirit of xml, can tasks simply ignore any peaks which they don't need?

**Comment by sbodorkos** [comment]
@cwmagee It's not straightforward because peaks need to be identifiable (in both run-tables, not just one of them) before a Task can know whether it needs that peak or not. Ludwig knew this, which is why the Task-XML matching in SQUID 2.50 was restrictive. At present, Squid3 requires that all analyses in the one file have the same number of peaks, but even that is only a broad constraint; there is nothing to stop a user taking the ANU 9peak run-table midway trough a session, and perhaps adding 232Th while deleting 248ThO. The resulting run-table would still have 9 peaks, and would still be processable by Squid3, but you'd presumably get gibberish after the changeover because the peaks would no longer be properly identified relative to the mappings that applied at the beginning of the session (because 238U would have been the 7th peak before the run-table change, and the 8th peak afterwards, having been supplented in 7th spot by 232Th).

Ludwig guarded against this scenario by forcing the user to specify the isotopic composition of each species in a Task, so he could enforce mass-equivalence (within user-specified tolerance) relative to the XML. We don't want to go that way, but it's likely we'll still need to engineer some "auditor" of run-tables on a spot-by-spot basis for any given XML input. The problem is obviously tractable, as we will have labels and masses for each peak in each analysis, so we should be able to provide at least educated guesses at peak-equivalences in 9peak vs 10peak scenarios... but it's something we'd need to do from scratch.

**Comment by bowring** [comment]
Handled per above in release v1.2.3
