### ISSUE TITLE
Strange non-function of "4 horsemen" expressions in Perm2 xenotime Task

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#337]
This one from Allen Kennedy overnight - he tried the most recent available version of Squid3 to reduce some xenotime data, but found the data-reduction didn't work. Based on the files he provided, I created my own Squid3 project based on the files he provided: [AKK_XENO.zip](https://github.com/CIRDLES/Squid/files/3318785/AKK_XENO.zip)

The files supplied by Allen comprise a Prawn XML, a SQUID 2.50 Task, and also a Squid3 Reference Material Model (XML) for the reference xenotime named "Y2". All three are in this ZIP: 
[Kennedy_SourceFiles.zip](https://github.com/CIRDLES/Squid/files/3318788/Kennedy_SourceFiles.zip)

Topically enough, this Prawn XML file features an **impossibly high SBM zero value** (presumably set on a much different meter-range), so it is essential to specify **SBM normalisation OFF** in order to get any sense at all out of the data. We have not yet implemented any error-trapping for 'invalid SBM' issues, so it is something we will have to look at. 

_(To begin with, I suggest a simple warning during Prawn XML parsing (e.g. "Found SBM count-rates lower than SBM zero at some mass-stations (ABC occurrences in total)", where ABC is a count of the number of permutations of species X/scan Y/analysis Z for which "sub-zero" count-rates were diagnosed). Even if the dialog-box just has an "OK" button, at least the user will know they have an SBM-related problem to deal with.)_

**But the issue I couldn't solve** (see my Project file) is that none of the "NU-switched Expressions with Uncts" are evaluating, and for the two "Uncor..." calibration constants, I have no idea what the issue is. Furthermore, the "ParentElement..." expression won't even validate in the Manage Current Task window, although I can't see a problem with it. I did note that the "ParentElement..." Expression in the Expression Manager is flagged "RU" when it would ideally be flagged "C", and it's not possible for users to manually alter that flagging, so I wonder if that is part of the issue.

Anyway, I'd appreciate any insights @bowring @NicoleRayner , for my own edification as well as Allen's.

**Comment by cwmagee** [comment]
Fyi, sbm background counts are proportional to the resistance of the selected resistor, or inversely proportional to the range. So a high background means that the background was taken on a smaller range.

**Comment by cwmagee** [comment]
Different beam monitors will have different numbers, but just for a ballpark estimate, our SBM has the following zeros:
Range   background cps
3  pA     375000
10pA     102000
30pA      34000
100pA     9300
300pA     3100
1nA          400
3nA          200

**Comment by bowring** [comment]
This instance uncovered a bug in an untested branch of the logic for no SBM as implemented in Squid3 from the correct logic here: https://github.com/CIRDLES/ET_Redux/wiki/SHRIMP:-Sub-EqnInterp .  Fix implemented and being tested - standby.

**Comment by bowring** [comment]
ps: Side effect fixed issue with four horsemen;  Note however that "ParentElement..." Expression in the Expression Manager is flagged "RU" is correct because the RU refers to the targets supplied to the expression, as seen in the results.  New version on the way.
