### ISSUE TITLE
General type tasks

### ISSUE THREAD

**Issue by cwmagee** [CIRDLES/Squid#342]
Can we have the "General" option in the manage task screen enabled so that we can try importing and matching isotope ratio mode squid 2.5 tasks?

**Comment by bowring** [comment]
The General option has not even been addressed in Squid3 and the option only appears as a reminder of a future feature.  @sbodorkos - thoughts?

**Comment by sbodorkos** [comment]
To be honest, I would need to re-familiarise myself with their function in SQUID 2.50 first. But in broad terms, the functionality of a General (i.e. non-Geochron) Task would be entirely enveloped by that of a Geochron Task (ignoring potential enhancements to RM models that would make life easier for non-Geochron users; see below).

In general, non-Geochron Tasks comprise Isotopes, Ratios with Uncertainties, and Custom Expressions that operate on those Ratios (and on each other). And that's about it.

In Manage Current Task screen terms, we would still use everything down to "Samples:", as well as the first two Parameters (SBM Normalisation and Ratio Calculation Method radio-buttons). All other Parameters (and all the Directives) would be inapplicable, and I imagine them being greyed-out whenever Type = General in the top-right corner of this screen.

It follows that in the Manage Expressions screen, the subcategories "NU-switched Expressions with Uncts" and "Built-in Expressions" are also inapplicable, and ideally would be greyed-out for General Tasks.

What I don't know (and need to review) is how (or even whether) RM analyses and unknowns are separated, and whether there are any "standard operating procedures" for normalising analyses of unknowns to some reference value of the RM. So I'm not yet certain what changes would be needed to the screens corresponding to the first two items in the Data... menu.

**In terms of associated new work**, I can envisage expansion of RM models (both Isotopic and Concentration) into ratios and elements significantly beyond the traditional U-Th-Pb set. At the moment, that sort of thing is often bespoke in SQUID 2.50 (i.e. people manually modify their Tasks at each use to reflect reference values of interest), but in Squid3, I can imagine an RM Model enhancement whereby a user gets to add reference isotopic ratios (or elements) of interest to an existing RM model, by specifying the desired isotopic numerator and denominator (or the element), and then specifying its reference value. 

But this new work could be delayed; it would be possible to 'enable' SQUID 2.50-style non-Geochron Tasks without it. But not until I review StandardData/SampleData behaviour in non-Geochron Tasks.

**Comment by bowring** [comment]
[handled in v1.5.5](https://github.com/CIRDLES/Squid/releases/tag/v1.5.5)
