### ISSUE TITLE
Grouping Video

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#349]
@bowring I have no idea how to upload this video to CIRDLES.org on YouTube. Can't for the life of me remember how I did the Perth ones last Christmas. 

Hopefully you can access the file (ZIP from WMV) here: once you have finished, feel free to close this "issue".

[GroupMe_v2_1-52.8_edit2.zip](https://github.com/CIRDLES/Squid/files/3395118/GroupMe_v2_1-52.8_edit2.zip)

**Comment by bowring** [comment]
viewed
