### ISSUE TITLE
Bug-> PrawnFile -> Manage Spots & Choose Reference Materials

### ISSUE THREAD

**Issue by cwmagee** [CIRDLES/Squid#35]
Squid3 Version: 0.1.4
Java Version: 1.8.0_131
OS: Windows 7 6.1

Issue details:
After editing duplicate spot names, all other spots starting with that initial letter are not selected when filtering by prefix. EG if two of the 28 Tem-X grains are renamed, then they are the only ones which show up when filtering.
[100157.squid.zip](https://github.com/CIRDLES/Squid/files/1374427/100157.squid.zip)

**Comment by bowring** [comment]
This was an oversight based on an early assumption that all spot names were upper case - the fix is to make spot names case-insensitive for filtering, so that a filter of "T" or "t" will find spot names starting with "T" or "t".
