### ISSUE TITLE
Peak stripping 

### ISSUE THREAD

**Issue by cwmagee** [CIRDLES/Squid#352]
How involved would it be to adapt the 204 correction math to a generalized peak-stripping equation? This would be really handy, particularly in ratio mode.

**Comment by bowring** [comment]
@cwmagee - Let's see what can be done per your ratio mode issue first.

**Comment by bowring** [comment]
@cwmagee - revisit this now that we have ratio mode and make a new issue with how-to details if you feel it is needed.
