### ISSUE TITLE
Documentation of Grouping-related algorithms completed

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#360]
Well... I think it is, anyway. And in theory, this give us end-to-end data-processing... the final product ought to be "Grouped-sample" type outputs, which ought to be comparable to the results of "Group Me" in SQUID 2.50.

[Procedural Framework Part 7](https://github.com/CIRDLES/ET_Redux/wiki/SQ2.50-Procedural-Framework:-Part-7-(Group-Me)) comprises three segments (7a, 7b, 7c) relating to [204-overcounts](https://github.com/CIRDLES/ET_Redux/wiki/SQ2.50-Procedural-Framework:-Part-7a-(204-overcounts)), [Common Pb corrections](https://github.com/CIRDLES/ET_Redux/wiki/SQ2.50-Procedural-Framework:-Part-7b-(Common-Pb-correction)), and [Group-extraction](https://github.com/CIRDLES/ET_Redux/wiki/SQ2.50-Procedural-Framework:-Part-7c-(ExtractGroup)) algorithms respectively, plus their associated subroutines.

[https://youtu.be/BHIo6qwJarI](url)  

No doubt there will be a zillion problems, so let me know... and hopefully Charleston-based people will stay safe from Hurricane Dorian in the meantime!

**Comment by bowring** [comment]
this link :  https://youtu.be/BHIo6qwJarI  is not correct

**Comment by bowring** [comment]
implemented in v3.1.2
