### ISSUE TITLE
Categories/members for Weighted mean sorting

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#379]
As discussed with @bowring today, here are my proposed categories/members for sorting in the weighted mean visualization window (pending further refinements/expansion of capabilities as discussed).

Hours (self explanatory)
Order of analysis (same as hours but with a normalized time axis to avoid big gaps)
Raw ratios (members = ratios defined in tasks, just as currently setup)
Species cps (members = cps of each species)
Composition (members = U ppm, Th ppm, 232Th/238U)

These should allow for a preliminary evaluation of the data with ability to identify "oddballs" (based on compositional characteristics e.g. Th/U, or zircon quality characteristic e.g. 204cps or instrumental behaviour e.g. UO/U) and then deselect them from the weighted mean.

**Comment by bowring** [comment]
will be enabled in release 1.4.6
