### ISSUE TITLE
Report builder - one little bug and a suggestion

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#380]
I love this tool and its functionality, I just have one tiny bug to report and also a suggestion for simpler user interface.
The bug: when you export a csv for a single unknown sample using the DEFAULT template, it saves it to a file named "unknowns", not the name of the selected sample.  The file itself is correct (in only contains the data for that one file), only the name is incorrect.  This does not occur if I use a custom report template.

My suggestion: the action buttons on this window change depending on what you are doing and I find it unnecessary and often confusing, especially if I start one thing then change my mind and want to back out to do another.  I think the only buttons needed would be:
New
Copy
Save
Save As (so that if you edit your copy you can save as  new name)
Delete
Import
Export
These would be displayed along the top at all times.  In an ideal world "Save" would be greyed out when the active version is identical to the saved version, but as soon as any changes were made, the "Save" button would be come live again.

**Comment by bowring** [comment]
addressed in v1.4.1
