### ISSUE TITLE
quirks when importing Custom expressions

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#385]
I recently imported a folder of custom expressions saved a while back (from v 1.2.2).  One expression (that worked in 1.2.2) throws a parsing error but it was a bit diabolical to track down.   See the **Hfppm.xml** file in the zip folder. It was only when I went to Edit the expression in TEXT mode (not drag and drop) could I see that a special character (an A with a little accent above it) was inserted prior to the ± symbol.  Once I deleted that, it was all good.  Not sure if there is a good solution to this, or just worth to noting in upcoming documentation that parsing errors should be diagnosed in text edit mode.  
On the same theme of importing custom expressions, if the custom expression pertains to a particular sample (not "UNKNOWNS"), the sample selection does not carry over when one imports that xml (or the folder).  See expression **1242_WtdAve_76ratio.xml**   Again, maybe the solution is just a message box upon import that reminds users to verify the targets (all unknowns vs individual unknowns) for imported expressions.

[Jan 7 clean expressions from v141.zip](https://github.com/CIRDLES/Squid/files/4031306/Jan.7.clean.expressions.from.v141.zip)

**Comment by bowring** [comment]
Fixed in release v1.4.9
