### ISSUE TITLE
Report builder - more finessing

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#386]
4 ease of use suggestions and one validation/error handling observation:
Ease of use:
- when in View mode and moving/reordering a column  to a region out of range one needs to drop the column at the edge, then scroll over, then pick it back up and move it further.  Request ability to drag/auto-scroll if possible.
- selected report template should "stick" when you go between toolbar items not return to default
- if I REMOVE a category or a column from my Report template I can't "Save" it, it is greyed out.    Only adding things (and re-ordering) triggers the ability to save.
- this is very fussy but when the csv's are created it appends the words "RefMat" in the file name BEFORE the report template name and the word "unknowns" AFTER the report template name.  It should be BEFORE in  both cases.

Validation/Error handling:
If there is a problem with the columns selected for your template (like one of the selected columns   returns a value of 0 because of a problem with an expression within it, eg.   something divided by 0) it will not PREVIEW or CREATE it just appears non responsive.  Even just an error message that says "csv not created, verify selected columns" would be helpful to indicate that the problem is in the template.

**Comment by ryanbarrett1515** [comment]
Can you provide an example/screenshot for the validation/error handling so that we can look at that in greater depth. Broken expressions aren't available to the report builder so we're a bit confused.

**Comment by NicoleRayner** [comment]
[964_3_2019_Oct_09_SQV1.4.1.zip](https://github.com/CIRDLES/Squid/files/4042913/964_3_2019_Oct_09_SQV1.4.1.zip)

Attached is a squid project with a custom expression called "bad test expression".  It is Zr cps/0.  If I add it to my report template the "peek" value shows as all zeros (it doesn't actually become an unhealthy expression for some reason) and it won't preview a report or make a csv.  If I exclude it from the report template all is good.  

This first happened to me for another reason, there was some other problem with my expression but it didn't show as unhealthy, just a bunch of zeros.  I can't exactly recall what that problem was but I tried to re-create by dividing by 0 and that did it too.

**Comment by ryanbarrett1515** [comment]
Your bottom 3 suggestions and the validation/error handling will be fixed in the next release. The auto scrolling functionality is something we're currently investigating but isn't easy to do in JavaFX so we may or may not add that in the future.
