### ISSUE TITLE
Squid3 on new PC - doesn't recognise its Models

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#387]
A lot of teething issues getting Sq3 running on my new Win10 PC, which have essentially stopped me from looking at any of the functionality of actual interest.

My "clean install" of 1.4.1 resulted in a version of Sq3 that would not talk to any of its Models. I checked the auto-generated folders, and the models were present as XML files... but they wouldn't show up in any of Sq3's dropdowns, nor did they appear in Sq3's Parameters Manager. When in the latter, I tried to import the Model XML files, and got an error: "Sq3 warns you: null".

That was a show-stopper, so I quit Sq3 and restarted it, in the hope it would make a difference. There were still no Models in the dropdowns or the Parameters Manager, but this time I found I **could** import the Model XML files from their various folders. So I did that. One Model at a time, for each of the different Model types.

Obviously this should never be necessary. I think the whole point of the pre-packed Models is to ensure that they are automatically available first time, every time, even in a brand-new installation of Sq3 on a computer that has never seen it before.

The rest of it was just relearning, and wasted time stemming from unacknowledged directionality in the data-processing. I had forgotten, for example, that it is necessary to have your RM and CRM properly specified in the Data... window **before** you import your Task, because if they are not configured correctly (e.g. set to 'NONE - v1.0'), then your re-imported Task and Expressions will **never** function properly, no matter what you do - it seems Tasks only read the RM and CRM Model settings at the time of initial import, and not at any subsequent time.

I understand that we need to work around these things during the active development phase of the software... but the user experience is terrible. It has taken me 3 hours to get all my Expressions working - and now I find that not all the windows will resize to the real estate available on my screen. So that's me done for today, but I'll go and make another issue for the window-sizing.

**Comment by NicoleRayner** [comment]
This is strange to me:

> "it is necessary to have your RM and CRM properly specified in the Data... window before you import your Task, because if they are not configured correctly (e.g. set to 'NONE - v1.0'), then your re-imported Task and Expressions will never function properly, no matter what you do - it seems Tasks only read the RM and CRM Model settings at the time of initial import, and not at any subsequent time."

I have not had this experience myself (and I just did a bunch of tests just now to try and create what you described, to no avail.  I actually get a message telling me to define by RM and CRM and even if I ignore it it still will work once I define them late in the game).  What I have often forgotten to do and not been able to get anything to work is to "Manage Isotopes".  Once I remember to do that is falls into place.

**Comment by sbodorkos** [comment]
Yeah - I am wondering if that initial Project is no good (and never will be any good) because it was created in a Model-less Sq3. It also has trouble remembering its Common Pb and Physical Constants Models, but I can remediate those via the Manage Task window, and my changes stick... no dice with the RM Models though.

I think I'll just abandon that Project and create a new one from scratch, and try to replicate the problem there (I suspect I will not be able to). Which will be fine - might just be "fresh install" glitchiness, which obviously won't have been an area of focus for Jim. I am feeling much better about all this today than yesterday!

**Comment by ryanbarrett1515** [comment]
We were unable to replicate the problem on our computers
