### ISSUE TITLE
Possible Bug with common Pb assignment for unknowns

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#392]
Hi Everyone,
I have tried to assign a new Common Pb model to my unknowns. I always get the same concordia diagram for the unknowns. As a test, I then made a new Common Pb parameter model, which I called Crazy Common Pb (6/4=200, 7/4=100, 8/6=20). I assigned this model to my unknowns and still got the exact same concordia diagram for the unknowns. If I assign the Crazy Common Pb to my standard in the manage Task window the concordia diagram for the standard changes.

**Comment by bowring** [comment]
Thanks @AllenKennedy - working on it ...
