### ISSUE TITLE
Breadcrumbs refinements requested

### ISSUE THREAD

**Issue by bowring** [CIRDLES/Squid#405]
@NicoleRayner notes that the first two menu items under Interpretations / Unknowns do not leave the menu item highlighted.

Also, the Save (not Save As ..) menu item in Project should not change the highlighted tab to project as it can be executed from any window without leaving the window

**Comment by ryanbarrett1515** [comment]
I created a pull request

save doesn't make the project menu get highlighted for me...I'm only highlighting on the launches
