### ISSUE TITLE
Select ratio table

### ISSUE THREAD

**Issue by cwmagee** [CIRDLES/Squid#41]
Squid3 Version: 0.1.7
Java Version: 1.8.0_131
OS: Windows 7 6.1

Issue details:
It would be the axes ought to be labelled "numerator" and "denominator". Also, selecting an entire row or column by clicking the label would be handy. The display will have issues with run tables were decimal mass stations are used, unless some sort of auto scaling can be done.

**Comment by bowring** [comment]
Clarification please @cwmagee : will clicking a column or row toggle all of the ratios on or off in that column or row or reverse the population (on>>off and off >> on) ?

**Comment by cwmagee** [comment]
all on, or all off iff all are already on.

**Comment by bowring** [comment]
Provided in v0.2.0.
