### ISSUE TITLE
Prob of fit exclusions is affected by the "sort by" column

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#415]
Not sure if this is a bug or a miscommunication on my part but the exclusions using the Prob of fit slider are being controlled by the "sort by" selection, when it should not be.  The goal of sorting is merely to visualize trends in the data and to understand why a given zircon date might not belong to the group.  The prob of fit selection should only apply to the "Calculate WM from" selection.

Attached is a .squid file for testing, its the same one I've been using for a while though so no need to download it if you already have it.

[964_3_2019_Oct_09_SQV1.4.1.zip](https://github.com/CIRDLES/Squid/files/4148821/964_3_2019_Oct_09_SQV1.4.1.zip)

**Comment by NicoleRayner** [comment]
Another tweak related to the "sort by" so I will leave it here as opposed to a new issue.  Right now the default "sort by" field = "calc WM from" field.  And if you switch your "calc from", the "sort by" changes as well.  I think it would be best if the default "sort by" was "SpotIndex".  The "sort by" selection should persist (either the default SpotIndex or a user specified parameter) even if the "calc from" is changed.

**Comment by bowring** [comment]
@NicoleRayner - Great catch!  Both issues addressed in v1.4.7.  The benefit of "release early and often" is more eyeballs!
