### ISSUE TITLE
Audit raw data - displayed mass deltas don't update when you remove a spot

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#419]
I'm starting to make demo videos and have gone back to the first few menu items (importing data etc) and noticed that when I delete a spot in Audit Raw Data, that the plot of the Mass Deltas doesn't update (the data for the "removed spot" still stays visible).  See issue #152

**Comment by bowring** [comment]
can't replicate ... need more info

**Comment by NicoleRayner** [comment]
This little video demos it.

[media.io_Data audit bug.zip](https://github.com/CIRDLES/Squid/files/4160220/media.io_Data.audit.bug.zip)

**Comment by bowring** [comment]
got it ... just the deltas behave this way and if you remove the delta and recreate it it comes back healthy ....  good catch.

**Comment by bowring** [comment]
good video too!

**Comment by bowring** [comment]
fixed in next release.
