### ISSUE TITLE
Help -> Online resources -> Github repository bug

### ISSUE THREAD

**Issue by cwmagee** [CIRDLES/Squid#42]
Squid3 Version: 0.1.7
Java Version: 1.8.0_131
OS: Windows 7 6.1

Issue details:
Help -> Online resources -> Github repository bug does not open anything in a browser. It doesn't do anything at all. Maybe a GA firewall issue?

**Comment by bowring** [comment]
There is no underlying action yet, so this is not a firewall issue, but a missing code issue.
