### ISSUE TITLE
SpotIndex should be 1-based for UI

### ISSUE THREAD

**Issue by bowring** [CIRDLES/Squid#421]
Suggested by @sbodorkos , The SpotIndex used to sort spots in the WM UI should appear to start at 1 instead of zero for more compelling user experience.

**Comment by NicoleRayner** [comment]
Great idea.  For readability there should also be a double colon (::) separating the SpotIndex/Hours "sort by" value from the "Calc by" value, just as there is for any other "sort by" parameter.
