### ISSUE TITLE
glitch in toggling spot exclusion when you switch between Time Sorting and other sorting in WM

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#423]
A suggestion, a request and a bug:

- [x] Would be nice if SpotIndex was the default sort for each sample unless otherwise changed by the user

- [x] the exclusions should persist if you switch between samples (and when you close a squid project and then reopen it)

- [x] If the Sort by parameter is changed (say to a raw ratio), then changed back to SpotIndex (or Hours) the selection/toggle off action gets confused and the wrong spot is deselected.  If this isn't clear, I demo it in the video.

https://youtu.be/Px0u6pqnB1o

**Comment by bowring** [comment]
SpotIndex is currently the default - does this mean you want a way to change the default?

When you say exclusions, do you mean for the 7 ages only or for any other weighted mean?  (the latter is a big todo).  Currently the min percent prob is saved with each age per each sample and when the sample / age is revisited when the the probability filter is on, the exclusions are regenerated.  It seems you are suggesting saving the exclusions made when the filter is turned off?

third point is well-taken!

**Comment by NicoleRayner** [comment]
Happy that SpotIndex remains the default (and I don't need to change it). It is just that if I change the sorting for **one sample** (say to U ppm because I think there are 2 age groups defined by composition and I want to see that) and then I go to **a different sample**, the sorting I see right away is not the default (spotIndex) but whatever I just did for the previous sample (in this example U ppm). 

Keeping the exclusions for the 7 ages is the most important thing.  The other things are less critical, and since I can "save" them by writing the stats to a csv, I am good.

**Comment by bowring** [comment]
v1.4.8 contains these fixes (coming soon!)
