### ISSUE TITLE
When summary calculations sneak into report builder

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#426]
I'm not sure if/how this is resolvable but I recently noticed that one of my summary calculations snuck into the report builder.  When I first built the template, I had NOT flagged this particular expression as a summary calc and I added it in error to the template.  Now when I use this template in a file where this same expression IS flagged as a summary it still is available in the report builder and a non-sensical value is shown in the Peek window.  Watch attached video if this is not clear.
[When A Summary Calculation Sneaks Into A Report-1.zip](https://github.com/CIRDLES/Squid/files/4251226/When.A.Summary.Calculation.Sneaks.Into.A.Report-1.zip)

**Comment by bowring** [comment]
fixed by #429
