### ISSUE TITLE
WeightedMeanReport bugs

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#427]
- [ ] the "sort by" parameter name is given as the "WeightedMeanName" instead of the "Calc from" parameter

- [ ] If the report csv is open and you try and append (or create a new one) to it you get the following message "Report file does not exist".  This isn't true, it does exist you just can't get at it.  This message box also comes up (as you would expect it to) if you try and append but a new file doesn't yet exist.

- [ ] This is sort of related to the above point: it is currently not possible to see if a report exists for a given sample before you choose "New" or "Append".  If there was an existing one and you chose "New", the existing one gets wiped out and replaced by the new one.  I don't have a proposed solution off the top of my head, but maybe the simplest solution is not to write the file automatically but instead open window where the user creates a new csv or appends?  We can discuss possible ways around this on Monday, just flagging this here for now.

**Comment by bowring** [comment]
1 - not sure what you are talking about re: "sort by" issue
2 - that is a "windows" issue - but fixable
3 - your idea is probably the best as folks are used to that scenario in general

**Comment by NicoleRayner** [comment]
[WeightedMeanReportForSample_10493.zip](https://github.com/CIRDLES/Squid/files/4262242/WeightedMeanReportForSample_10493.zip)
The attached zip files shows what I mean.  This is the output of some weighted mean AGES but you can see that the column labelled WeightedMeanName is populated by "SpotIndex" (which was the sort by parameter), not the Age type.

If we implement the idea from -3, -2 becomes mostly moot so might not be worth the trouble to fix.

**Comment by bowring** [comment]
Fixed in release v1.4.9
