### ISSUE TITLE
bug in sorting weighted means

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#443]
I'm not sure if this is resolvable because I can't seem to recreate this in a new .squid file, but as you can see here the weighted mean plot of an unknown is not sorting by Spot Index.  It sorts properly by other parameters.  I'm including the squid project file too in case that helps with diagnostics.
[962_2_2019_Dec_23_12.14.zip](https://github.com/CIRDLES/Squid/files/4553445/962_2_2019_Dec_23_12.14.zip)

![squid spot index no sort](https://user-images.githubusercontent.com/40035242/80630423-30c59e00-8a22-11ea-9b63-6850f7cc1161.JPG)

**Comment by bowring** [comment]
You have encountered a file trapped in a wormhole of updates - go to "Manage Isotopes" and click "Apply Task ... " orange button.  Also, on a per WM basis switch to Hours and then back to SpotIndex.    I had a note about this from our March meeting, but could not find the file.  Will not happen to new files.
