### ISSUE TITLE
Bug when "Replacing" custom expressions  when importing from folder 

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#444]
If I import a folder containing custom expressions and select "Replace all", the first expression in the folder gets duplicated (the IMPORTED expression show up twice), but the rest get replaced.   

![problem with replacing expressions](https://user-images.githubusercontent.com/40035242/80642422-768b6200-8a34-11ea-849f-a236fdd29f2b.JPG)

If I say "replace" to each individual expression, each one gets duplicated.  
In each case it is the IMPORTED expression that shows up 2x, the old one is not preserved.

If this isn't clear and you wish to test, you can open the attached .squid file and you will find within it an expression called aaa = 2.  The folder has a custom expression where aaa = 1.  If you import the custom expressions and say REPLACE for each (not replace all) you will see you will end up with 2 expressions called aaa = 1.

[SQUID3.zip](https://github.com/CIRDLES/Squid/files/4554395/SQUID3.zip)

When I REMOVE one of the duplicate expressions, both are wiped out but when I RESTORE the removed expression, only one comes back (the imported one).

**Comment by NicoleRayner** [comment]
I also just noticed that LnPbU, LnPbU-sample, LnUOU, and lnUOU-sample are exported to the custom expressions folder even though they are NU-switched expressions.  no big deal but they are susceptible to the doubling up issue raised above.

**Comment by bowring** [comment]
fixed in pull request  #447
