### ISSUE TITLE
Error in concordia plotting - error correlations

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#465]
I'm not sure how long this has been the case, but I just noticed today that my error **_ellipses_** are awfully circular in SQUID3.  So I exported the data and plotted it in Isoplot to confirm that the problem was in the plotting not the math/ratios.  Indeed there is a problem.
![Concordia diagram isoplot4 15](https://user-images.githubusercontent.com/40035242/85748620-32d07400-b6d6-11ea-90e3-084ab41d4f09.JPG)
![Concordia diagram Squid 1 5 1](https://user-images.githubusercontent.com/40035242/85748625-33690a80-b6d6-11ea-94ec-6b3d8f371fe9.JPG)

I tried importing this data into redux to see what happens there but I wasn't successful (but I also didn't spend a lot of time trying).

**Comment by bowring** [comment]
The shape is related to the correlation, so we need to examine that field and also see if Topsoil has introduced a problem.  Can you supply the Squid file (zipped)? or tell me if I have it already?

**Comment by NicoleRayner** [comment]
I just plotted it in Topsoil and it is fine. 
![Concordia diagram topsoil](https://user-images.githubusercontent.com/40035242/85754637-387c8880-b6db-11ea-82df-523f76002f13.JPG)
Stand by for the zipped file.

**Comment by NicoleRayner** [comment]
This was Topsoil version 3.0.0 alpha

**Comment by NicoleRayner** [comment]
[975_1_2020_Feb_24_10.36_cal1.zip](https://github.com/CIRDLES/Squid/files/4832475/975_1_2020_Feb_24_10.36_cal1.zip)
