### ISSUE TITLE
Reports folders - some tweaks

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#466]
- [x] A "SQUID3_Reports_v1.5.x" folder is still created in the directory where SQUID3 resides even though this isn't needed anymore (since the reports folder goes where the .squid file lives)

- [ ] Within the reports folder there still is a "Task" subfolder - back in April we discussed getting rid of this as it makes for very long file paths which in the windows environment is an obstacle to opening.  I see no benefit to this subfolder.

- [ ] (let me know if you want this as a separate issue) In the Custom Report builder menu can we define which report template is our default and then THAT is the one that gets used to make the reports when "Generate All Reports" is selected? (I really like this feature BTW)

**Comment by bowring** [comment]
good catch on 1
on 2, I left the task there for now as I realized we need to decide for certain that a project will have only one task
for 3, please make an issue
