### ISSUE TITLE
Minimum external 1sigma err for 206/238

### ISSUE THREAD

**Issue by cross-a** [CIRDLES/Squid#468]
Squid3 Version: 1.5.2
Java Version: 1.8.0_251
OS: Windows 7 6.1

Issue details: Currently the minimum external 1 sigma 206/238 error (or reproducibility) has a minimum set at 0.5%. I say users should have the freedom to set this to less than 0.5% or even to 0% if they wish.

**Comment by cwmagee** [comment]
The minimum should be zero. We have great zero-excess-scatter SHRIMP data from Squid 2.5, and a potential method for generating it.
