### ISSUE TITLE
Change the default plot box aspect ratio to ~1: 1.2 

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#469]
Please move the slider that separates the data from the plot over to the right so the resulting plot has an aspect ratio of approximately 1:1.2 .  With this as the default setting this will make the plot a bit more square (as is standard) and provides an immediate view of the data/sorting parameters.  With this as a default setting the user will not adjust the plot size on a regular basis thus making arbitrarily sized plots which would then need to be tweaked to match when importing into figures.

**Comment by bowring** [comment]
I am going to assume wider than taller even though per Wikipedia: The aspect ratio of a geometric shape is the ratio of its sizes in different dimensions. For example, the aspect ratio of a rectangle is the ratio of its longer side to its shorter side – the ratio of width to height, when the rectangle is oriented as a "landscape".
