### ISSUE TITLE
RefMat visualizations - other X-Y plots, add error bars

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#471]
Allow the option of including (or not) error bars on the X-Y plots in RM Interpretations.  Choices should be 1sigma, 2 sigma or None. 

Others might have a feeling about the utility of error ellipses - I don't think they are useful here - just error bars.  @sbodorkos @cwmagee @Shrimpjock ?

**Comment by bowring** [comment]
handled in release v1.5.5
