### ISSUE TITLE
Ratio mode - reports

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#475]
I am unable to make a custom report in ratio mode (seemingly due to the absence of a RM - according to the message in "column details" window).  I can successfully "Generate all reports" and the counts/ratios (which is all I am after) are in the "Redux and Topsoil" csv but not in the "report table for unknowns".  Attached is a zip folder with the squid project and the reports folder.
[DeadtimeinSQUID3.zip](https://github.com/CIRDLES/Squid/files/4960541/DeadtimeinSQUID3.zip)

**Comment by bowring** [comment]
Ratio mode does not support reference materials yet, although you can select them, so the short answer is treat spots as unknowns until this use case is specified.

**Comment by NicoleRayner** [comment]
Its no problem that I don't have a RM (I don't actually need one in this case but good to know) - its just that I can't make a custom report, and the lack of RM _seems to be_ (according the message in the columns detail window) what is holding up that functionality.

**Comment by bowring** [comment]
I unchose the RM and then could write a custom report for unknowns, by clicking the unknowns radio button and create report.  Let me know if that works.

**Comment by bowring** [comment]
see attached
[JIM_Deadtime.squid.zip](https://github.com/CIRDLES/Squid/files/4961259/Deadtime.squid.zip)

**Comment by bowring** [comment]
There seems to be a bug in re-opening the squid project where it renames the isotopes ... researching; just drag and drop the isotopes again.

**Comment by NicoleRayner** [comment]
You are right, I made this report template with RM as a target, not unknowns.  My mistake.  There might be some UI things that we could do here to prevent dumb mistakes like this (and others that I made when I was trying to produce these reports)
