### ISSUE TITLE
RM naming - delimiter vs filter

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#480]
I always assumed that the RM sample name was defined by the delimiter (just like all the other samples), not the filter used to assign it.  However this is not the case, which means when you go to the visualization (concordia or wt mean) the name of the RM is whatever you used to type into the filter.  If the RM has a really distinctive name, one might only filter using the first few letters: 
![RM name in name manager](https://user-images.githubusercontent.com/40035242/88429315-68937600-cdc4-11ea-86e2-9f8c4e6c2157.JPG)
![RM name in visualizations](https://user-images.githubusercontent.com/40035242/88429323-6b8e6680-cdc4-11ea-8406-6bcc612bb3af.JPG)

This is less than ideal, but is mostly an aesthetic/clarity of labelling problem on the plots.  Can obviously be overcome by typing in the full name of the RM into the filter, but if it is easy to transition the RM name from the filter to the delimiter that would be better.

**Comment by bowring** [comment]
So if you use the hyphen as the delimiter and the dropdown box of sample names to "type" your filter, you get TEMORA.  It appears you are using a count of 3 characters as the delimiter?

**Comment by NicoleRayner** [comment]
I have set the hyphen as the delimiter, not character count.  When I use the filter to define the RM (no dropdown box, just start typing in the the Manage Sample field) I might only type a couple of characters because that is enough to identify the RM (we commonly use one that starts with 6_ _ _ , most of our unknown samples start with 1_ _ _ _).  So then whatever I put in the filter (1 character, 3 characters) becomes the label that appears on plots etc (lower image above).  
![image](https://user-images.githubusercontent.com/40035242/88546743-d1f4ce00-cfea-11ea-851e-c90d3a05211e.png)

SQUID "knows" that the name is 6266 because that is what I have set in the delimiter (it shows up properly in the dropdown), it just uses the **_filter_** as the ID moving forward, not the name.

**Comment by bowring** [comment]
My point is don't type anything, use the dropdown box to get the full set of sample names and pick one.

**Comment by NicoleRayner** [comment]
Yes - there are many ways to solve this problem (type it fully, or use the dropdown).  Maybe we don't need the filter option, it provides 2 ways to do the same thing and one of those ways is prone to funny labelling further downstream.

**Comment by bowring** [comment]
I agree - I added the dropdown a while back but left the filter typing in ... it really serves no purpose since you are going to choose a sample by name ultimately.  OK if we remove it?

**Comment by bowring** [comment]
@NicoleRayner and @sbodorkos  - thoughts?

**Comment by NicoleRayner** [comment]
OK by my to remove the filter option.
