### ISSUE TITLE
Task management - naming and saving

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#490]
Loving the new ability to export tasks.  In doing so, I noticed a few little quirks in file saving/naming etc.  

I had a pre-existing task, when I saved it I gave the xml a new, tidier file name.  The xml file name did not replace the "Task Name" on the task screen. It should.  There should only be one name for it - the name on the file.  

Next I went to the task designer to make a new task ("New task from this design").  Back at the task manager this new task had the name/description/provenance of the task that was there before.  Any new task generated from the task designer should have these 3 field blank (or provenance could say "Task Designer").

**Comment by NicoleRayner** [comment]
I just noticed that the project naming/project file name interactions in the Project manager work perfectly (if you change the Project name when you "save as" it defaults to that name, and if you Save As and change the name, the Project name automatically changes to reflect that).  So hopefully just a matter of harvesting that functionality and applying it to the tasks.

**Comment by NicoleRayner** [comment]
Just like the provenance/name/description should be blank when a new task from the task designer is created, any of the custom expressions that were associated with the previously loaded task should be wiped out too.  I noticed this when trying to replace my custom task with one derived from the Task Designer, my custom expressions persisted.

An alternative that might be easier (?) or more desirable (?) is that a separate "Clear Task and Expressions" button is put on the Task Manager window so if you want to start from scratch.  you press that then proceed.  I don't have strong feelings either way on the best way forward.

**Comment by bowring** [comment]
addressed in release v1.5.8
