### ISSUE TITLE
Ma vs years in reports

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#492]
Currently, in the report builder Peek, the age is given in Ma, however when you output the report the age is given in years.  Please modify so that any ages are given in Ma in the report (NOTE TO USERS, an "age" is recognized where the expression name contains the letters a-g-e.)

**Comment by cwmagee** [comment]
So if I  make a calibration constant  vs Stage X expression, will it get confused?

**Comment by bowring** [comment]
no; StageX is the name of a spot property and not an expression in this context; but if you name the expression "stagexvscc" peek will present results in "Ma", i.e. divided by 1e6;

**Comment by bowring** [comment]
done as of v1.5.10
