### ISSUE TITLE
Description of task appears when you hover over task name in menu

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#494]
In order to provide a bit more information about what is contained within a task,  when one hovers over the task name before loading it from the Squid Task Library it would be helpful for the content of the "description" of that task to appear.  This will give the user more information about what is IN the task before opening it. For example a task name might specify 9pks but I cannot tell _which 9_ until I open it.  If the "description" was shown I would see it is for masses from 196-254, that helps me evaluate if this task is useful to me.   By doing it through the description, you do not encumber the file name with lots of detail.

On a related note @cross-a, the names of your existing tasks are not particularly meaningful (for example the Z1, Z2 thing is really unnecessary).  There might be some benefit to re-using the exact names that come with the pre-loaded tasks with Squid2.x  but this is also an opportunity to make them more concise and/or meaningful.  I don't feel strongly about either outcome but I thought I would bring it up in case you wish to revisit these names.

**Comment by NicoleRayner** [comment]
ETA - the description would appear whether you are loading from the Task Library, or loading any other .xml task (not in the library)

**Comment by bowring** [comment]
This latter request for a hover-description for any task.xml is not practical as that interaction would have to occur in the operating system's file opener - but:  we could have a 'peek' mode where you choose a task.xml and the description appears, and then you would have to decide to proceed to load; if not, repeat;

**Comment by NicoleRayner** [comment]
A peek mode sounds good to me.  It means an extra click to load a task but I think it is worth it to see what you are getting in advance.  Chime in @sbodorkos @cross-a @cwmagee if you disagree.

**Comment by bowring** [comment]
added in version v1.5.8
