### ISSUE TITLE
Tidying up of Resources and Help menus before next release

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#495]
Suggest moving "JavaDoc/Ludwig Library" into "Online resources" rather than a separate menu item
Suggest getting rid of Online Help (link to http://cirdles.org/projects/squid/#Development) as it is quite out of date and we don't really have plans to update that content (instead using Video Tutorials).  
Could alternatively put the link to www.cirdles.org  under online resources (I think putting the cirdles link rather than the squid link would be best here, might encourage folks to engage with topsoil).

**Comment by bowring** [comment]
done as of v1.5.10
