### ISSUE TITLE
What happened to Save WM plots as SVG or PDF?

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#497]
We used to be able to export WM plots as SVG or PDF (e.g v 1.4.7) and now that option seems to be gone.  
Also, RM concordias can only be exported as SVG. while pdf was an option for WM.  

All visualizations (concordias, WM, for RM and Unknowns) should be exportable.  My preference is as SVG and PDF, but I'm not sure if that is a big heap of hassle and I would be happy with just one file type in the short term..

**Comment by bowring** [comment]
Actually those buttons for WM never worked - they were just placeholders.  I dropped them since there seemed to be no interest.

**Comment by bowring** [comment]
Provided in v1.7.0
