### ISSUE TITLE
Manage Ratios can get out of sync with Manage Isotopes

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#498]
Attempting to make a new task based off the default 10pk task.  Add 2 masses (190 and 196.1), move background to position 5 instead of position 3.  Everything looks fine in the Manage Isotopes pane. 
![Isotope manager is correct](https://user-images.githubusercontent.com/40035242/93236995-82f72980-f74d-11ea-8be4-22770dcf095a.JPG)
However when I go to manage ratios, the grid does not reflect what is in the Manage Isotope table.  The chosen ratio doesn't match up and in some cases you can get bkg as a denominator/numerator. 
![Ratio builder is confused](https://user-images.githubusercontent.com/40035242/93237153-b76ae580-f74d-11ea-8442-4f512997a58f.JPG)
The problems occur for any ratios that incorporate species greater than 204.  I can't quite put my finger on where this problem crept in but I think inserting spots/moving backgrounds didn't translate over to the ratio builder.
Attached is the .squid project where this was identified.
[977_1_2020_Sep_14_11.48_with modified task from designer.zip](https://github.com/CIRDLES/Squid/files/5226377/977_1_2020_Sep_14_11.48_with.modified.task.from.designer.zip)

**Comment by bowring** [comment]
@NicoleRayner - thank you for exercising the designer and finding these issues; short-term fix is to deselect background in isotope manager (right click menu) then re-select background;

**Comment by bowring** [comment]
fixed in release v1.5.8
