### ISSUE TITLE
Task management menus

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#505]
This is great - I really like this new format. I have a couple of suggestions simplify things.  
Under "New Task" only have 3 options: Current task w custom expressions, without custom expressions and Empty.
Put the "default" tasks in the Library.  
Under Browse/Load/Edit, specify SQUID**_3_**where appropriate (not just squid).  I would change the name to "built in Task Library" to make it very clear what the library represents.  Likewise I would change the menu item to say "custom Task folder", rather than just folder.  Those two edits might make the difference between library and folder more clear.

It also seems to me that there is no need in this menu to have the option to load/edit an _individual_ task as well as browse the folder.  It is simpler, but just as effective to call this menu item Browse,  and it would only contain 3 choices: SQUID3 Built In Task Library, SQUID3 Custom Task Folder, SQUID2.5 Folder.  From _within_ the browse you then get to pick the individual task where you can either edit or replace.   On a related note, when I select a folder (and this is the case when I select a folder for importing of custom expressions) I can never see a list of the files that are within that folder (not to select, just to see the list of file names).  That is not great if I want to confirm that I have selected the "correct folder", but not sure if that is not really a tractable problem as it implicates operating systems etc.

**Comment by bowring** [comment]
great ideas!

**Comment by NicoleRayner** [comment]
On a related note, when in Data > Manage spots and RMs,  the blue hint bar should now read:
Task > View, New or Browse (not Task > Manage Task)

**Comment by bowring** [comment]
@NicoleRayner - when you say see list of file names do you mean all names even files that are not tasks?  If just valid task files, we could provide file name in tool tip hover, but they will likely be the same as the task name;  the folder name is displayed at the top;  also, when choosing folder, you can open it in your file explorer and still choose the whole directory .... need more details here as to what is needed.

**Comment by NicoleRayner** [comment]
When I browse files in my normal Windows File Explorer I see this:
![File explorer shows task name](https://user-images.githubusercontent.com/40035242/95592699-04716d00-0a17-11eb-8ced-4b80554701db.JPG)
When I browse to the same folder within SQUID3, this is what I see:
![SQUID3 browse does not show task name](https://user-images.githubusercontent.com/40035242/95592741-105d2f00-0a17-11eb-9e07-7f5e2895c28b.JPG)
The task is in there, it just doesn't show in a list so I can be 100% sure I have selected the correct folder until I actually say "Select Folder" and view in in the SQUID3 browser.

**Comment by bowring** [comment]
can't you click one more time and show the contents?  what is the filter at the bottom showing as an extension?  are you showing extensions in your file browser?  might need a screen-sharing session.
