### ISSUE TITLE
Loss of match between data and task isotope labels when editing task, no matter the edit

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#506]
If you are in the task editor and you select "replace then view current task", even if you have not made any changes to the task, you will lose the "match" in Manage Isotopes between  the data and task labels.  If it were possible to set this us so that any change to the task that did NOT involve adding/removing isotopes/background ID preserved the match in Manage Isotopes, that would be great.  Obviously if any isotope is added/removed or the background ID has changed (basically any action under Mass Labels), then action in Manage Isotopes will be required.

**Comment by bowring** [comment]
Can do - the nice thing is you can edit the task meta data (name etc) right from the view page anyway without jumping those hoops!

**Comment by bowring** [comment]
handled in release v.1.5.11
