### ISSUE TITLE
Custom report templates (including modified plot & sort) - make them sticky across projects

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#512]
It would be great if once a "custom report template" was imported, it remained available in the drop down list for all future projects (i.e. did not need to be re-imported every time).  I think that most labs are going to have 1 template (or rather one template per mineral/experiment type) that they use over and over, so not having to re-import it every time would be great.  I'm flexible on how best to achieve this - for example with a "make default" check box or something?
If the same could be done for the "plot and sort" report, that would be great too (so that any edits that are saved are then ported over to subsequent files) however this would be a secondary request.

**Comment by bowring** [comment]
done in next release
