### ISSUE TITLE
Isotopes (Data Isotopes Labels) no longer displays properly in Expression Manager

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#514]
The correct expression is in the text field at the top, but not in the typset image in the middle, nor in the peek box at the bottom (whatever expression was there before is stuck there).  

If you choose the cps expression to use elsewhere it works properly, it just doesn't show properly.  I tested this using v1.5.10 and it worked as expected, only occurs in 1.5.11

**Comment by bowring** [comment]
Fixed in next release.
