### ISSUE TITLE
Mouse position (without click) affects what action takes place in Task Editor

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#515]
As ever, it is interesting to watch someone else interact with software, they do things that I don't and you realize the little gremlins that creep in.  In this case, it has to do with the mouse position when you are adding masses in the Task Editor.  Even if you click the cursor on the line and add a mass, it is overridden by the position of the mouse highligher (even if it just drifts there - no click) when you press enter.  This can mean that masses don't get added as intended, or that masses get restored when you meant to add a different one.  See video:
https://youtu.be/eV6OdGHL8JE

**Comment by bowring** [comment]
Improved UI so button only allows adding masses; restore requires re-entry using add; and background mass index is set with a spinner.  Available in next release.
