### ISSUE TITLE
Toggle exclusion of spot in WM plot - doesn't work but just for the FIRST sample in the list

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#522]
If I go to Visualization - unknowns - weighted mean; on the first/default sample that is displayed  (e.g in Demo file that is 6266) I select a spot then right click to "toogle to exclude", nothing happens.  I can exclude by using the check boxes.
If I go to another sample (e.g. in demo file sample AAAA) and do the same, it excludes as intended.  Now if I go BACK to the first sample (6266) and right click/toogle to exclude it DOES work.

**Comment by bowring** [comment]
good catch - fixed in next release
