### ISSUE TITLE
Truncated text in "About Squid3"

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#530]
the text in the first and last paragraph in “About Squid3” blurb is getting truncated.  Not sure if this is because of my screen settings or something else (nothing else gets truncated just this).   
![about sq3](https://user-images.githubusercontent.com/40035242/99418942-8c298180-28c9-11eb-9b30-79f5567340e5.jpg)

**Comment by sbodorkos** [comment]
Off-topic @NicoleRayner , but your video tutorials are **brilliant** ! I had to put them on pause and go make some popcorn, so I could settle in for the whole lot back-to-back - what a great Wednesday evening!
