### ISSUE TITLE
Tera-Wasserburg Concordia visualisations are incorrect

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#531]
First, some housekeeping: the "Tera" in Tera-Wasserburg only has one r (it's a surname: see https://doi.org/10.1016/0012-821X(72)90257-9 ). It is misspelt throughout the Squid3 interface.

But more seriously, I noticed in video 3 (first appearance @ 9:07) that the Tera-Wasserburg Concordias are not constructed correctly (we never tested this! Perhaps Tera-Wasserburg wasn't available as an option last time we looked at it...). 

As you know, Wetherill Concordia plots require 5 input-columns: X, X-error, Y, Y-error, and **error-correlation**. But for Tera-Wasserburg Concordia diagrams, we only use 4 input-columns, because the **error-correlations are zero throughout** (the result is ellipses with major and minor axes that are parallel to the axes of the plot). At the moment, it looks like the T-W plot is using the same error-correlation values as the Wetherill plot did... which is no good.

I am not sure whether we need to edit this video (the screenshot does sit on the bogus OG1 Tera-Wasserburg diagram for quite a long time, unfortunately), but we definitely need to address the actual functionality of the software.

**Comment by NicoleRayner** [comment]
I wonder if this crept in when issue #465 was dealt with (conventional concordias DIDN'T have the error correlation).  WRT to the videos,  please keep a running tally of these sorts of things, as well as any other content/delivery suggestions (too much detail, not enough detail etc).  After the "dress rehersal" workshop with GA folks I can compile all of these are redo any videos that require changes.
