### ISSUE TITLE
_SQUID3 Google Drive

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#535]
@bowring can you please make a subfolder within the _SQUID3 Google Drive called "Video Tutorials" and give me edit access?  I will put mp3's of the video tutorials in there for those who have difficulty accessing YouTube through their networks.    Relatedly, there will need to be a link in the SQUID 3 Help menu to this Google Drive.  This seemed like the most sensible drive to me, if you have other suggestions, just let me know.

**Comment by bowring** [comment]
https://www.amazon.com/dp/B08FXV64ML?ref=KC_GS_GB_US

**Comment by NicoleRayner** [comment]
Interesting!  I’ll have a closer look next week.  Gotta run, it is my husbands birthday today and I need to pick up dessert (ice cream sandwiches, since the traditional ice cream cake with friends/family is too much for just two people)!

Nicole

**Comment by bowring** [comment]
Somehow I had some bogus links previously here.

Video Tutorials are in: https://drive.google.com/drive/folders/1PnGhJENKeN6lLJyruc8mGewiUp1DAeCX?usp=sharing

**Comment by NicoleRayner** [comment]
I have uploaded 3 videos to the Google drive as mp4 (videos 1, 2 and 4) today.  Please test that these are accessible to you @bowring

**Comment by bowring** [comment]
I can access them when not logged into google.  The clips seem to have been uploaded in when they were in the middle of playing as the thumbnails seem to be random?

**Comment by NicoleRayner** [comment]
I’m not sure why that is – I converted them into mp4 using HandBrake (at your earlier suggestion) and they just came in like that. I don’t know how to modify the thumbnail in anything other than Youtube  I’m not sure I care to worry about it at this stage.
