### ISSUE TITLE
Custom Report builder

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#540]
Should all the Built in Expressions for the task be available for drag and drop in the Custom Report builder?

**Comment by NicoleRayner** [comment]
They should be - but don't forget that RM expressions are only available for RM reports and likewise for unknowns.  As well, Summary expressions don't show up in the report builder (but their output can be exported using the report built for that purpose).  

I hope this captures the essence of your question - I often feel like expressions are "missing" but in the end they are usually covered by one of the two conditions above.

**Comment by AllenKennedy** [comment]
I will have to learn to export the Summary expressions. Thanks
