### ISSUE TITLE
2D regression in PLOT ANY TWO EXPRESSIONs

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#542]
Does the 2D regression use all the data points, even ones that have been excluded and not shown in the plot? I then removed the point in Data (Manage Spots), but still get the same regression. It would be good if we could see the effect on the regression of getting rid of a spurious point without editing the XML Prawn file. This isn't really and issue, just a future improvement.

**Comment by bowring** [comment]
I can't replicate what you are describing so you need to include files and more detailed descriptions of what you are doing;  generally, all you have to do is uncheck the point on the left side and it is removed from the regression;  there is no reason to edit the XML Prawn file.

Note: new video support here (see below)

**Comment by AllenKennedy** [comment]
Screen Shot 2020-12-23 at 2.40.41 pm

**Comment by AllenKennedy** [comment]
I think all regressions include the 0,0 point and are incorrect. I did a simple test, producing a data set that gives a perfect -1 slope regression. The 2D regression is wrong. Try plotting 206*/238 4 corr vs 238/206* 4 corr and then do a 2D regression.

**Comment by AllenKennedy** [comment]
I think all regressions include the 0,0 point and are incorrect. I did a simple test, producing a data set that gives a perfect -1 slope regression. The 2D regression is wrong. Try plotting 206*/238 4 corr vs 238/206* 4 corr and then do a 2D regression.

**Comment by bowring** [comment]
Can you supply the data set or the file?  Also where do you calculate 238/206* 4 corr and its uncertainty?

**Comment by bowring** [comment]
I confirm the problem with the following three expressions and then plotting **test1 against test3** - see image;  Mclean Regression works correctly, but Topsoil makes the plotting 
error.  Great catch @AllenKennedy !
```java
test1 = SpotIndex
test2 = count(["204/206"])
test3 = test2 - SpotIndex
```
![badregression](https://user-images.githubusercontent.com/1092963/103103401-d0a5ec80-45ee-11eb-84e7-eda8aad68c14.png)

**Comment by bowring** [comment]
Caveat - this is the special case where there arfe no uncertainties and Topsoil is supposed to use simple regression instead of McLean Regression, which it does, but reports it and plots it incorrectly.  Still need to confirm the case of data with uncertainties.

**Comment by bowring** [comment]
Definitely confirmed to be a typo in Topsoil that caused the inclusion of (0,0) into every dataset - great catch @AllenKennedy !
