### ISSUE TITLE
Refining spot removal and restore

### ISSUE THREAD

**Issue by bowring** [CIRDLES/Squid#547]
per @sbodorkos - open for discussion

Possibly the Restore functionality needs to be strengthened. One way would be to have a "Removed Spots" category in the spot-list, next to "All Samples". When you chose "Removed Spots", you'd be able to see the spots that have been Removed, and choose which (if any) you'd like to Restore (rather than just Restoring all Removed spots as at present). Note also that at present, Restoring Removed spots is only possible prior to Saving your Squid3 project: if you Remove a spot and then Save your Project, you are powerless to Restore it should you change your mind later (unless you reload the original XML file into the Project).

My feeling is that Removing spots should (after Save) quarantine them from calculations in that Project, until the user decides to reinstate them via Restore. At present, spots that are Removed are exterminated on Save, and there's no way back, which is not ideal.

**Comment by NicoleRayner** [comment]
I think the suggestion above is very sensible.

**Comment by bowring** [comment]
Provided in v1.7.0 with improved right-mouse context menus and sticky removals = always available for restoration.
