### ISSUE TITLE
RM Calibration Constant weighted mean calculations are incorrect when Probability of fit > 0.05

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#550]
This one is from @cross-a who came across while trying to use Squid3 on real data. (He is still using version 1.5.10, but I have taken a copy of his Project into my version 1.6.5 and Saved it, and it is the 1.6.5 version that is attached here: 

[200049_GA6458_SBv1.6.5.zip](https://github.com/CIRDLES/Squid/files/5773199/200049_GA6458_SBv1.6.5.zip)

Here's a screenshot of the Interpretation–RM–weighted mean data with all analyses included. Note Probability of fit < 1e-3, and 1sigma external spot-to-spot error = 1.03%. This is all perfectly fine and (according to SQUIID 2.50) arithmetically correct.

![image](https://user-images.githubusercontent.com/17473203/103712910-1612e280-500f-11eb-8ae9-7186f94bff50.png)

( **Side issue:** The captions for the second and third rows of the Wtd Mean result here should be "1sigma error of mean (%)" and "1sigma external spot-to-spot error (%)" respectively, with my "sigma" being symbolised. Been meaning to correct that for years... ).

Now, here's a screenshot of the same Interpretation–RM–weighted mean data with the biggest outlier (TEM-1.1) removed from the calibration. Note Probability of fit is now 0.13.

![image](https://user-images.githubusercontent.com/17473203/103713784-4491bd00-5011-11eb-9ff8-130ebb475f76.png)

In this situation (where Probability of fit > 0.05), the WtdMeanAcalc routine should be setting the external spot-to-spot error to zero (because by convention, it doesn't exist when Probability of fit > 0.05), and the corresponding 1sigma error of the mean should be arithmetically equivalent to the output of the WtdAv function (which is invoked from WtdMeanAcalc in any case, once the WtdMeanAcalc auto-rejection routine has been either enacted or bypassed).

So there is something wrong here, but it is not clear exactly what it is. Having reviewed my documentation of WtdMeanAcalc (https://github.com/CIRDLES/ET_Redux/wiki/SHRIMP:-Sub-WtdMeanAcalc), I think it is likely to be something happening inside WtdAv, possibly as a consequence of the arguments passed to it by WtdMeanAcalc.

But I don't know how WtdAv has been implemented, as part of Squid3's Ludwig Library. I don't think I ever documented the relevant Isoplot code; I think Jim @bowring did that himself, but I am happy to be corrected. I think we should start by looking at why Squid3 RM weighted means have non-zero external errors when Probability of fit exceeds 0.05, but it's possible we'll need to dig deeper than that.

**Comment by bowring** [comment]
@sbodorkos - the raw calculated weighted mean results used to produce the stats shown above in your attached images are displayed in the peek window of the expression manager, where you can also toggle the spots live:
All TEM:
```java
	[0] mean            : 0.00413205306898011
	[1] 1-sigmaAbs      : 4.26086666153017E-5
	[2] err68           : 1.24709693930471E-5
	[3] err95           : 2.53222775645044E-5
	[4] MSWD            : 2.26947593815653
	[5] probability     : 7.65069187206424E-4
	[6] externalFlag    : 1.0
	    LargeRej Indices: None
	    WmeanRej Indices: None
	Manual reject indices: None
```
TEM-1.1 Excluded:
```java
	[0] mean            : 0.00413998555362976
	[1] 1-sigmaAbs      : 8.53722108784403E-6
	[2] err68           : 1.02241255568546E-5
	[3] err95           : 2.07980849822264E-5
	[4] MSWD            : 1.36395565914657
	[5] probability     : 0.127592414338081
	[6] externalFlag    : 0.0
	    LargeRej Indices: None
	    WmeanRej Indices: None
	Manual reject indices: 1 
```
The element [6] externalFlag ( 1 = externalErrors, 0 = none) reflects that the logic proceeded correctly per Ludwig.  

The issue may be that in **both** cases, the summary stats shown in your attached images determine the displayed **1%sigma error of mean** by dividing element [2] by element [1] and multiplying by 100; and determine the displayed **1 sigma external spot-to-spot error** by dividing element [1] by element [0] and multiplying by 100; 

Hopefully this is the root of this issue - a misunderstanding about how to calculate / represent these two derivative values.

You are right that I ported this code as well as many other Ludwig routines to Java without additional documentation.  However, the test suites supplied with the Java ports use Squid2.5 data and results and I am confident that the numbers shown above in the peek are correct as these weighted means have been rigorously reviewed.

For reference, Ludwig's WeightedAverage is [here](https://github.com/CIRDLES/LudwigLibrary/blob/master/vbaCode/isoplot3Basic/Means.bas) starting at line 451 and the Java port of this code is [here](https://github.com/CIRDLES/LudwigLibrary/blob/master/src/main/java/org/cirdles/ludwig/isoplot3/Means.java) starting at line 42.

The Squid3 implementation of WtdMeanACalc, which uses WeightedAverage, is [here](https://github.com/CIRDLES/Squid/blob/v1.6.5/squidCore/src/main/java/org/cirdles/squid/tasks/expressions/functions/WtdMeanACalc.java).

**Comment by NicoleRayner** [comment]
Good catch @cross-a .

This made me think, that as well as the outputs of the wt mean calculation we should also include the minimum external 1sigma % err as specified under Parameters

**Comment by bowring** [comment]
Would someone please describe what is needed exactly in each case?  Thanks.

**Comment by NicoleRayner** [comment]
I have to defer the math stuff to @sbodorkos.  But it seems to me that for the RM weighted mean calculation and its 95% error is calculated differently than the usual WtdMean:  This text is taken from the "?" of 2nd Wtd mean box in the screen snap below.
 "The scatter of the data points is assumed to arise from a combination of the assigned data-point errors plus some unknown but constant 'External' error.  The magnitude of the most-probable 'External' error is solved along with the weighted average, and the 95%-confidence error on the weighted mean involves Students-t for **2N-2 degrees** of freedom."  
![image](https://user-images.githubusercontent.com/40035242/103820534-897e1980-503a-11eb-97ea-7a40cf0ea474.png)

**Comment by NicoleRayner** [comment]
The additional output that I am requesting on the RM Weighted mean diagram is an additional item to the array named " 1sigma external spot-to-spot error (%) USED" where the value is the one assigned as a default in the Project Manager/Parameters window

![image](https://user-images.githubusercontent.com/40035242/103821761-d9f67680-503c-11eb-92b0-2a5cd31ebbf7.png)

**Comment by sbodorkos** [comment]
OK, there are a few different things here. I agree with @NicoleRayner regarding her most recent Sq3 screenshot, and have some additional suggestions for improving the display of WtdMeanAcalc output in the Interpretations-RM-WeightedMeans window, but I will create a separate issue for those display-related considerations, later.

Regarding the RM weighted mean calculations, I don't believe there is an arithmetical issue, because when things do work, they work perfectly. But something is going wrong, because the uncertainties on 206/238 flowing through to the unknowns are sometimes incorrect, so I think there might be a logical/procedural issue (or maybe more than one).

Jim @bowring , one thing to urgently address is the captioning in the 'peek' is to change "err68" to "exterr68" and "err95" to "exterr95" - I did not know what those values represented until you explained it in your comment on this issue.

In a nutshell, the issue is that when ExternalFlag = 0, then exterr68 = exterr95 = 0.

The catch is that ExternalFlag is not entirely user-defined. If the user sets ExternalFlag = 0, then it stays 0 (this is the mode in which WeightedAverage functions for unknowns everywhere). But even if the user sets ExternalFlag = 1 (as WtdMeanAcalc always does, when it invokes WeightedAverage), it is still necessary to perform an initial WeightedAverage calculation on the dataset to generate an initial Probability of fit. Because if that Probability of fit exceeds 0.05 straight off, then the routine itself needs to switch ExternalFlag to 0, and set exterr68 = exterr95 = 0. 

This is because the calculation of exterr values is predicated on the existence of dispersion in the dataset. If that dispersion does not actually exist, then it doesn't matter if the user has asked for an exterr value — they can't have one.

So that's what I think the issue is, with respect to the second peek. ExternalFlag is **correctly** evaluated as 0, which means err68 and err95 should be 0 as well. So I am interested in why those calculations appear to proceed regardless.

I am now going to try to pick through the Isoplot VBA code, to try and isolate exactly where the WeightedAverage routine gives itself permission to override the user-specified input for the Isoplot equivalent of ExternalFlag.

**Comment by bowring** [comment]
@sbodorkos - I think you will find that all proceeds as it should relative to the ExternalFlag.  The issue is more simply that Java WeightedAverage (line 249+) is reporting the wrong numbers due to a misunderstanding of the inscrutable Ludwig code:
```java
            // determine whether to return internal or external
            if (extMean != 0.0) {
                retVal = new double[][]{{
                    extMean,
                    extSigma,
                    extMeanErr68,
                    extMeanErr95,
                    MSWD,
                    probability,
                    1.0
                },
                // contains zeroes for each reject
                values
                };
            } else {
                retVal = new double[][]{{
                    intMean,
                    intSigmaMean,
                    intErr68,
                    intMeanErr95,
                    MSWD,
                    probability,
                    0.0
                },
                // contains zeroes for each reject
                values
                };
            }
```
Simply changing the contents of the returned array in the else clause (for ExternalFlag == 0) easily solves the problem:
```java

            // determine whether to return internal or external
            if (extMean != 0.0) {
                retVal = new double[][]{{
                    extMean,
                    extSigma,
                    extMeanErr68,
                    extMeanErr95,
                    MSWD,
                    probability,
                    1.0
                },
                // contains zeroes for each reject
                values
                };
            } else {
                retVal = new double[][]{{
                    intMean,
                    intSigmaMean,
                    0.0,
                    0.0,
                    MSWD,
                    probability,
                    0.0
                },
                // contains zeroes for each reject
                values
                };
            }
```

**Comment by sbodorkos** [comment]
Jim @bowring you are correct that care is needed, and that the simple zero-substitution I canvassed is **not** the way forward. I had forgotten the intricacies of WeightedAverage depending on whether ExternalFlag = 0 or 1. I am unwilling to plunge into the inner workings of WtdAv until I have no other option, so for the moment, I am willing to stipulate that your retVal implementations are correct.

Possibly the issue is that the "summary" set of values (as displayed on the Interpretations-RM-WeightedAverage screen **and** as used in subsequent calculations applied to the unknowns), is not always a direct copy of the relevant set of retVals. Essentially, that summary **should** be:

"Wtd Mean of..." = (If ExternalFlag = 0 Then intMean Else extMean)
"1%sigma of mean" = (If ExternalFlag = 0 Then intSigmaMean Else extSigmaMean)
"1sigma external spot-to-spot error" = (If ExternalFlag = 0 then 0 else extMeanErr68) **never** intMeanErr68!
"MSWD" = MSWD
"Prob. of fit" = probability

And then, after that process is completed, "1sigma external spot-to-spot error" should be compared with "Minimum external 1sigma %err for...", as per @NicoleRayner Squid3 screenshot, and the **largest** value used for the purpose of quadratic addition to measured 206Pb/238U %err in each spot-analysis of the unknowns.

So in my original example, with TEM-1.1 included, the low probability should retain an ExternalFlag value of 1 (and Squid3 does do this correctly). The corresponding extErr68 value is 1.03%, and this is the "1sigma external spot-to-spot error" that should be propagated to the unknowns, because it exceeds the "Minimum external 1sigma %err for..." specified by @cross-a (0.75%). That is indeed occurring correctly in Squid3. 

But when TEM-1.1 is excluded, re-evaluating the weighted mean yields probability > 0.05, which should set ExternalFlag to 0 (and Squid3 seems to do this OK). On that basis, the summary value of "1sigma external spot-to-spot error" should be 0, and from there, the comparison with "Minimum external 1sigma %err for..." should result in the latter value as specified by @cross-a (0.75%) being propagated to the unknowns. Squid3 is **not** doing this correctly in this example; it is propagating some larger value. I am not sure exactly what the propagated value is, but I am wondering if intMeanErr68 has been caught up in the calculation somehow.

**Comment by bowring** [comment]
After a detailed discussion with @sbodorkos , the source of the problem has been traced to two bugs in the logic handling the external errors of the calibration constant weighted means.

The expressions containing the fault can be viewed in the expression manager.  For example:
```rtf
4cor_206Pb238U_Ext1SigmaErr_Pct =
     Max(Min_206Pb238U_Ext1SigmaErr_Pct,
         WtdAv_4cor_206Pb238U_CalibConst[1] / WtdAv_4cor_206Pb238U_CalibConst[0] * 100)
```
contains two bugs - the first masking most instances of the second:
1. the case of external errors == 0, where the parameter Min_206Pb238U_Ext1SigmaErr_Pct should rule
2. The use of the indexed (see peek above) [1] value for 1 sigma instead of the [2] value for exterr68 in the division

The correct formulation is: (note construct for 'IF a, then b else c' is 'IF(a, b, c)'
```rtf
IF(WtdAv_4cor_206Pb238U_CalibConst[6] == 0,
   Min_206Pb238U_Ext1SigmaErr_Pct,
   Max(Min_206Pb238U_Ext1SigmaErr_Pct,
       WtdAv_4cor_206Pb238U_CalibConst[2] / WtdAv_4cor_206Pb238U_CalibConst[0] * 100))
```
The other expressions containing variations of these bugs are: 
```rtf
7cor_206Pb238U_Ext1SigmaErr_Pct
8cor_206Pb238U_Ext1SigmaErr_Pct

and, for 208Pb/232Th:
4cor_208Pb232Th_Ext1SigmaErr_Pct
7cor_208Pb232Th_Ext1SigmaErr_Pct
```

The next release will contain this fix as well as an improved display of the RM WM stats per @NicoleRayner (see above) that shows both the Min_206Pb238U_Ext1SigmaErr_Pct and calculated 1sigma external spot-to-spot error (%) and which is being used.

Happy New Year!

**Comment by sbodorkos** [comment]
Jim @bowring I think the second bug is not actually a bug. I am not certain, because even after all these hours, I *still* cannot reconcile the output of your WeightedAverage with the parameters Ludwig presents on the SQUID 2.50 StandardData sheet, as the springboard for processing Unknowns there. That is hampering us getting to the bottom of this.

But the key thing to remember is that in the original example, with **all** TEM points included — where Squid3 calculated the 1sigma external-spot-to-spot at 1.03% **prior** to Friday's discussion — everything was working completely correctly. At that point, you were using array element [1] in the calculation, so that **must** be the correct element to use, even if neither of us understands why...

All I can think is that the first bug is the only bug. Now that the IF logic is perfect, and intSigmaMean is totally occluded from the calculation, maybe that solves the whole problem. So let's retain fix 1, and unwind fix 2 so that the expression uses array-element [1] instead of [2].

**Comment by bowring** [comment]
Simon @sbodorkos - I will revert to use of [1] from [2] and switch the displayed values as well to align.  I think the answer may lie in taking Ludwig at his word when he names his variables and uses "extSigma" in slot [1] when there is external error.  The variable names I show in the discussion of retVal above are directly from his VBA code.

**Comment by bowring** [comment]
Simon @sbodorkos - after these changes, the net result is only that the display is corrected - for the supplied file, the downstream weighted means of the unknowns remain the same as Squid3 was using 0.75 even with the incomplete logic since 0.75 % > 0.206213 %.  This can be confirmed by examining expressions such as 4cor_Total_206Pb238U.

**Comment by sbodorkos** [comment]
Jim @bowring , it turns out the issue is completely separate and (I suspect) unrelated to the weekend discussion. I did not look carefully enough at the Squid3 Project file @cross-a supplied. I will make a separate issue.

Feel free to close this one; I guess if the discussion above repaired the IF logic, then it wasn't a complete waste of time :) .

**Comment by bowring** [comment]
It is always good to review things!
