### ISSUE TITLE
Custom Report builder not accessible

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#553]
Testing v1.6.6 when I select menu item Reports - Custom Report builder I am sent back to the blue home screen.  Squid hasn't crashed (I can continue to work in the other windows) and in fact if I select Reports - Generate All Reports it does that just fine.  I just can't get to the Builder.
ETA: it is independent of the squid project file.  Happens with the Demo project file as well as the random one I first encountered this problem with.

**Comment by bowring** [comment]
looks like that is a problem too .... standby

**Comment by bowring** [comment]
found the issue ... fix on the way
