### ISSUE TITLE
Hard to read numbers - Manage Displayed Masses screen

### ISSUE THREAD

**Issue by Slj996** [CIRDLES/Squid#555]
Squid3 Version: 1.6.5
Java Version: 1.8.0_271
OS: Windows 10 10.0

Issue details:
Low priority!

Steps: Data - Audit Raw Data
When you click on the individual spot analysis in the time axes - the numbers are hard to read. See attached screenshot. Suggested solutions might be: bold the number - as you only need to click away to see the graph underneath OR I wonder if changing the font to a different colour might work?
![Sqid3 Manage Displayed Masses](https://user-images.githubusercontent.com/29034224/104863651-b6abbf80-598a-11eb-98d3-1fd92e2ba0c8.PNG)

**Comment by NicoleRayner** [comment]
Great idea.  I find the same.

**Comment by bowring** [comment]
How is this?  larger and blue, not bold

![blue](https://user-images.githubusercontent.com/1092963/105536289-18876480-5cbe-11eb-87cc-9d1ec5f5f8ce.png)

**Comment by Slj996** [comment]
Yes the blue text is much easier to read. 

Thanks for resolving this so quickly!
