### ISSUE TITLE
_WM_sample expressions.  Flagging as "unhealthy" instead of "unknowns"?

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#564]
At the GSC we regularly analyse a sample (1242) as a monitor of our 7/6 ratio/age to determine if we need a intra element mass fractionation correction.  Other labs use OG1 for this same purpose.   I created/used the _WM_1242 expression to determine a mass fractionation factor, and included that expression in my custom task.  If I use that same custom task for a different xml file, the target flag for that WM goes to "unknowns", rather than stick as 1242.  
![image](https://user-images.githubusercontent.com/40035242/105735213-6f30b080-5f01-11eb-9e19-d67a43beef24.png)

I know that there is no way for this flag to be preserved as 1242, because there is no guarantee that a given xml file will contain sample 1242.  Currently I need to remember to go change the flag on that expression everytime I use the task that contains it, which is doable but prone to human error. However I was wondering if it would be possible for these specific types of expressions, generated from within Squid3 (rather than manually built),  and identifiable by "_WM_samplename" in their expression name could be flagged as "unhealthy" when first used to force the user to investigate those and make any edits required (in this case changing the flag from unknown to 1242).

I'm not sure if this is the best workaround to this situation - others may have other suggestions.

**Comment by bowring** [comment]
The fix (next version): On loading the task, the "WM" expression is pointed to the Sample (by name) specified in its name and if the Sample with that name is present, the expression works out of the box.  Otherwise, "WM" expression appears as Unhealthy and user can edit the target to bring it into compliance or delete it.  Great idea @NicoleRayner !
