### ISSUE TITLE
renaming report category - doesn't stick/allow save

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#565]
I renamed a category in my custom report template.  Seems to take it fine.  Save is not an option in the report template manager menus (greyed out).  If I switch to another report (e.g. the RM reports) then switch back, the old category name is there.

Of course I try it again and it does ask me to save.  Just prior, I had tried editing the content of category to check that save was triggered.  It was.  Then I tried the rename again and THIS time it asked me to save.  Maybe this happens when rename is the FIRST thing you try and do.  Standby for further testing.

Just confirmed that if the FIRST and ONLY thing you do is rename the category, you don't get the option to save and it doesn't take. Other/subsequent actions (like adding a column to a category trigger save, which will also include your category name change)

**Comment by bowring** [comment]
Fixed in next release.  Also fixed issue where lab default report could not be edited while being default.
