### ISSUE TITLE
Need to read Nscans for each spot (to process XML files containing spots with different Nscans values)

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#567]
From Mark Fanning (PRISE/ANU), to @sbodorkos via email:

> [I have installed Java 1.8 and] the SQUID.JAR now works OK. I have been working through @NicoleRayner’s videos - great work on all counts.
> 
> One immediate snag is that one cannot process files with differing numbers of scans. To me, and no doubt others, this is a major issue!!  Often when one is running complex zircon samples, one uses the 6 scan format to determine the crystallisation age and for most of the older/inherited components. However, also very often, as one may not be in a geological survey setting, machine time is of the essence - and importantly cost. So one may reduce the number of scans to gain a better idea of these older/inherited components in 4 or 5 scan mode. In such cases, more often than not, one has files with mixed numbers of scans. To have to process these as separate “projects” would be a real pain.
> 
> Another common situation with mixed numbers of  scans is when one has an heterogeneous population of zircons, say an ignimbrite or a young volcaniclastic rock where all the zircons are euhedral igneous grains. When one is trying to find the youngest magmatic age grouping, one may start an analysis as a 6 scan set, but as the numbers roll off the machine one can see that the grain is part of an older igneous component. In such cases, one often cuts the numbers of scans short, but still keep that data as one has rastered etc. Of course that older info is important, but cannot be processed together with the other 6 scan data.

I echo this – I suspect we probably took a couple of shortcuts when originally reading in our demo XML files to get started on emulating the data-processing, but we definitely need to be able to cater for varying numbers of scans on a spot-by-spot basis. I realise that there will be associated work, related to the Audit Data graphics and things like that, but this is an important one.

As part of this same exercise, I'd like to add in the analogous check on the source(s) of the values of **sbm_zero** and **deadtime_ns**. I know that most of our demo Prawn XML files present these values as session-invariant constants, but the SHRIMP control software allows both values to (in theory) be re-specified from one spot to the next, so the spot-specific value needs to be read from the Prawn XML every time.

If it would help, I think @cross-a has a Prawn XML file with varied sbm_zero values in it, and we could use that to test the code.

**Comment by NicoleRayner** [comment]
I have successfully processed data with variable numbers of scans - so it is permitted, I just don't have a sense of what impact that has on the actual data reduction.  At one point @bowring told me that there was some difference, I just don't remember what but I did mention that in one of my videos as something to beware of. The demo file that comes loaded with squid3 actually has mixed scans (6 and 8).  Audit data seems to respond properly (the analyses with 8 scans are at the end of the session, you can see the spacing between analyses changes accordingly).

![image](https://user-images.githubusercontent.com/40035242/105997439-9e6a2d80-6079-11eb-973e-4705ef50b7dd.png)

**Comment by sbodorkos** [comment]
Yes, I have asked for a copy of the offending Prawn XML file, because I'd better rule out the possibility that its problem is something unrelated to Nscans!

**Comment by cwmagee** [comment]
I think session 90038 has multiple scans- comparison paper data is "90038 6 scan only" which I think is trimmed.
