### ISSUE TITLE
Assessing different definitions of Discordance - what is "best" for Squid3?

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#569]
From Kei Sato (Institute of Geosciences, University of Sao Paulo), to @sbodorkos by email:

_**Please note** that this discussion is accompanied by two attachments, both prepared by Kei Sato. Comment2.PDF is the original version of the below post, and Book2.XLS implements the calculations described herein._

**[COMMENT2.pdf](https://github.com/CIRDLES/Squid/files/5880903/COMMENT2.pdf)**
**[Book2.xlsx](https://github.com/CIRDLES/Squid/files/5880917/Book2.xlsx)**

**COMMENT - DISCORDANT VALUE CALCULATION**
The mathematical formula for Discordance value calculation between 207Pb/206Pb and 206Pb/238U ages are very different between the SQUID 1.7 and SQUID 2.5 or SQUID 3-1.6.6 software. Squid 1.7 calculates the discordant values between ages 207/206 (equation A - see below) whereas in squid 2.5 or squid 3-1.6.6 uses 206Pb / 238U ratio by 206Pb/238U and 207Pb/206Pb ages but with the same λ238 (see equation B below)

![image](https://user-images.githubusercontent.com/17473203/106002276-0b76d500-6105-11eb-8038-571bae890e67.png)

Equation B has a problem mainly when T207/206 approaches zero or negative ages. Negative ages do not exist but common Pb correction problems may occur producing future ages mainly in young zircons. Table 1a,1b and 1c (below) show data extracted from Demo-SQUID3-1.6.6 for unknown sample DDDD. The 206Pb/238U ages are around 28.6 Ma but the 207Pb/206Pb ages are mostly negative (table 1c). This is due low intensity of 207Pb radiogenic and high common 207Pb correction. The problem is in the Discordance values, which are **positive** for **negative** 207Pb/206Pb ages. _This in my view is wrong, but I would like to hear your opinion._ The mathematical formulation used in squid 1.7, the Disc (%) are more consistent when compared to squid 2.5 (table 2A)

![image](https://user-images.githubusercontent.com/17473203/106002803-a7a0dc00-6105-11eb-84a5-3f6dceca379e.png)
**Figure/table 1:** _Data extracted from SQUID 3-1.6.6 DEMO. (A) 204cor-207Pb/206Pb; (B) 204cor-206Pb/238U age; (C) ages and disc(%) data from demo-squid3-1.6.6 report table; (D) Wetherill plot - DDDD unknown sample._

Table 2A shows Disc (%) calculations in squid 1.7 and squid 2.5 / squid3-1.6.6 software. The 206Pb/238U ratio = 0.0935 was fixed at 576 Ma and we calculated the 206Pb / 238U = e λT -1 (ratio) for the hypothetical T207/206. It is observed that the discordance values between squid 1.7 and 2.5 are similar for 206/238 and 207/206 close ages, however when T207/206 approaches zero the discordant value in squid 2.5 go to infinity (Table 2A). This is due 206/238 ratio tends to go to zero and T207/206 approaches zero and therefore the discordant (%) go to infinite value (Figure 2B) according to the mathematical formulation used in squid 2.5/3.0.

Figure 2B shows that If 207Pb/206Pb age go to near +0 (positive) then discordance value go to infinite (negative number). On the other hand, if 207/206 age go to near -0 (negative age) discordant value go to infinite (positive) number. For 207/206 negative ages the discordant values are always positive in the squid 2.5 or squid 3-1.6.6 software (Tables 1C and 2A - see equation below). From equation (B):

Disc(%) ={ 1 - [206/238] / [ eλT-1] } * 100

If T < 0 then eλT <1.0, therefore we have eλT-1 = negative value, and so **for T < 0**:

Disc(%) ={ 1 - [206/238] / [negative value] } * 100 = always positive value (see table 2A)

![image](https://user-images.githubusercontent.com/17473203/106003338-3877b780-6106-11eb-8b05-6167dd83e643.png)
**Table 2A:** _206Pb/238U ratio calculated by eλ238T-1 where ratio 1 = 576Ma (constant) and ratio 2 is calculated by hypothetical 207Pb/206Pb age._

![image](https://user-images.githubusercontent.com/17473203/106003568-6e1ca080-6106-11eb-8665-8f2fa19fdeab.png)
**Figure 2:** _(B) Discordant (%) versus 207Pb/206Pb age for SQUID2.5 - asymptote occurs at T=0. We have 2 close Disc(%) values around +100% for T= -4500 and +4500Ma. (C) Disc (%) versus 207Pb/206Pb age for SQUID1.7: R^2 is exactly = 1._

Figure 3B shows Disc (%) calculated by SQUID 1.7 as a function of T207/206 with super well aligned points (R^2 = 1).

![image](https://user-images.githubusercontent.com/17473203/106004181-0fa3f200-6107-11eb-94bc-fe58e7548f91.png)
**Table 3A:** _Data extracted from DEMO-SQUID3-1.6.6 - 206Pb/238U for unknown sample DDDD (spots 3.1, 7.1, 16.1 and 20.1). Squid 1.7 column were calculated by equation A._

![image](https://user-images.githubusercontent.com/17473203/106004661-8b05a380-6107-11eb-91d2-414b423f4042.png)
**Figure 3B:** _Disc(%) versus 207Pb/206Pb age. Diagram shows points well aligned with R^2 = 1.000._

**Comment by sbodorkos** [comment]
My response _(which addressed an earlier version of the above PDF and XLSX, so some of my discussion has already been addressed above):_

I have reviewed your documents, and I think I agree with you. I have noticed parts of this issue previously, but I have never documented it in detail. I had noticed the sign reversal on the SQUID 2.5-3 Discordance value (and its opposite relationship to the sign on young/future 207/206 dates), but I had not previously understood the asymptotic behaviour of SQUID 2.5-3 Discordance as 207/206 age approaches zero (and now that I do know about it, I do not like it!).

The fundamental problem with Discordance is that there is no absolute definition. Until now, the various equations in use have not been considered 'better' or 'worse' than each other, just different. For example, I add to your discussion a third equation for Discordance, which is based on the 'classical' definition of Concordance, as used in 'twentieth century' U-Pb geochronology, prior to the development of Squid 1.

Conventionally, Concordance is defined as = 100 * [206/238 date] / [207/206 date], so 'pre-Squid' Discordance can be considered as = 100 * [ 1 – ( [206/238 date] / [207/206 date] ) ], such that Concordance + Discordance = 100.

I have added  this pre-Squid definition of Discordance to your XLSX as a third option, and as you can see, the expression currently in use in Squid 2.5-3 reflects it very closely. It is clear that the pre-Squid expression has the same problems as the Squid 2.5-3 expression: spurious sign reversal for [207/206 date] < 0, and asymptotic behaviour at [207/206 date] ~ 0.

In my opinion, with respect to 'improving' the calculation of Discordance values, there are two ways forward:

**Make the calculation of Discordance conditional, by requiring [207/206 date] > 0, else Discordance = NULL.** Some people might favour this solution because it only excises [207/206 date] values that are geologically insignificant anyway… but I personally do not like it.

1. Ken Ludwig built Squid arithmetic to be as agnostic as possible with respect to the input values. There are very few conditional calculations anywhere in previous versions of Squid, and I do not believe we should be introducing them now. 
2. Now that I have seen it properly, I do not like the asymptotic behaviour of Squid 2.5-3 Discordance, even if it was confined to [207/206 date] = 0+. 
3. I think it is relatively common practice for geochronologists to Sort their data by Discordance, and I do not like the idea of unpredictable Sorting behaviour for analyses which have NULL Discordance.

**Adopt the Squid 1 expression (or one very closely related to it) as the 'best' way of calculating Discordance.** I think I like this idea better.

1. Expressions with [206/238 date] in the denominator seem superior, because they are not vulnerable to spurious positive Discordance values: negative values in the numerator are almost impossible to match in the denominator, in contrast to expressions with [207/206 date] in the denominator.
2. An obvious advantage is the continuous nature of the function, which means the calculation can always be performed reliably, as long as the input values are numeric. (This is how Squid expressions traditionally work, and I think it is a strength of Ludwig’s approach.) 
3. Sorting of the data by Discordance will yield predictable results, and coherent age-sorting behaviour (albeit with respect to [206/238 date] rather than [207/206 date]). 
4. In my subjective opinion, the Squid 1 expression is 'more sensitive' to normal discordance (and therefore 'better') in the geologically important range. For example, using your XLSX, analyses that are 18% discordant in Squid 2.5-3 are 21% discordant in Squid 1. The fact that discordant analyses are 'judged more harshly' by the Squid 1 expressions suggests to me that the Squid 1 expression is superior. It is true that the Squid 1 expression is correspondingly 'less sensitive' to reverse discordance, but I do not consider this a major problem, because most of the sources of reverse discordance are only weakly related to the geological history of the zircons.

**[All other opinions welcome!]**

**Comment by NicoleRayner** [comment]
Thanks @sbodorkos and Kei Sato - this is all really eye-opening, especially for someone who works mainly in the Archean/Paleoproterozoic so ages close to 0 don't fall on my radar much.  I think a nice thing about squid3 is we don't need to reach a consensus or have a geochronology overlord be responsible for implementing new approaches.  If we've given this (or any other topic) some thought and we want to implement it, it is as simple as writing an expression (and then also decide if that is what we want to use in our reports instead of the "onboard" disc (%)).  Here I have created and exported the squid1 discordance expression and an xml in case anyone wishes to download, unzip and import into your own version of squid3 if you wish.  

[Disc (%) squid1.zip](https://github.com/CIRDLES/Squid/files/5883252/Disc.squid1.zip)

**Use of this expression is by no means required, or even encouraged** - just a contribution to the discussion and the community  I hope we can build here.

**Comment by cwmagee** [comment]
This is more of a comment than a solution, but...

When I was putting data together for the supplementary material of my geology paper (Geology 44 527)  a few years back, I was comparing laser-ICPMS and SHRIMP data, and I discovered that there are EVEN MORE ways to calculate discordance over in that community. I think I ended up finding a total of 4 different definitions, but I can't find the source files for figures DR 12 and 13 here at work (I finished and submitted the paper in between finishing at ASI and starting at GA, so I don't have all the files at GA). However, I did find some preliminary files which show 100*(6-38age/7-35age). 

It looks like any discussion of this was cut from the final published supplement (We had to make a lot of cuts). I'll check my files at home this weekend. But I think that people need to be very careful when comparing numerical "discordance" values from different data reduction packages, as they can be completely different calculations. This is particularly important if anyone is aggregating numerical data from different platforms and data reduction software packages.

**Comment by cwmagee** [comment]
Further comment- the formula in the comment above was concordance, not discordance (sorry).

**Comment by sbodorkos** [comment]
Yes, these are good points. I had never even considered writing my own Discordance expression in a Task, so thankyou @NicoleRayner ! One thing I am mindful of is that Squid 1 and SQUID 2.50 essentially unified the global U-Pb SHRIMP community in terms of data-processing and 'built-in' expressions, right out of the box. I think we as a community take that for granted to an extent, but when you looks at the diversity of data-processing approaches in the U-Pb LA-ICPMS community (and the need to explicitly consider that as a source of discrepancy when comparing results between labs), I think we have been fortunate. 

Possibly we should still seek to optimise the 'built-in' arithmetic and logic, in recognition of the likelihood that most users will remain reluctant to engage with the Expression Manager (notwithstanding its user-friendliness relative to SQUID 2.50).

It has gotten me to thinking about what a Discordance (D) calculation 'should' achieve. Obviously D should be 0 on the Concordia curve, but presumably D should be uniformly > 0 on the 'Pb loss' side of the curve, and uniformly D < 0 on the other side? Of all the expressions I have seen (including Chuck's), only the Squid 1 expression actually delivers that. I also like that it 'handles' zero and negative [207/206 date] values in an intuitive way, and that the function is continuous in 207/206 (much more important than continuity in 206/238, because zero and negative values are far harder to come by in the latter).

Would adopting the Squid 1 expression be an enhancement of Squid3's 'built-in' arithmetic/logic? Or is it over-reach, and we should stick to SQUID 2.50 as we have tried to do everywhere else?

**Comment by cwmagee** [comment]
I think that we should stick with 2.5 until we make a compelling and transparent case to change.

As for being a source of discrepancy, I learned all this plotting SHRIMP and laser data from the same detrital grains together, and I puzzled over why laser ellipses farther from concordia had smaller numerical discordance. Graph of data below:
![1612254263002_shrimplascomp](https://user-images.githubusercontent.com/11417991/106572247-4e64fc80-658c-11eb-8a67-2cfd26f2244e.png)

**Comment by cwmagee** [comment]
Does Nat read this? We should probably warn Barry.

**Comment by sbodorkos** [comment]
Discordance is the least of their problems, given that they have just published a Record-ful of Tera-Wasserburg diagrams that look like this:

![image](https://user-images.githubusercontent.com/17473203/106590641-6eeb8180-65a1-11eb-8f9c-6913ac14f95c.png)

One valuable function of a future Topsoil would be to check that Tera-Wasserburg input has error-correlation values near zero. I can only assume that this diagram has used the Wetherill rho-values in conjunction with the Tera-Wasserburg ratios and uncertainties, and I am starting to wonder how we stop people doing this. Off-topic with respect to discordance though.

**Comment by ryanickert** [comment]
At the risk of appearing as if I have some interest in this, I'll leave this here:

https://gchron.copernicus.org/preprints/gchron-2020-38/

**Comment by cwmagee** [comment]
I think the Vermeesch paper is a further argument for:
1. Stating clearly what the default definition is.
2. Allowing user-generated changes (as per Nicole).
3. Changing the default only through broad and transparent consensus.

**Comment by NicoleRayner** [comment]
This issue can be closed.  See earlier reply pasted below for an custom expression that calculates discordance as per squid1 if you wish to import and use in your laboratory. 
> Thanks @sbodorkos and Kei Sato - this is all really eye-opening, especially for someone who works mainly in the Archean/Paleoproterozoic so ages close to 0 don't fall on my radar much. I think a nice thing about squid3 is we don't need to reach a consensus or have a geochronology overlord be responsible for implementing new approaches. If we've given this (or any other topic) some thought and we want to implement it, it is as simple as writing an expression (and then also decide if that is what we want to use in our reports instead of the "onboard" disc (%)). Here I have created and exported the squid1 discordance expression and an xml in case anyone wishes to download, unzip and import into your own version of squid3 if you wish.
> 
> [Disc (%) squid1.zip](https://github.com/CIRDLES/Squid/files/5883252/Disc.squid1.zip)
> 
> **Use of this expression is by no means required, or even encouraged** - just a contribution to the discussion and the community I hope we can build here.
