### ISSUE TITLE
Software name: Squid or Squid3?

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#570]
From John Aleinikoff (USGS) via email:

> On the title page, the program title below the 4-armed Squid icon is shown as "Squid".  Shouldn't this really be "Squid3"?

I believe Jim @bowring has already enacted this, so feel free to close this whenever, if there is nothing more to say.

For what it's worth, I think it is clear that the name "Squid3" is going to stick. Adopting it would also be consistent with the naming of the .jar files. 

And it might also protect us against unimagined success in the proliferation of the software: we might be less likely to come to the legal attention of some commercial enterprise that has already trademarked the name "Squid" for their own software (remembering that this happened to Ken Ludwig and the Berkeley Geochronology Center, courtesy of the organisation which had registered the name Isoplot). "Squid3" is more likely to be unique.

**Comment by bowring** [comment]
Updated to Suid3 with version and build date - next release.
