### ISSUE TITLE
XML opened in Squid3 and saved as XML does not open in Squid2.5

### ISSUE THREAD

**Issue by cwmagee** [CIRDLES/Squid#580]
Following on from the previous iteration of this issue, backwards xml compatibility still doesn't work (using the version of Squid 2.5 currently installed on the GA SHRIMP LIMS computer).
File "100157_GA6148NKunopened"  opened fine in both Squid 3 and Squid 2.5
File "100157_GA6148NKunopened-Squid3172"  was saved as xml from Squid3 1.72, and does not open in Squid 2.5
[source and save file.zip](https://github.com/CIRDLES/Squid/files/5916007/source.and.save.file.zip)

Before and after xml files uploaded below:

**Comment by sbodorkos** [comment]
Do you recall what (if any) the SQUID 2.50 error message was? I'll investigate over the next couple of days.

**Comment by cwmagee** [comment]
Attached
![errormsg](https://user-images.githubusercontent.com/11417991/106697648-4ca24400-6633-11eb-9a86-737566361cb6.png)

**Comment by sbodorkos** [comment]
I eyeballed the Squid3-generated XML in Notepad++, and didn't spot anything obvious... but that was because it was too obvious! SQUID 2.50 was telling me the file contained only 1 line, and still the penny didn't drop...

Here is a screenshot of the first part of Squid3-1.7.2-generated Prawn XML output from Chuck's ZIP, opened in Notepad++:

![image](https://user-images.githubusercontent.com/17473203/106711265-5d5eb400-664b-11eb-84e9-eba467d45f38.png)

The issue is the paired carriage-return [CR] and line-feed [LF] at the end of each line - those need to be line-feed **only**. Jim @bowring, could you please address this one in the next release?

**Comment by bowring** [comment]
Squid3 only generates the end-of-line character "\n" or LF, which is the Unix standard.  Windows uses "\r\n" or CRLF.  The likely source of the CRLF in this case is that @cwmagee opened and saved the XML file on a Windows machine and got the Windows flavor before giving it to Squid25.  Please confirm.

**Comment by cwmagee** [comment]
It was saved from squid3 as xml, copied to a stick, taken downstairs, and opened directly from the stick drive on the lins computer.

**Comment by cwmagee** [comment]
The computer running squid3 is Win10, the LIMS computer is Win7.

**Comment by bowring** [comment]
Copying it must have changed it as I just ran Squid3 on a Win10 machine and checked the output in XML and it only has "\n" or LF as required.  Do the same on your file before it is ever moved or saved by another application.

**Comment by bowring** [comment]
Now I have a confusing scenario - I tried another win10 machine and got an opposite result, namely CRLF.  So I am going to experiment and see if I can force it.  Otherwise, it will be a user-be-warned scenario where you need to go into the file and convert it to use with Squid25.  Stand by.

**Comment by cwmagee** [comment]
Squid 2.5 won't run in win10, so it has to be copied somewhere. I can try ssving directly to the stick...

**Comment by cwmagee** [comment]
Saving to and opening from the stick without resaving the file does not resolve the issue. File attached (although it will obviously have been copied to get here)
[Bug580.zip](https://github.com/CIRDLES/Squid/files/5922345/Bug580.zip)

**Comment by cwmagee** [comment]
Works on our end now.
