### ISSUE TITLE
Squid Serializer Fix

### ISSUE THREAD

**Issue by RichardMcCarty1** [CIRDLES/Squid#587]
The squid serializer error from squidAPI is resolved with the inclusion of a secondary mkdir for the SQUID_USERS_DATA_FOLDER_NAME folder in the event storeState is referenced prior to SquidPersistentState.

See [my branch](https://github.com/RichardMcCarty1/Squid/blob/d03f929924c6fad17cb4de3ce9aa5cfd270c9c9d/squidCore/src/main/java/org/cirdles/squid/utilities/stateUtilities/SquidLabData.java#L109) for the content of the change, I can also throw up a pull request with the change if we determine it will not negatively affect anything.

**Comment by bowring** [comment]
waiting further insights - this issue relates to squidInk on the server.

**Comment by bowring** [comment]
all is well.
