### ISSUE TITLE
204/206 and 208/206 Ratio uncertainty value not exported to csv

### ISSUE THREAD

**Issue by auscopegeochemistry** [CIRDLES/Squid#589]
Hi there, 
When I export ratios of 204/206 and 208/206 the uncertainty values that are visible in the peek window do not show up in the csv file. Any particular reason?
Best,
Alex

I can write a custom expression in the form:
ValueModel([204/206],[%"204/206"],false)
which does export uncertainty values in the csv.

**Comment by bowring** [comment]
@auscopegeochemistry - Good catch!  The ratio uncertainties disappeared due to a bug introduced recently while attending to another issue related to reporting uncertainties and was undetected until now.  Note that an alternative equivalent expression is: ValueModel(["204/206"], [±"204/206"], true). In drag'n drop mode in the Expression editor, a right mouse click on an expression of the form ["...."] will allow you to specify value, abs uncertainty, or percent uncertainty.

Fix is in next release (very soon).

May we add your name to the list of contributors in the About page?

**Comment by bowring** [comment]
A further note on uncertainties:  you can always access the uncertainty of an expression that has an uncertainty calculated by referring to the underlying 0-based index array, as follows:
```java
["204/206"] refers to the value of the expression
["204/206"][0] also refers to the value
["204/206"][1] refers to the absolute 1-sigma uncertainty
```

**Comment by bowring** [comment]
A further note on uncertainties:  you can access the value and uncertainty of any expression EXCEPT task-specified isotopic ratios (as listed in the left hand panel of the expressions manager) by referring to the underlying 0-based array:
```java
expressionName = value of expressionName
expressionName[0]  = value of expressionName
expressionName[1]  = 1 sigma absolute uncertainty of expressionName
```
However, for ALL expressions including ratios, as referred to in the previous comment, you can use:
[%"expressionName"] and [±"expressionName"]) to refer to the two flavors of uncertainty.  Note that
only the 1 sigma absolute uncertainty is stored and the percent uncertainty is always calculated on the fly.

**Comment by auscopegeochemistry** [comment]
Thanks @bowring. I'm happy to be mentioned and will keep at. Currently writing an custom report that will be able to populate all wanted fields in the data platform, [AusGeochem](https://www.auscope.org.au/ausgeochem), that we are developing with the AuScope Geochemistry Network ([AGN](https://www.auscope.org.au/agn)).

**Comment by bowring** [comment]
@auscopegeochemistry - Thanks for the update.  An improvement in the works is to provide simple formatting driven by 

1) specify a default significant digits count (currently 15) with specific overrides for an individual field

2) a count of significant digits in the 1-sigma absolute uncertainty, as pioneered in ET_Redux.  Thus for the case of 
12345.678 with 1-sigma abs of 23.45678, 
the user could specify 3 significant digits of uncertainty and the report would show
12345.7 with 1-sigma abs of 23.4;
and four digits would show
12345.68 with 1-sigma abs of 23.45.

If these ideas intrigue you or you have other suggestions, we are all ears.  The actual issue to discuss this feature in is #460.

I will paste these comments there as well to help get the conversation going.

Thanks!
