### ISSUE TITLE
Troubleshooting tips when processing OP files

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#594]
In processing a legacy OP file, I noted that most of my Built in expressions were returning 0 for all values.  

In order to assess where the problem might be I sorted these expressions by order of execution (Exec dialogue button).  From here I could see that I started to get problems with the Wtd CalibConstant calculation for the RM:
![image](https://user-images.githubusercontent.com/40035242/110490511-66192e80-80be-11eb-8b0a-33a317e797fe.png)
My next step was to proceed to the Interpretations - RM - Weighted mean window to see what was going on and I noticed that NONE of my analyses were selected. and this was likely because the "auto reject" button was selected (see upper left).  Once I DESELECTED that, it was possible to calculate a Wtd mean CalibConstant for the RM and proceed with the data processing.

![image](https://user-images.githubusercontent.com/40035242/110490308-2c482800-80be-11eb-96ca-cd1df3a24546.png)

This auto-reject option was selected right at the start in the Manage Project menu - this is my default but might be a poor choice when reducing data using .OP (I have not fully testing this but put this here as a warning).

![image](https://user-images.githubusercontent.com/40035242/110491281-20a93100-80bf-11eb-93ed-46cb2ab075c7.png)

This is part 1 of some quirky behaviour when processing OP files - more detail below.

**Comment by bowring** [comment]
Glad to see you trying it.  We only had one or two files to learn from, so your actual files and tasks will be helpful.

**Comment by NicoleRayner** [comment]
Once the problem above was resolved, I noticed something else odd - the first 7 RM analyses were normal, but the last ~20 were returning a value of 0 (despite the fact that these analyses return normal raw counts/ratios)
![image](https://user-images.githubusercontent.com/40035242/110494417-97dfc480-80c1-11eb-9107-301863f89a79.png)

Even more strangely, these RM analyses are not even showing up AT ALL in some of the expressions:
![image](https://user-images.githubusercontent.com/40035242/110494802-edb46c80-80c1-11eb-8f00-86d23586256b.png)

Upon further investigation of the Unknowns tab, almost NONE of the unknown analyses are showing up.  This lead me to examine the source OP file and I noted that the analysis immediately following the last one that showed up in squid3 had a problem with the SBM (all zeros).  Once I removed this analysis (Data --> Manage Spots --> Remove analysis 9009-35.1) everything worked as expected.
![image](https://user-images.githubusercontent.com/40035242/110497137-2f461700-80c4-11eb-9040-e3563df00cf6.png)

If it were possible to Audit the SBM of OP files (currently Audit is not a menu item for OP files, due to the absence of detailed scan/scan magnet settings/masses) that would be helpful.

Attached is the .squid file (which includes the offending analysis 9909-35.1, you can play with removing it yourself) as well as the raw .OP data. I used the built in 10 pk task. 

[Test OP files.zip](https://github.com/CIRDLES/Squid/files/6109717/Test.OP.files.zip)

**Comment by NicoleRayner** [comment]
In addition to making an audit of the SBM signal available for OP files, it is also worth noting that information about Spot Meta data (e.g. primary beam intensity, stage coordinates, QT1Y and QT1z are NOT available in .OP files (ever).  However, these are reported in squid3 as having a value of 0.  If possible, it would be better if these fields were given as not used/not found or n/a.

**Comment by NicoleRayner** [comment]
Maybe I should be making these as separate issues but I thought it might be helpful to have all .OP tips and tricks in one place for reference. 

Note that if you load an "Old Prawn" file type (commonly with .op file extension), under the Data menu you only get the options "Manage Sample Names" and "Manage Spots and Reference Materials".  However if you load the SAME Old Prawn file but change the extension to .txt you ALSO get the menu options of "Audit Data" (which doesn't do anything because you don't have the data needed to audit, like the primary beam intensity, this is neither here nor there), but also the option to "Replace project data ...."

You can test this with the .op file attached above.

No action needed at this point, just an observation.

**Comment by sbodorkos** [comment]
@NicoleRayner this sounds like fun!

I _think_ the underlying issue here (identified in early 2016, and filed under "to address later"...) is that Squid3 currently has no error-trapping of SBM data, at all. Strictly, this issue has nothing to do with the .OP format - you'd see identical Squid3 behaviour in a Prawn Data XML that had the same SBM measurements (or lack of).

@bowring I will raise a separate issue describing the very simple automated SBM error-trapping per SQUID 2.50, to prevent (at least in the interim) the behaviour Nicole has documented.

I agree with Nicole re Spot Metadata failing to zeroes, it would be much better to fail to "n/a" or a double-hyphen or something, because 0 is a real candidate for the QT1Y bit-value, for example.

**Comment by NicoleRayner** [comment]
CORRECTION!  The problem wasn't that SBM had gone to 0 for analysis 9009-35.1, the ION COUNTS were at 0 for the complete analysis but SBM was normal (a gate valve must have closed), so this behaviour doesn't represent what is being addressed in #597 but is good to keep in mind.

**Comment by NicoleRayner** [comment]
No further action needed.
