### ISSUE TITLE
Concordia Age - output is not as advertised

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#595]
I am attempting to calculate concordia ages for my samples in the expression builder,  using the Common Squid Function "concordia".  The output should be Age, 1σ abs, MSWD, Prob Of MSWD but it is only the 1s error (abs and %).

![image](https://user-images.githubusercontent.com/40035242/110505734-6ddfcf80-80cc-11eb-84fa-e26782b8165b.png)

This is not just in the peek, but also in the report.

**Comment by bowring** [comment]
This issue has its roots in the early decisions made about ET_Redux over 15 years ago where we agreed that data reports would consist of values and their uncertainties, if applicable.  The idea was that secondary results such as  MSWD would be handled as additional expressions with their own column (and uncertainty if applicable).  This approach got baked in and was never revisited until now.  

However, our design is flexible enough to accommodate this change, but it involves the next iteration of complexity for reports - giving the user control over whether the uncertainty - and now, the additional possible outputs from a defined function - are to be shown.  This iteration is in the design stage now with an uncertain (pardon the pun) release date. 

I have modified the **peek** window in the next release to show all the columns for a defined function per the suggestion above (thanks @NicoleRayner ).  The report columns can be handled in the short term by writing another expression that accesses the zero-based output array of the function as in:
```java
myConcordiaExpression = Concordia(4cor_207Pb235U, 4cor_206Pb238U, 4cor_ErrCorrel)
myAgeExpression = myConcordiaExpression[0] // note the string "Age" causes conversion to Ma
myOneSigmaAbsAgeExpression = myConcordiaExpression[1] // note the string "Age" causes conversion to Ma
myMSWDExpression = myConcordiaExpression[2]
myProbOfMSWDExpression = myConcordiaExpression[3]
```

The sam approach can be used for any other Squid function.

**Comment by NicoleRayner** [comment]
This is great.  Thanks.
