### ISSUE TITLE
Task Audit - include Task name description in csv report

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#596]
As with the Project Audit report, could we please get the Task name and description included in the project audit report?
I am suggesting that the task name gets included to facilitate searching the data once it gets brought into our database.  If we realize that there was an error in a specific task (with a specific name), we can more easily track down the offenders if the name is queryable.  

I don't think that Author, Lab and Provenance is that important but maybe for completeness these should be included too.

As for outputting the directives in a text format - I'm not sure that is necessary as this information is elsewhere but perhaps others have some insight?

**Comment by bowring** [comment]
Feature added in v1.7.6
