### ISSUE TITLE
Interim handling of feral SBM data

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#597]
Nicole has documented a bunch of nasty consequences (in #594 ) stemming substantially from processing a file which contains "bad" SBM data. In so doing, she has highlighted that we have never done any error-trapping in the SBM data. It's an omission that we noted back in the pre-Granada days, but which we have never acted on.

Because we need to do something about this, I will describe the logic and arithmetic that SQUID 2.50 uses to perform an _automatic_ check (and Preference-adjustment, where necessary). These procedures will serve until we have a chance to build something a bit more descriptive and interactive.

There are two basic operating principles for SBM data handling:

1. For any OP or XML file, no matter how poor the SBM data and/or how prevalent the zeroes, it should be possible to process the data "as normal" simply by de-selecting the "Normalise to SBM?" check-box. This de-selection should force Squid3 to do its arithmetic solely with the ion-count data, but otherwise proceed as usual. Nicole has documented the fact that Squid3 does not currently do this, which suggests we have some logic problem in the code handling the fundamental data processing (maybe it only affects OP input, but we can't yet rule out the possibility that it affects XML input as well).

2. If the automated check determines that the SBM dataset (overall) is "bad", then the remedy should be for Squid3 to override the input user-preference "Normalise to SBM?" = YES, with NO, and proceed as per 1. above.

**Comment by sbodorkos** [comment]
Automated SBM-checking: note that the below is only a consideration when the user sets "Normalise to SBM?" = YES. If they set NO, then none of the below code is executed.

During SHRIMP analysis, we generate/calculate an SBM value for every species, in every scan, in every analysis, and convert it to CPS by dividing by count_time_sec (analysis- and species-specific, but invariant between scans). We then subtract the "SBM zero" value, which is analysis-specific. In concept, at "datafile at once" scale, it looks like:

```
For i = 1 to Nanalyses

  For j = 1 to Nscans
    
    For k = 1 to Nspecies
    
      If InputFile = OP
      
        SBMCounts[i,j,k] = SBM[i,j,k] --SBM read directly from OP file
        
      Else  --InputFile = XML
      
        SBMCounts[i,j,k] = 10 * TukeysBiweight( SBM10subcounts[i,j,k], 6 )
        --SBM10subcounts read directly from XML file
        
      End If
      
      SBMCps[i,j,k] = ( SBMCounts[i,j,k] / count_time_sec[i,k] ) - SBM_zero_cps[i]
        
    Next k
  
  Next j
  
Next i
```

Ludwig's automated check is simply to ensure that **all** elements of SBMCps are positive (zeroes are not acceptable). If the user has set Normalise to SBM? = YES and all elements of SBMCps > 0, then the user is permitted to retain that setting and proceed with data reduction.

But if the user has set Normalise to SBM? = YES and even one single element of SBMCps <= 0, SQUID 2.50 automatically overrides YES with NO (without explicitly warning the user!) and data-processing proceeds with SBM data ignored at **datafile** scale. )I think there is plenty of scope (eventually) for a more nuanced approach in Squid3; see below.)

Firstly, it's important that the user does get an explicit warning when the software overrides a user-specified setting for "Normalise to SBM?", and I hope Squid3 can deliver one.

Secondly, down the track, I would like to see Squid3 build a mini-report of non-positive SBMCps elements arising from the check, and present it in "hierarchicalised" form to the user (i.e. _how many_ distinct species, scans, analyses, and _which ones_). This information would help the user to decide whether to (a) retain SBM normalisation by pre-deleting all analyses with aberrant SBMCps values, or (b) retain all analyses as collected, but abandon totally the idea of doing SBM normalisation of any of them.

**Comment by NicoleRayner** [comment]
There is some kind of SBM checking in squid3, see this message:
![image](https://user-images.githubusercontent.com/40035242/110691652-6810e980-81b3-11eb-97d5-ea3245c17e64.png)

Are you saying that even if I don't deselect SBM normalization, that squid3 is doing it for me anyway (which squid2.5 did, and didn't tell you). My usual habit is to use the audit function to find the offending analysis and remove it from Data Audit.  That might be a simple way to implement your SBM mini report above.  This way you can visually see which analyses have non-positive SBM (which analyses, scans, species).

**Comment by sbodorkos** [comment]
Sorry for the delay. It sounds like I was off-track with my original suggestion for the errors in @NicoleRayner s file. But the Squid3 warning message also raises a few questions.

1. How do we define "invalid" SBM counts in this context? I assume it means SBM values that, when converted to cps and zero-corrected, yield values <= 0, but it would be good to confirm.

2. "1 spot has invalid SBM counts"... the obvious user-question is "Which one?"

3. "Squid3 recommends switching SBM normalisation OFF..." - what happens to that one spot if you don't do this? 

I suspect, until we come up with something better, we need Squid3 (with a warning) to seize control of the SBM normalisation control in this scenario. This type dialog should read something like "SBM normalisation is ON, but Squid3 found 1 spot (label "ABCD.1") with invalid SBM counts. Please either Abort and remove these analyses from the data-reduction or Proceed with SBM normalisation switched OFF." 

Action buttons could be labelled:
- "Abort" (or similar): pressing this could return you to the list of analyses, where you could perform spot-removals.
- "Proceed" switches SBM normalisation to OFF, and updates everything.

The idea would be to ensure that you don't get mixed normalised and non-normalised data in the same data-reduction, and to ensure that analyses with invalid SBM counts are actively handled, rather than failing to zero.

**Comment by NicoleRayner** [comment]
Regarding point 3 above - this message just comes back again, and again and again every time you try and do something new.  It is annoying enough that you deal with it quite promptly.  
We certainly could have 2 action buttons - one that takes you to the Project Manage window so you can switch off SBM-norm and instead of "Abort" I would suggest the button says "check audit" and takes you to the Data Audit window, from there you are able to identify which was the offending analysis (either by looking at cps or primary beam) and remove it.  I would guess that 99% of the time using the cps or primary intensity in the Audit you will be able to tell which is the bad analysis and thus successfully remove the offending one.  But on the rare occasion where you cannot tell which is bad from the audit, the message comes back.

**Comment by NicoleRayner** [comment]
I think this issue can be closed.  I will make a new one to with a specific suggestion and we can go from there.
