### ISSUE TITLE
Weighted mean reports - also output total "N"

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#599]
Currently the weighted mean report outputs "n" the number of analyses included in the mean.  It would be helpful if it also output the total number of analyses (included those excluded) so at a glance it would be possible to tell how selective the calculation is.  This is currently shown on the WM plot as e.g. "n=13 of 15", so it would merely be a function of adding an additional column with for the "15", with the header "N (total)"  - I am open to other label suggestions here.

**Comment by NicoleRayner** [comment]
This request for including n, and N as indices for weighted means should apply to unknown WM, RM WM (as per issue #606) AND RM Calib constant

**Comment by bowring** [comment]
Feature provided in v1.7.6
