### ISSUE TITLE
RM-Plot any two Expressions, always goes to origin if the expression is an AGE (and labels as annum not Ma)

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#603]
This was brought to my attention by Allen Kennedy - as poor labelling/scaling for some plots.  
![image](https://user-images.githubusercontent.com/40035242/111809318-3aaaf680-88ab-11eb-9f49-a0579acb6aff.png)
Turns out, anytime you select an AGE as one of the expressions it goes to the origin on that axis 
In the short term you can zoom to scale the plot to your liking.   At the same time I noted that the axis labels for Age are given in annum not Ma, and at some point when you zoom in you get overlapping labels (on the x-axis).
![image](https://user-images.githubusercontent.com/40035242/111809271-2e269e00-88ab-11eb-8a66-b8c339f04c93.png)

**Comment by bowring** [comment]
Fixed in next release.
