### ISSUE TITLE
SBM auditing 

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#605]
Please add SBM trace to data audit as a means of easily identifying which analyses have problematic SBM (either zero, or major dropouts signifying other analytical problems).

**Comment by cwmagee** [comment]
Can we squid data with no SBM at all?
Or maxxed out SBM?
Will the latter even through an error?

**Comment by NicoleRayner** [comment]
I don't see how a maxxed out SBM would be a problem (for squid3).  As for no SBM at all, I think that the xml has to have an entry for SBM for the schema to be recognized, but even if they were all zeros as long as you turn off SBM normalization it should go.  Only one way to find out...Got an example file?  We can try it.

**Comment by cwmagee** [comment]
Maxxed out SBM is something that should be flagged. For example, if the max SBM count is repeated in more than 1% of all SBM readings.

**Comment by NicoleRayner** [comment]
We can discuss implementing this if/when we implement more advance zero trapping but in the short term adding it to the audit makes identifying/resolving these issues very simple to do on your own as part of routine data processing.  The instrument tells you when your SBM is maxxed out (or at least our does), so if you aren't aware/fix it then there is only so much squid3 can do to save you from yourself.    Clearly I am from the school of tough love, in life and in the lab. Good thing I don't have kids - I would mess them up.

**Comment by cwmagee** [comment]
Screen warnings aren't that useful in the age of autoruns, when the beam
can grow all night and hit the maximum if you're unlucky.

Even more frustratingly, the instrument may have told the guy who collected
the data 25 years ago the SBM was maxxed out, but it doesn't help the
person reprocessing it in the present unless we build a seance subroutine
to ask the original analyst.

If we are flagging out-of-range SBM numbers, we might as well tag the too
high ones at the same time as the too low ones. That's just good design.

**Comment by NicoleRayner** [comment]
This doesn't work for me on a file that has an SBM problem.  You can use attached as a test (github won't upload the zip file right now, I'll email it to you separately)

When I load the file, it recognizes that it has an SBM issue and gives me the recommendation to turn off SBM but n

othing happens in either data audit or SBM audit - squid3 just sits there and changing menus doesn't do anything either.  The only way I can get life back into it is to return to Manage Project, then any other menu item becomes live again.

**Comment by bowring** [comment]
@NicoleRayner - works fine for me with file you sent.  May be a memory problem on your machine - I have not addressed this yet.  I will make a new release that only pre-populates with 2 masses to save memory.

**Comment by NicoleRayner** [comment]
OK - good news!  In fact since I am working from home at the moment, this is the same machine that gave me similar grief before.  I should have thought of that.  Thanks in advance for the interim fix of pre-populating with 2 masses.

**Comment by bowring** [comment]
Latest solution in v1.7.7 - enjoy.
