### ISSUE TITLE
Weighted means for RM

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#606]
As discussed, please implement a parallel structure for calculating weighted means of the RM, similar to the one that exists for Unknowns.  This will be a separate Interpretations/RM menu item from the one that already exists - the existing one should be renamed "Calibration Constant", this new one "Weighted means". 

- All the same functionality from the Unknowns weighted mean window should be there (Calc WM from:, Sorted Ascending by: Save WM stats to file, Show WM in expressions and To SVG).  
- There will therefore be a need for a "RM Weighted Mean Plot and Sort" report template. 
- The "Filter by min. Prob. should be REMOVED for the RM window.  
- Instead the same "Auto-reject" and 'plot reject buttons should be included. 
- The WM stats report should be called WeightedMeanReportForRM_samplename.csv

**Comment by cwmagee** [comment]
Isn't the weighted mean by definition going to be the reference age/ratio?

**Comment by NicoleRayner** [comment]
It is for the 6/38 age/ratio, but I want to output things like the average UO/U for the RM to compare the the average UO/U of my unknowns. Or even the average 7/6 age to track things long term.

**Comment by bowring** [comment]
@NicoleRayner - haven't forgotten you and am now working on this ;-).

**Comment by bowring** [comment]
see version 1.8.1
