### ISSUE TITLE
Recenter problem 

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#609]
Interpretations/Reference/Plot any two expressions
If any axis of the plot is an _Age expression, then recenter does not work, as the zero for the _Age expression is included in the plot. 

<img width="720" alt="Screen Shot 2021-04-12 at 12 38 56 pm" src="https://user-images.githubusercontent.com/33318855/114341347-22698700-9b8c-11eb-9f27-28ddc503001b.png">

**Comment by bowring** [comment]
@AllenKennedy - I fixed that but had not released the fix - thanks for reminding me - will do shortly!

**Comment by bowring** [comment]
fixed in release v1.7.5
