### ISSUE TITLE
Word wrap on Project notes

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#616]
This is such a trivial issue (especially in light of the random number thing) but I am re-reducing some very old .op data and I need to add notes to the Project Notes field.  The text box does not implement Word Wrap however so I need to scroll to be able to read my notes (or add carriage returns mid-sentence).   Word wrap would be a big help.  Thanks, your squid3 Tinkerer.

![image](https://user-images.githubusercontent.com/40035242/116720648-76f16c80-a9aa-11eb-87f1-1d679e798760.png)

**Comment by bowring** [comment]
addressed in v1.7.10
