### ISSUE TITLE
Can't deselect a spot in Audit screen inspection window

### ISSUE THREAD

**Issue by TPestaj** [CIRDLES/Squid#620]
Squid3 Version: 1.7.8
Java Version: 1.8.0_281
OS: Windows 10 10.0

Issue details:  Once a spot is highlighted in the 'inspection window' of the audit screen, I can't seem to de-select it, only change which spot is selected within it.  Furthermore, the highlighted _position_ is retained when I move the inspection window rather than 'sticking' to the spot that was selected.  (At least that's how I would expect it to work.)

This seems to be more of an annoyance as opposed to a functional issue as I can seemingly remove the selected spot without trouble, but the selection still cannot be cleared from the inspection window.

**Comment by bowring** [comment]
@TPestaj - I understand your question about stickiness - the current behavior is based on the assumed use case that the sliding zoom window would be positioned before selections were made and that if the selected spot were to slide out of the zoom window it would become unreadable anyway - in fact selection mode is turned off in the non-zoomed portions for that reason of readability.  Suggestions welcomed!

The on / off is fixed in next release: v1.7.10.

**Comment by TPestaj** [comment]
I might not be approaching the Audit window as it was intended, but I would expect that a selection made within the zoom window would stick to that analysis, instead of sticking to the position within the zoom window as it does now.

As for how to handle selections once they are outside the zoom window range, perhaps just indicating that they are still selected   would be good enough to prompt the user to inspect it with the zoom window, despite not being able to read the label.  Something like this:

![image](https://user-images.githubusercontent.com/43234276/118674552-dd0e2a00-b7c7-11eb-8f6e-d551ca2906a8.png)


And while we're here, it'd be nice to be able to select non-adjacent analyses instead of just blocks of them (i.e. 'ctrl-click' in addition to 'shift-click').

**Comment by bowring** [comment]
@TPestaj - For now with v1.7.10, multiple selections are possible and unselecting is done by control click (toggle select), the selections travel with the sliding window, the sliding window is wider and much better behaved;  However, tracking and showing selections beyond the zoom is not practical.  Try it out once it is published and start a new issue if needed.
