### ISSUE TITLE
Possible problem with Browse, Load, Edit of a custom task

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#627]
I Edited a task (image 1), changing the indirect 232Th/238U_RM equation to ["232/238"] and Saved this to my SQ3 custom task folder. I then Loaded it and the screen (image 2) showed the new equation. I then selected Use to Replace Current Task, Mapped the isotopes, and ended up back where I started (image 3). The zip of the SQ3 project is attached.
(1)
<img width="1249" alt="Screen Shot 2021-05-20 at 1 37 10 pm" src="https://user-images.githubusercontent.com/33318855/118928426-c86f9480-b975-11eb-961a-049caa812c3b.png">
(2)
<img width="1247" alt="Screen Shot 2021-05-20 at 1 37 54 pm" src="https://user-images.githubusercontent.com/33318855/118928457-d32a2980-b975-11eb-84e4-eaa00c8c717d.png">
(3)
<img width="1247" alt="Screen Shot 2021-05-20 at 1 38 56 pm" src="https://user-images.githubusercontent.com/33318855/118928506-e5a46300-b975-11eb-808d-978a1a5adc01.png">

[FMG high Th.squid.zip](https://github.com/CIRDLES/Squid/files/6513349/FMG.high.Th.squid.zip)

**Comment by bowring** [comment]
@AllenKennedy - Actually the change has been made under the hood - you can confirm if you edit the task or look at the expression manager.  What you have found is a bug in how the task is displayed in screen shot 1  - one typo and all is good.  See this fix in v1.7.10 coming soon.   Good sleuthing!
