### ISSUE TITLE
Non-updating of RM 206/238 weight mean diagram

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#629]
When I have "auto reject"  and "plot rejected" selected then toggle between 204 and 207 index isotope, or toggle between systems 206Pb/238U and 208Pb/232Th ,the diagram isn't updating with each toggle. The list of points change every toggle, but not the diagram. (see figures below).

Is this error trapping, as there is one analysis with No Age Calculated?

(1) 206Pb/238U weighted mean diagram with "auto reject" , prior to selecting "plot rejected"

<img width="1249" alt="Screen Shot 2021-05-28 at 12 31 22 pm" src="https://user-images.githubusercontent.com/33318855/119930529-32112380-bfb2-11eb-8247-a4bce1ea01a3.png">

(2) 206Pb/238U weighted mean diagram after "plot rejected" selected

<img width="1248" alt="Screen Shot 2021-05-28 at 12 31 47 pm" src="https://user-images.githubusercontent.com/33318855/119930556-41906c80-bfb2-11eb-9fcd-e037fc519978.png">

(3) 208Pb/232Th weighted mean diagram with both auto reject and plot reject selected 

<img width="1242" alt="Screen Shot 2021-05-28 at 12 32 14 pm" src="https://user-images.githubusercontent.com/33318855/119930571-46edb700-bfb2-11eb-9e0c-52d75cc80bfb.png">

(4) toggle to 206Pb/238U weighted mean diagram with both auto reject and plot reject selected
...no update as we still have the still have 208Pb/232Th 

<img width="1250" alt="Screen Shot 2021-05-28 at 12 32 38 pm" src="https://user-images.githubusercontent.com/33318855/119930595-4f45f200-bfb2-11eb-80e5-0d81d961143b.png">

[Allanite C36 A46.squid.zip](https://github.com/CIRDLES/Squid/files/6558262/Allanite.C36.A46.squid.zip)

**Comment by bowring** [comment]
@AllenKennedy - on first pass, if I remove the offending spot TARA.4.1, all seems well.  So we need to decide what to do in the presence of no age - currently Squid3 is choking.  One solution is to skip the offender or plot a blue dotted line?  Ideas welcome here.

**Comment by AllenKennedy** [comment]
I think a blue dotted line would make the user aware that something is wrong in the data. Maybe others will have an opinion.

**Comment by bowring** [comment]
I am proposing this - see image.
<img width="752" alt="issue629" src="https://user-images.githubusercontent.com/1092963/120071743-a4d7d880-c05e-11eb-8744-6af9a5632b34.png">

**Comment by AllenKennedy** [comment]
looks like a good solution to me

**Comment by AllenKennedy** [comment]
@bowring    Jim, Do you want me to continue to do idiot proofing, by doing data reduction with old data sets?

**Comment by bowring** [comment]
@AllenKennedy - Please do for now ...
