### ISSUE TITLE
Data Audit issue with Ancient data set

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#630]
I loaded a very old (2011) XML data set and SQUID3 would not load it. This is because of a problem with the 7th line of the XML file? I cut and pasted the top 7 lines of a recent XML file and SQUID3 happily loaded the doctored XML file. Everything then worked fine, except for Raw Data Audit. I started with image (1) and when I dragged and dropped the first peak I got image (2). After that drag and drop did not work.  

Should we place a limit on backwards compatibility?

(1) 
<img width="1258" alt="Screen Shot 2021-06-01 at 3 03 00 pm" src="https://user-images.githubusercontent.com/33318855/120283085-6572eb80-c2ed-11eb-9c10-c28a43dc56c3.png">
(2) 
<img width="1252" alt="Screen Shot 2021-06-01 at 3 03 18 pm" src="https://user-images.githubusercontent.com/33318855/120283116-6d329000-c2ed-11eb-9de4-4bda0520ede0.png">

[BR8 Apatite 2.squid.zip](https://github.com/CIRDLES/Squid/files/6574263/BR8.Apatite.2.squid.zip)

**Comment by NicoleRayner** [comment]
I'm having similar issues to image 2 for some recent xml files (so this is not totally a function of vintage).  In my case nothing shows up in data audit other than the axes, and if I leave the Data Audit window then return to it I get the blue welcome screen (everything else continues to work fine). I haven't quite sussed out exactly what is triggering it (I've been meaning to run it in verbose but haven't yet), so I haven't yet made an issue of my own.  Here is my problematic .squid file FWIW.

![image](https://user-images.githubusercontent.com/40035242/120328757-2460e400-c2b9-11eb-86e4-a838d75974df.png)
[367_2_2020_Dec_01_10.46.zip](https://github.com/CIRDLES/Squid/files/6576458/367_2_2020_Dec_01_10.46.zip)

Additionally, I've noted that the radio buttons don't track when you open/close files.  If you close a file showing SBM counts, when you reopen a file, it still displays SBM in the graphs, but the Display Mass button is selected.  It is easy enough to "wake up" by changing/changing back to your selection, so just a little gremlin.

**Comment by bowring** [comment]
@AllenKennedy - please send original XML file.

**Comment by bowring** [comment]
The audit window issue is resolved in the soon-to-be-release v1.8.0 (skipping v1.7.11).  The problem was related to the small (<40) number of samples.
