### ISSUE TITLE
TW diagram is okay, but Wetherill diagram isn't

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#637]
In the attached SQUID file most unknowns plot correctly in both TW and Wetherill concordia. ALBUR and ALOLD plot okay in TW, but not in Wetherill (see the images for ALOLD) I did have a look at the 204 corrected 207Pb*/235U values for ALOLD and could not see a problem.  I tried re-center, but the Wetherill diagram does not change.

<img width="1247" alt="Screen Shot 2021-06-29 at 2 00 36 pm" src="https://user-images.githubusercontent.com/33318855/123752211-2d11fd80-d8eb-11eb-99e2-cf6f1d003181.png">
<img width="1251" alt="Screen Shot 2021-06-29 at 1 39 17 pm" src="https://user-images.githubusercontent.com/33318855/123752275-3733fc00-d8eb-11eb-8b55-82a70349fce3.png">
[Allanite C36 A46.squid.zip](https://github.com/CIRDLES/Squid/files/6731331/Allanite.C36.A46.squid.zip)
)

**Comment by bowring** [comment]
@AllenKennedy - The attachment did not come through - please send again!

**Comment by bowring** [comment]
@AllenKennedy - Update: the zipped file showed up in the email sent by GitHub, so I had a look with current version of Squid3 and all seems well as shown in image.
<img width="1251" alt="alold" src="https://user-images.githubusercontent.com/1092963/123946647-72770f00-d96d-11eb-8e55-2df462a9ce3d.png">

**Comment by bowring** [comment]
I assume this is no longer an issue.
