### ISSUE TITLE
default lab report - doesn't remain selected

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#643]
When I start a new squid project (or open an old one where this hasn't yet been defined) the "Builtin Report table for Unknowns" - which is the first in the list on the Custom Report window is selected, even though I have defined a different "default" lab report.  

The "default" one is the one that should be automatically selected (and therefore generated when you hit the Generate all reports button).  

Likewise for the RM reports (but I don't have a custom one for that no I haven't tested it)

**Comment by bowring** [comment]
Thanks @NicoleRayner -   Implemented as of version v1.8.3!
