### ISSUE TITLE
WM reports - default csv file name

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#647]
It would be great, if keeping with the report naming convention, that the name of the WeightedMeanReportforSample could be prefixed with the squid3 file name.  This helps ensure unique file names for all these files (especially since often times the WM of the same secondary RM might be measured on many, many mounts).  In order to keep the file name a bit shorter/tidier this could be:
Squid3Name_WMReport_XXXX.csv

**Comment by NicoleRayner** [comment]
Another thought, can the WMReport for the RM be differentiated in its name someway from the WMReports from the "unknowns"? 
Perhaps it could be Squid3Name_WMReport_RM_XXXX.csv instead?

**Comment by bowring** [comment]
Coming in version v1.8.3 !
