### ISSUE TITLE
Task Audit report - include all fields? 

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#652]
It would be super helpful for me to have the entire task audit window captured in a .txt file (not just the bottom Task Audit box as currently).  Once we get squid3 data sucked into our database I could then track/filter data based on task name, or directive.  Thanks!  I should have thought of this earlier....

**Comment by bowring** [comment]
Solution is to make one report "Project and Task Audit" that has all the details.  Check it out in v1.8.5, arriving soon!
