### ISSUE TITLE
DefCom parameters (in Expressions) do not reflect selected (and refreshed) Common Pb Model

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#655]
Win10, Squid3-v1.8.4

New Project in Squid3, load my Prawn XML and proceed through the Manager Project window like this, selecting Common Pb Model = Stacey-Kramers at 416.78 Ma, and mashing the Refresh Models button:

![image](https://user-images.githubusercontent.com/17473203/135857572-e2d7a08c-b878-43c4-ba77-a0b8aa783e9a.png)

But when I check the DefCom parameters in the Expressions Manager, I see the values corresponding to the startup Common Pb Model which Squid3-1.8.4 put in place when I installed it. Nothing I can do changes it.

![image](https://user-images.githubusercontent.com/17473203/135857266-ed0334a3-2515-4415-86cc-db52c3fe47ea.png)

This is not just an issue with the display-name for the Model; the actual value of DefCom_206Pb204Pb is not the one I want either (i.e. 18.04 is the value that truly goes with that Monazite 74 84 Model, whereas the value I want, based on Stacey-Kramers at 416.78 Ma, is 18.053).

**Comment by sbodorkos** [comment]
Forgot the Squid file:
[170111_GA6357_Sq3-184.zip](https://github.com/CIRDLES/Squid/files/7278387/170111_GA6357_Sq3-184.zip)

**Comment by bowring** [comment]
Good catch - this is a quirk associated with making the common pb model choice before the task is initialized ... it should not matter, but it does right now and this will be fixed.  You can correct the problem by going back to the model chooser and choosing a third model, refreshing, then choosing your desired model and refreshing.

**Comment by bowring** [comment]
Another workaround is to immediately press Set Defaults after choosing  your model and before selecting your task.

**Comment by bowring** [comment]
fixed in v1.8.5 to be released soon
