### ISSUE TITLE
Sample Names do not appear in allocated Report column

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#656]
Win10, Squid3-1.8.4

I have assigned my Sample names as follows, and this is all good. 

![image](https://user-images.githubusercontent.com/17473203/135859809-6bcb704c-a42f-4957-b8b8-568edc07d4e3.png)

What I am hoping for is that in my 'UnknownsReportPerSquid2.5' CSV, these Sample Names (precisely as ticked, with no assumptions about delimiters or character-counts) will appear in the dedicated 'Sample' column. Sadly, that column is currently blank:

![image](https://user-images.githubusercontent.com/17473203/135861012-df978d52-867f-401d-aa57-037d37eb476f.png)

**Comment by sbodorkos** [comment]
Oops, forgot the SQUID file:
[170111_GA6357_Sq3-184.zip](https://github.com/CIRDLES/Squid/files/7278378/170111_GA6357_Sq3-184.zip)

**Comment by bowring** [comment]
Fixed in v1.8.5 - to be released.
