### ISSUE TITLE
Th/U error in custom reports

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#657]
The error for the Th/U (232Th238U) is not output for custom reports.  It is output however when using the "Unknowns - per squid2.x" template (under miscellaneous reports).  Is there a specific reason for this?  In order to duplicate "our" squid2.x data format (which is not exactly the same as the standard as we have custom equations in squid2.5) it would be very nice to get this back.

**Comment by bowring** [comment]
can you point me to a squid project that uses 232?  or supply one. thanks

**Comment by NicoleRayner** [comment]
232Th238U is a NU fixed expression in any geochron project including the demo

Attached is a custom report template (it won't fully populate for the demo project but the Th/U issue (aka no error) should persist.

[Zinfo zircon report template.zip](https://github.com/CIRDLES/Squid/files/7295781/Zinfo.zircon.report.template.zip)
.
