### ISSUE TITLE
CSV Output Templates - Squid Output for AusGeochem 

### ISSUE THREAD

**Issue by auscopegeochemistry** [CIRDLES/Squid#659]
Hi Team,

With the AuScope Geochemistry Network we developed a Squid3 importer for our data platform (AusGeochem) that is connecting laboratories to a repository and collaboration - publishing platform.

I have created a template that includes Concentration values for U-Th and Th/U, as well as metadata on the common lead correction used for unknowns.

Would it be possible to publicise this template via CIRDLES or include it in the Squid Build after your review?

Thanks.
Alex

[AGN-AusGeochem-SquidReport-template.zip](https://github.com/CIRDLES/Squid/files/7308065/AGN-AusGeochem-SquidReport-template.zip)

**Comment by bowring** [comment]
Yes -a great solution for report templates and for collections of parameter models and tasks is to make a public Github repository with subfolders for each category.  Squid3 could then access these folders per context and provide for loading them and allowing the user to select an item for use in a way similar to selecting from a local folder.  Users could make pull requests to the repository for any new files they would like to contribute and the manager of the repository could vet and accept them.  Once the files are in the repo, then subsequent visits by Squid3 will show them.

@sbodorkos - if you set up a trial repo with a folder for "reportTemplatesUnknownSamples" or similar and give me admin permissions, we can experiment with how best to proceed.

**Comment by bowring** [comment]
With no further comment, I am closing.
