### ISSUE TITLE
In Custom Report, 8cor_ErrCorrel has two columns (should only be one!)

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#666]
8cor_ErrCorrel looks fine in the Expression Manager, and it also looks fine in the Custom Report Builder (see below):

![image](https://user-images.githubusercontent.com/17473203/141780685-617a0b96-b704-4a76-8d14-f0dde65753cd.png)

The Column Details/Peek shows one Value per spot, which is what users would expect. But when the Report CSV is generated, 8cor_ErrCrrel contains two columns (albeit the second is permanently filled with 'n/a'):

![image](https://user-images.githubusercontent.com/17473203/141782162-123e66c4-c206-464a-94a3-170b61ac4fcd.png)

This problem seems to be restricted to the Custom Report Builder, so hopefully not too difficult to run down!

**Comment by bowring** [comment]
The return value count in Rad8corConcRho was mistakenly set to 2 instead of 1.  Fixed in v1.9.2 coming soon!
