### ISSUE TITLE
RefMaterial Reports need access to more metadata

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#667]
It is already possibly to report arrays of Reference Material data comprehensively, but these arrays lack direct records of key user-defined parameters ("metadata"). I have identified three that I would like to have access to, in support of general-purpose reporting (see below).

Note that in each case, these parameters are not spot-specific: they apply equally to all analyses in a Ref Material Report CSV (i.e. they will appear as repeated values from row to row in the CSV report). All three are controlled by radio-buttons in Squid3, so the outputs should be easy to standardise.

1. **Suggested header: "Primary daughter/parent ratio"**, candidate values (a) 206Pb/238U and (b) 208Pb/232Th. Specified by Task... View Current Task... Directives.
2. **Suggested header: "Secondary daughter/parent calculation"**, candidate values (a) Direct and (b) Indirect. Specified by Task... View Current Task... Directives.

![image](https://user-images.githubusercontent.com/17473203/144247039-212af750-d657-4bda-b31b-24e1adc260d9.png)

3. **Suggested header: "Index Isotope"**, candidate values (a) 204Pb, (b) 207Pb, and (c) 208Pb. Specified by Interpretations... Reference Materials... Calibration Constant WM.

![image](https://user-images.githubusercontent.com/17473203/144247454-ecfe6417-50f5-4547-8c35-2788eec4cd24.png)

It's mandatory to set all three radio-buttons before you can generate a Report, and being able to include the settings as part of the Report array would help remind users "where to look". 

For example, one Task/Project is capable of delivering up to four arrays of calibration-constant values (depending on the Task setting for Secondary daughter/parent calculation, are accounting for all the legal candidates for Index Isotope). The metadata would help remind users which of the four is the "primary" calibration.

**Comment by NicoleRayner** [comment]
Perhaps you are looking for this in a differernt format, but this stuff is included in the Project and Task audit report.

**Comment by sbodorkos** [comment]
Yeah, I know, but it's a bit of a weakness of our reporting that you need to look at one CSV to interpret another CSV. I am keen for a bit of redundancy, where child outputs (i.e. data-tables) inherit some of the important characteristics of their parent records (e.g. processing metadata). Little bit less scope for things to go wrong.
