### ISSUE TITLE
RM Report-template field "IndexIsotope" (in Custom Report Builder) does not update

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#669]
Re the new (Squid3 version 1.9.2) RM Report-fields: "PrimaryDaughterParentRatio" and "SecondaryDaughterParentCalculation" are both fundamental directives controlled by the form of the selected Task.

However, "IndexIsotope" is controlled by radio-button within the Project, and (linked) within the Reference Material Interpretation. That radio-button needs to be polled every single time an RM Report is generated:

![image](https://user-images.githubusercontent.com/17473203/145021281-165029c7-a7e7-4408-8288-6caaf4265aa3.png)

Really, the radio-buttons controlling all three fields should be polled every time, regardless. 

When I switch the radio-button, I can generate a new RM Summary report which understands the change, but nothing I do is capable of changing the outdated contents of the IndexIsotope field in the RM report-template.

**Comment by sbodorkos** [comment]
Then I switched the Project to a Perm2-style Task (i.e. direct calibrations for both Pb/U and Pb/Th), and all three of the new RM Report-template fields ("IndexIsotope", "PrimaryDaughterParentRatio" and "SecondaryDaughterParentCalculation") returned "not found" in my RM Report.

**Comment by bowring** [comment]
I cannot replicate - please send .squid file.

**Comment by sbodorkos** [comment]
Here is my RM Report super-template:
**[SQ2.50 StandardData ALL Report-template.zip](https://github.com/CIRDLES/Squid/files/7668756/SQ2.50.StandardData.ALL.Report-template.zip)**

Here are the two Tasks I have used in this Project at different times:
**[10peak_zircon_Tasks.zip](https://github.com/CIRDLES/Squid/files/7668757/10peak_zircon_Tasks.zip)**

Here is the Project (I don't remember which Task is actually loaded at present):
**[170111_GA6357_Sq3-192.zip](https://github.com/CIRDLES/Squid/files/7668758/170111_GA6357_Sq3-192.zip)**

**Comment by bowring** [comment]
The new metadata fields do not appear in these files, so I added them and saved the report and they behave properly.  Can you send the same files with the mis-performing metadata fields present?  Maybe we should schedule an online demo of the problem if I still can't replicate it after that?

**Comment by bowring** [comment]
Followup - I see where the fields are present in the group "Prelims", so no need to send anything, but they still behave correctly for me so maybe an online demo of the problem is in order?

**Comment by sbodorkos** [comment]
I can see them in the version I sent, when I use my Custom RM report-template, as follows:

![image](https://user-images.githubusercontent.com/17473203/145228840-fd566213-528b-4ee9-a65d-7a8704b0ea03.png)

In the process of generating this screenshot and pressing Create CSV, I have discovered that the new fields come out fine in the CSV, **as long as you Peek at them first** (as per my screenshot). But if you don't Peek at them individually, you get "not found" in the CSV, which is not great.

**Comment by bowring** [comment]
I can replicate and fix that!

**Comment by sbodorkos** [comment]
In addition, if I change the Project Index Isotope (e.g. from 204Pb to 207Pb) using the radio-button and then quit Squid3 **without saving**, that also fools the IndexIsotope field in the Custom Report Builder. It "remembers" the change (even though I didn't Save), 

So when I restart Squid3 and open that Project, the Project Index Isotope setting is 204Pb (because the change to 207Pb was not Saved), but when I go to CustomReport Builder and press View CSV (without Peeking), the RM Report-field IndexIsotope still returns 207Pb in the CSV. Which is wrong.

**Comment by bowring** [comment]
Yeah that is related to the previous problem.
