### ISSUE TITLE
NU-switched Expressions with negative values yield (impossible) negative uncertainties in Ref Mat Report

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#672]
My Task contains a NU-switched expression (with Unct) "LnPbU". In the Custom Report Builder, I can Peek at the output, and it looks fine:

![image](https://user-images.githubusercontent.com/17473203/145757252-3ce6ee50-393a-4ac3-a91f-11b2a4c80e31.png)

But when I actually generate the report CSV, the percentage uncertainties are negative:

![image](https://user-images.githubusercontent.com/17473203/145757483-e5378975-dada-45e7-bc34-0129646c0d93.png)

This is obviously bad. But more to the point, why are the Expression-outputs taking one path to the Peek window, and another path to the CSV? I can't understand how they can **ever** become decoupled, and it is very unsettling - makes me wonder how many other similar issues are out there, undetected because they're not obvious enough.

**Comment by bowring** [comment]
The percent uncertainties are not coupled to anything - they are calculated on the fly - the absolute uncertainties are coupled to the values.  This bug is simply a case of not applying the absolute operator to the calculation of the percent uncertainties in the reports generator.  Good catch.

**Comment by bowring** [comment]
As a followup - I identified everywhere percent uncertainty is calculated - 22 places - and confirmed that all use absolute operator.

**Comment by bowring** [comment]
Question - in searching for all calculations capable of producing negative percents, I came upon % discordance, which in Squid and ET_Redux has always had positive and negative values - in fact, Gehrels specifically looks at negative and positive discordance in his analysis.  What should we do about it?  Currently, for example, 8cor_Discord_Pct is calculated as:
``` java
100*(1-8cor_206Pb238U/(EXP(Lambda238*8cor_207Pb206Pb_Age)-1))
```
![image](https://user-images.githubusercontent.com/1092963/145834624-5af959b9-f807-4f1b-89a0-7c4ece2f4791.png)

This produces positive and negative values, as does 4cor_Discord_Pct:
``` java
100*(1-4cor_206Pb238U/(EXP(Lambda238*4cor_207Pb206Pb_Age)-1))
```
![image](https://user-images.githubusercontent.com/1092963/145835405-48e00115-58fb-436b-b9bb-75ece24d8551.png)

Thanks!

**Comment by NicoleRayner** [comment]
Positive and negative are permitted as each have different meanings (below vs above the concordia curve, respectively).  All good as is.  The negative discordance can be geologically induced (though rare), in SHRIMP it is often the result of a problem with the calibration (or rather a problem with the matrix of the unknown zircon that is unlike that of the RM)

**Comment by bowring** [comment]
Next question - how about the "delta percents"?
4cor_8cor_PrimaryCalibConstDelta_Pct:
```java
100*((1-Com_206Pb204Pb*["204/206"])/(1-Com_206Pb204Pb*4cor_204Pb206Pb_OvCtCorFrom208Pb)-1)
```
7cor_8cor_PrimaryCalibConstDelta_Pct:
```java
100*((1-Com_206Pb204Pb*["204/206"])/(1-Com_206Pb204Pb*7cor_204Pb206Pb_OvCtCorFrom208Pb)-1)
```

7cor_PrimaryCalibConstDelta_Pct:
```java
100*((1-Com_206Pb204Pb*["204/206"])/(1-Com_206Pb204Pb*204Pb206Pb_OvCtCorFrom207Pb)-1)
```
