### ISSUE TITLE
Expression  4cor_206Pb238U_Ext1SigmaErr_Pct not taking the minimum value defined by user.

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#674]
I noticed this in the the RM summary report - I have set my minimum error at 0.8.

![image](https://user-images.githubusercontent.com/40035242/145870779-739e4bca-f2bb-4b17-b8b0-9d5c1ed8c00d.png)

But in the expression manager/summary report it shows as 0.75 (the default)

![image](https://user-images.githubusercontent.com/40035242/145870844-da386fab-71d1-461b-8d49-cf9ef0708172.png)

But it appears to be doing what I told it on the RM calibration diagram
![image](https://user-images.githubusercontent.com/40035242/145870976-c43f43fe-c020-48e5-a8ba-9334f9aec0d7.png)

**Comment by bowring** [comment]
send .squid please.

**Comment by NicoleRayner** [comment]
[1000_1_2021_Dec_07_10.10.zip](https://github.com/CIRDLES/Squid/files/7713852/1000_1_2021_Dec_07_10.10.zip)

Its strange, if I change it in the Manage project window it "wakes up" and takes it, but you will see when you open there is the disconnect shown above.

0.8 is my default value.
