### ISSUE TITLE
Custom Report gives correct columns in View but not Create CSV

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#677]
Squid3 version 1.9.4 in Win10, and Squid3 Project attached.

**[170111_GA6357_Sq3-194_Perm1.zip](https://github.com/CIRDLES/Squid/files/7846912/170111_GA6357_Sq3-194_Perm1.zip)**

Below is a screenshot of the Custom Report I am testing. The key Category is Calibrations, where you can see I have only 7 fields:

![image](https://user-images.githubusercontent.com/17473203/148949832-1e5f7fa1-74ac-44e2-8ff9-82506e25cb87.png)

When I press View, these fields are replicated faithfully, and the final field of the Calibrations category (8cor_206Pb238U_Age_RM) is followed immediately by the first field of the Chemistry category (which is 4cor_Com206Pb_Pct_RM), as would be expected (see below). All good.

![image](https://user-images.githubusercontent.com/17473203/148952279-da669973-3309-47ec-ad5d-9814474155ec.png)

But when I press Create CSV and Open File, a bunch of extra columns appear (BT–BZ in the below image), in between 8cor_206Pb238U_Age_RM and 4cor_Com206Pb_Pct_RM, related to overcounts. 

![image](https://user-images.githubusercontent.com/17473203/148951260-2376fd41-7e13-4c33-bd52-f1ffe74ec2fd.png)

I know why these fields appear there: they **used** to be part of the Calibrations category, in one of my earlier iterations of this Report-template. I have since deleted them from there, and reintroduced them in their own Overcounts category. 

I have Saved both the Report-template and the Project several times since, and have even tried Exporting the Report-template to XML and re-importing it into the Project. None of that helps. The View gives me the correct columns, but Create CSV + Open File does not. 

It seems like Create CSV + Open File does not check for the most up-to-date list of fields within each category; instead it is going with some out-of-date "memory" of those fields.

**Comment by bowring** [comment]
This is related to issue #678 and fixed in next release.
