### ISSUE TITLE
Error in calculation of 4cor_207Pb206Pb_Age_RM

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#678]
This is a nasty one, not sure how I missed it in testing.

In theory, each value of 4cor_207Pb206Pb_Age_RM would be displayed (in Peek and in CSV-report) by taking the Age value (in annum) and dividing it by 1.0e6, to give a value in units of Ma.

What is actually happening (as you can see below) is that this calculation is taking the 4cor_207Pb206Pb_RM **ratio** value (not the Age value) and dividing the **ratio** value by 1.0e6 to report 4cor_207Pb206Pb_Age_RM. The result is nonsense.

![image](https://user-images.githubusercontent.com/17473203/148956784-98fff7f8-1392-4030-8873-31af77da384d.png)

The same thing is happening in the Peek, but there it is clearer what is happening. Note the mismatch between the name of the field I am peeking at (which includes 'Age') and the heading of the left-hand column of the Peek (which does not include 'Age'):

![image](https://user-images.githubusercontent.com/17473203/148957468-34c0f789-1b00-4998-8fcb-4e908f983380.png)

**Comment by NicoleRayner** [comment]
That is so strange and I haven't noticed it either because the  4cor_207Pb206Pb_Age_RM on the Interpretations (Reference Materials - Weighted Means)  IS fine.  And it writes to the WM report as such too.
![image](https://user-images.githubusercontent.com/40035242/148988996-7fbb83e0-a8ca-4dac-98a4-88a0447c8d47.png)

**Comment by NicoleRayner** [comment]
It gets worse.  Its not just the weighted mean that is wrong, it is the individual analyses for the unknowns as well.  This is new as of v. 1.9.4

**Comment by bowring** [comment]
Looking into this ...

**Comment by bowring** [comment]
Found and fixed in next version v1.9.6.  The bug was only in the peek / reporting logic, not the underlying logic, and was a side-effect of solving the aliased expressions issue and not testing thoroughly.
