### ISSUE TITLE
Weighted Mean from: Concentrations all 0.0

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#686]
Interpretations:unknowns:Calc Weighted Mean from: Concentrations: Uunk,Thunk,Ycpsunk are all 0.0. Is this because there is no Ycps?

**Comment by bowring** [comment]
@AllenKennedy   can you supply a squid file with these expressions and more details?  Thanks

**Comment by AllenKennedy** [comment]
Hi Jim,
I am puzzled. The SHRIMP Misc. report for the unk already contains U and Th concentrations, so that is what I was expecting would be used in Calc Weighted Mean and shown in the diagram.

**Comment by bowring** [comment]
weighted mean calculator requires non-zero uncertainties;  currently calculated concentrations have 0 uncertainty:
U_Concen (for an unknown) = ParentElement_ConcenConst/Av_ParentElement_ConcenConst*Ref_U_Concen

You can always add expressions for the weighted mean visualizer by editing the report "Weighted Mean Plot and Sort Report"

Hope this helps

**Comment by AllenKennedy** [comment]
Thanks,
That helps. I will look at the WMPS report.
