### ISSUE TITLE
setting minimum external 1sigma error - 

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#688]
While squid3 permits you to type in a desired minimum error, it doesn't actually TAKE it (if you browse away and come back it has returned to its earlier setting, setting as default doesn't help either).  You need to use the up/down increment buttons to get it to actually take.  Minor but a bit diabolical/confusing. 

Squid3 Version: 1.9.9
Java Version: 1.8.0_321
JavaFX Version: 8.0.321-b07
OS: Windows 10 10.0

Issue details:

**Comment by bowring** [comment]
@NicoleRayner - press **enter** after typing number and it sticks. :smile:

**Comment by bowring** [comment]
@NicoleRayner - fixed in next release v1.9.10 😷
