### ISSUE TITLE
Weighted Means turns into Concordia

### ISSUE THREAD

**Issue by TPestaj** [CIRDLES/Squid#689]
Squid3 Version: 1.9.9
Java Version: 1.8.0_321
JavaFX Version: 8.0.321-b07
OS: Windows 10 10.0

I found a weird bug (or maybe a family of them?) that seems to transform a weighted means plot into either a concordia plot or nothing at all.  It's a little convoluted to get to, but I've been able to induce it on all data files I've tried (including the demo data set) by following these steps:

1) Open the demonstration project (for example).
2) Draw a concodrdia plot for unknowns (Interpretations --> Unknowns --> Concordia).
3) Draw a weighted means plot (Interpretations --> Unknowns --> Weighted Means).  So far so good.
4) Now, click on an analysis row, but NOT the checkbox.  This will cause the WM plot to disappear (that's the first problem):
![image](https://user-images.githubusercontent.com/43234276/157730818-88f0bde8-dff3-4829-87ed-5c6c5bf6cf80.png)
5) Click on the sample label row, but again, NOT the check box.
![image](https://user-images.githubusercontent.com/43234276/157732616-fa1627bd-9840-4784-bd7f-e6ae2839df29.png)
6) Now click on a checkbox for any analysis and a (non-functional) concordia plot appears like magic.
![image](https://user-images.githubusercontent.com/43234276/157732995-14be5183-52b6-4060-901a-ecf6675ce4e4.png)

If you follow the same steps above for Reference Materials instead of Unknowns, no plot returns after step 4.

The method above reliably recreate this on all the installations I tried it on, but there may be slight variations that also cause similar results.

**Comment by bowring** [comment]
@TPestaj - good catch!  fixed in next release v1.9.10.
