### ISSUE TITLE
Task editing issue

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#690]
View Current Task gives:
<img width="1100" alt="Screen Shot 2022-03-17 at 9 07 51 am" src="https://user-images.githubusercontent.com/33318855/158716728-aa8bb39c-eead-443f-b223-9709999c0cb4.png">

Edit Current Task gives:
<img width="1102" alt="Screen Shot 2022-03-17 at 9 08 07 am" src="https://user-images.githubusercontent.com/33318855/158716821-4a5a6d79-f38f-4399-bfd1-3aafc94fe44a.png">

Below is the zipped .squid file

[Allanite C36 A46 2nd try.squid.zip](https://github.com/CIRDLES/Squid/files/8279202/Allanite.C36.A46.2nd.try.squid.zip)

**Comment by bowring** [comment]
@AllenKennedy - great catch!.  Fixed in next release V1.9.10.
