### ISSUE TITLE
Custom Reports not responsive to changes in Common Pb – Unknowns settings

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#704]
Might be two issues - not sure.

1. Peeks and Reports in general seem to not show the Common Pb settings accurately at first. It is possible that this is an artefact of upgrading older Squid3 Projects (e.g. 1.9.6 to 1.10.0), so this is difficult to test/retest. It might be good to ensure that the Peek is polling the initial settings. If/when I make a change in the Common Pb – Unknowns window, the Peek springs to life and works correctly thereafter.

2. More annoyingly, my Custom Reports seemingly do not pick up changes in the Common Pb – Unknowns window unless I Save the Project immediately prior to pressing Create CSV. Maybe it has to be this way, but if so, the Save Project routine should be included as part of the Create CSV routine.

**Comment by NicoleRayner** [comment]
I'm not sure if this is related, but it appears that the default common Pb selection for the unknowns doesn't "stick" - I was sure it used to in previous versions.  It always defaults to SK even if a custom model is selected for the RM (I am 99% sure that if a custom model was used for the RM and set as "default" that is what was used in the Common Pb window but I haven't gone back to an old version to check).

**Comment by NicoleRayner** [comment]
As discussed, when a custom common Pb model is selected for the RM (on the Project Manager page), default to the same custom model for the common Pb correction of the unknowns.  If a S-K model is selected for the RM (be it Temora or otherwise), please default "SK" for the unknowns.

**Comment by sbodorkos** [comment]
@NicoleRayner I talked with Jim @bowring about this on Monday and he mentioned he had resolved this... might be in the next release?

**Comment by NicoleRayner** [comment]
Yes – indeed this will be resolved, I was just documenting the nature of the resolution for posterity in this issue.  Feel free to close now if you are happy with the resolution of the original issue.

Nicole

**Comment by bowring** [comment]
@NicoleRayner and @sbodorkos - I think this has been resolved.  Make another issue if problems remain?  Cheers.
