### ISSUE TITLE
making task in ratio mode

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#708]
#502 
Back in October 2020,  this issue was closed as the most recent version at the time  had enabled the Task editor for ratio mode projects.  @nmseymour was recently in touch with me about this, so I did some tests and while I am able to generate a task and add isotopes, I can't make ratios (which I click on the add ratio button nothing happens).  I was trying to make a deadtime task with only 204 and 208.  A geochron task requires a bkgd, 207 and 206 isotopes.  Is that what is holding back the task editor now?

**Comment by bowring** [comment]
Ratio mode tasks were were an accidental side-effect of an experiment for @cwmagee .  We never actually planned it or developed it.  What I would like is a detailed description of what is wanted - use-cases, examples, etc. to understand the issue.

**Comment by NicoleRayner** [comment]
Just re-upping this Issue in preparation for more discussions about ratio mode.  Note that above some test files and potential tasks have been attached.  Currently "ratio mode" can import xlm files and make defined ratios.  They next step are to make custom expressions/tasks using those ratios.  There would be no built in expressions for calibrations etc.  They would all be custom.

**Comment by NicoleRayner** [comment]
After our meeting today I am going to close this issue and reopen a discussion section with a bit of an overview of where I think things are and an overview of the potential modifications needed and then as appropriate I will start making issues out of each of those modifications in turn (I just don't want to clutter the issues with a bunch of background stuff)
