### ISSUE TITLE
rejected RM points issue

### ISSUE THREAD

**Issue by adburnham** [CIRDLES/Squid#709]
(Possibly related to #706, but seems different enough that I'm reporting as a new issue)
If I go to Interpretations>Reference materials>Calibration constant WM and switch off auto-reject, the rejected spots on my RM (Temora) come back into play. However, if I go to Interpretations>Reference materials>Plot any two expressions the auto-rejects are still greyed out (in the plot) and unchecked (in the list), even after saving the project. These have to be re-selected manually in the "Plot any two expressions" list and the slope value changes. This latter step doesn't affect the calculated age, so it's just a plotting issue, but it's a bit confusing that it doesn't synchronise correctly with the list of points and they have to be added manually if auto-reject is switched off.

Also wondering if there is any way to find what the uncertainty is on the slope calculated for the plot of LnPbU vs LnUOU (the plot shows an uncertainty envelope but doesn't give numerical values anywhere).

**Comment by bowring** [comment]
@adburnham - next release has this fixed.  Also, the uncertainties will be displayed for the plot any two feature.  Thank you for your contribution!

**Comment by adburnham** [comment]
Maybe I'm missing something, but although I can see the error envelope for the best fit of any two expressions (blue dotted line), the window only shows (written out) the values of the slope and y-intercept but not their uncertainties. Is there any way to find out the uncertainties, short of sending the values to Excel and calculating in Isoplot? I tried viewing it in "Manage expressions", where I can see the calculation of Expo, but the numbers in the Peek window don't match up to to what is calculated in "Plot Any Two Expressions".
