### ISSUE TITLE
Newly-defined RM Models don't become available for Select until Squid3 restarted

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#715]
This is a pretty minor one. When in the Manage Spots and Reference Materials screen, I realised I had no model for the Isotopic RM I was using.

No problem, clicked Manage RM Model, created the Model I needed... but it didn't become available for Select via the Select Isotopic RM Model dropdown (which was unchanged). Nothing I did inside the Project was capable of changing this, so I quit and restarted Squid3, which addressed the issue.

Unfortunately, at that point I realised I needed to repeat the entire process because I had no model for the Concentration RM either... culminating in yet another quit and restart (post-CRM construction) before I was able to finalise my Manage Spots and RMs screen:

![image](https://user-images.githubusercontent.com/17473203/178294873-7e3619eb-4fd5-4746-9505-ca2593eeea73.png)

It seems like defining a new RM Model (whether Isotopic, Concentration or both) ought to be reflected in the Select dropdowns

**Comment by NicoleRayner** [comment]
I think i have encountered this before too and what I did that seemed to rectify it was go to Manage Project and press refresh models THEN the new/edited one appears.
![image](https://user-images.githubusercontent.com/40035242/178341234-fd1465b5-336b-4719-a74c-4bea91b1d4ae.png)

Now it is possible that this fix only works when editing an existing model, not making a new one.  I have not tested

**Comment by bowring** [comment]
Actually, just reloading the page you are on (Data/Manage Spots and Reference Materials) will do the trick.  However, I will add a refresh models button on this page as well.

**Comment by bowring** [comment]
Next release: Fixed both scenarios - if you use the parameters menu item to launch parameters manager, then use the new refresh button;  if you use the manage parameters button, refreshing is done automatically.  Happy Squiddin'!
