### ISSUE TITLE
Loading old squid files not working

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#721]
I tried loading some old, 2019, .squid files and had two outcomes. (1) the file wouldn't open, but with no warning message, as for LMT titanite.squid,
or (2) a different .squid file kept loading. The .squid file I tried to load after (1) occurred was, Kara18.squid, which is 5MB in size, and the one that loaded is magcheck.squid, which is 1.8MB. I have attached the files. I have noticed that when this occurs the title at the top of the window is Squid 3 (Project File: NONE)
[LMT titanite.squid.zip](https://github.com/CIRDLES/Squid/files/9264730/LMT.titanite.squid.zip)
[magcheck.squid.zip](https://github.com/CIRDLES/Squid/files/9264731/magcheck.squid.zip)
[Kara18.squid.zip](https://github.com/CIRDLES/Squid/files/9264733/Kara18.squid.zip)

**Comment by bowring** [comment]
Fixed in v1.10.3.  This was a missed backward compatibility issue having to do with reporting.  Good catch.
