### ISSUE TITLE
Squid 1.10.3 will not run for me

### ISSUE THREAD

**Issue by TPestaj** [CIRDLES/Squid#723]
Squid3 Version: 1.10.2
Java Version: 1.8.0_341
JavaFX Version: 8.0.341-b10
OS: Windows 10 10.0

Issue details:
When I launch the latest version of Squid (1.10.3), I get this error:

![image](https://user-images.githubusercontent.com/43234276/183084611-ab6bc37f-4650-46be-ae80-50112a3f672c.png)

1.10.2 runs fine in the same environment.  (A reboot did not help me.)

**Comment by NicoleRayner** [comment]
I have the same issue

**Comment by bowring** [comment]
hmmm.... works here on my mac ... need to find a windows box

**Comment by bowring** [comment]
can you run it in verbose mode from the command line and send me the output?
java -jar Squid....jar  -verbose

**Comment by TPestaj** [comment]
Here's what I get..

![image](https://user-images.githubusercontent.com/43234276/183096735-2c634bc4-658b-4f97-828d-2794bacdaab4.png)

**Comment by bowring** [comment]
I accidentally build it with java 17 :
[Liberica JDK/JRE 17 full](https://bell-sw.com/pages/downloads/#/java-17-lts%20/%20current) (select **full** from drop-down list)

[Azul JDK-fx 17](https://www.azul.com/downloads/?package=jdk-fx#download-openjdk)

... will rebuild with java 8
