### ISSUE TITLE
Capturing Calibration Constant WM data

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#727]
Could we please have a look at the best way to allow users to write their standard calibration data to file. At the moment, you get a display of it (via Interpretations - Reference Materials - Calibration Constant WM; see first image below), but there is no way to write that summary data anywhere:

![image](https://user-images.githubusercontent.com/17473203/189579026-10512739-aeb6-4a67-b7db-71b2e13ecd1c.png)

But if we instead go to the next option down the menu (Interpretations - Reference Materials - Weighted Means), which is in general less immediately useful, we have options for writing those means to file:

![image](https://user-images.githubusercontent.com/17473203/189579761-c26ce688-219c-4a9b-9fe2-d896a8500c1f.png)

Is there some way to unify this functionality across both menu options?

**Comment by NicoleRayner** [comment]
This value is written to the RefMat Summary report, which is generated with one click (along with all other reports) using the "Generate all reports" button under reports.  Will this suffice?  In attached file this value is in row 210

[1014_2_2022_May_09_09.32_RefMatSummaryReport.csv](https://github.com/CIRDLES/Squid/files/9548396/1014_2_2022_May_09_09.32_RefMatSummaryReport.csv)

**Comment by sbodorkos** [comment]
Yeah, I didn't know about that! I have avoided using "Generate all reports" because I didn't now which templates would be applied to my RefMat and Unknowns data (and the template needs to be matched to the type of Task you're using, otherwise inapplicable column-headers vanish and never return). Jim has told me that "Generate all reports" uses whatever the "default" template is, so now I know! And I see that report can be generated in isolation via Reports - Summary Expressions and Values - Reference Materials.

Although... I can see that the RefMat summary is not reported correctly, relative to the display data in Calibration Constant WMs:

![image](https://user-images.githubusercontent.com/17473203/189925770-5273fca6-cf65-4360-b05e-df801bad350b.png)

The field labelled "exterr68" in the CSV is actually the 1sigma _internal_ error of the mean in Squid3 (and expressed as absolute in the CSV, not percentage as in Squid3):

![image](https://user-images.githubusercontent.com/17473203/189926406-c179acf2-74f9-4654-a13f-b9e548ae8ee5.png)

Furthermore, the 1sigma external spot-to-spot error in Squid3 is not actually reported anywhere in the CSV.

Jim @bowring I think we need to have a look at these, with respect to the differences between the "true" RefMat summary-block, and the output of Isoplot's WeightedAverage function. I have described them somewhere in here: https://github.com/CIRDLES/Squid/issues/582#issuecomment-801641139

**Comment by NicoleRayner** [comment]
the 1s external spot to spot is row 21
"4cor_206Pb238U_Ext1SigmaErr_Pct | Note: RM dataset: Calculated external (spot-to-spot) 1sigma uncertainty  (expressed as a percentage) derived from WtdAv_4cor_206Pb238U_CalibConst  subject to a user-defined minimum value."

**Comment by sbodorkos** [comment]
Ah yes, I see! Thanks
