### ISSUE TITLE
Spot-means via Linear Regression in Squid3 appear to be Intercepts (t = 0), not burn-midpoints

### ISSUE THREAD

**Issue by sbodorkos** [CIRDLES/Squid#728]
Thanks to Bill Davis (Geological Survey of Canada) for flagging this. He has processed data in both Squid3 and SQUID 2.50.20.10.26 (which is the "best match" to Squid3), and noted that spot-means are indistinguishable when Squid3 is used in 'spot-average' mode ("Wtd Mean" below), but quite different in 'linear regression' mode ("LR" below). In particular, the Squid3 LR uncertainties are significantly larger than the SQUID 2.50 LR uncertainties:

![image](https://user-images.githubusercontent.com/17473203/189842197-73b0207c-5fe3-4c48-9974-e8b83520428c.png)

Bill suggested that it might be a manifestation of this problem (this is a slide from my Squid3 Launch PowerPoint):

![image](https://user-images.githubusercontent.com/17473203/189842779-236afbf2-da0e-439e-8708-2c84ce60e4d7.png)

I have reviewed both sets of code, and I think he might be right. At some point, the "midpoint vs intercept" issue was addressed in SQUID 2.50: the 26 October 2020 version contains the amended code:

![IfLinReg](https://user-images.githubusercontent.com/17473203/189843720-ac2bfd12-1de1-4128-924f-8606567cbb95.png)

which calculates Slope, SigmaSlope and CovSlopeInter whenever LinReg = TRUE (regardless of MinIndex).

In contrast, the corresponding code documentation for Squid3 (see https://github.com/CIRDLES/ET_Redux/wiki/SHRIMP:-Sub-WtdLinCorr, right at the bottom) looks like this:

![image](https://user-images.githubusercontent.com/17473203/189841967-399b3eb8-cfc7-456c-a89c-e625810ea7f7.png)

It appears that the MinIndex-related criterion was flagged for follow-up, but this line of code was never changed in Squid3. My guess is we never picked this up previously because we have never done a cell-by-cell comparison (for data calculated via linear regression) since the SQUID 2.50 change was enacted.

Jim @bowring , could you please review the Squid3 code corresponding to the yellow line, and modify if needed? It should simply read "If LinReg = TRUE". When we have a new version, I will ask Bill to re-test.

If that line of code is not the issue (i.e. if it _already_ just reads "If LinReg = TRUE"), then we will need to dig deeper. Please let me know.

**Comment by bowring** [comment]
Found the code with the minIndex condition at line 198 of [WeightedMeanCalculators.java](https://github.com/CIRDLES/Squid/blob/master/squidCore/src/main/java/org/cirdles/squid/algorithms/weightedMeans/WeightedMeanCalculators.java).

```java
        if (linReg && (minIndex > 0)) {
               wtdLinCorrResults.setSlope(slopeW[minIndex]);
               wtdLinCorrResults.setSigmaSlope(sigmaSlopeW[minIndex]);
               wtdLinCorrResults.setCovSlopeInter(covSlopeInterW[minIndex]);
        }
```

Will update and release a new version this week.  Thanks for checking the details!
