### ISSUE TITLE
Missing Parameter models

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#740]
I had a bunch of Common Lead and Reference Material Models that were inside the SquidParameterModels folder inside the SquidResources folder, that were removed by the latest version. I did have a back up, and could copy them across. However, they don't appear to be accessible when choosing a reference material in Data. If I find an old .squid file that uses a missing model, I can sometimes reinstate the missing file by editing and then saving under Parameters. This doesn't always work. The attached squid file uses the AFG2 common Pb model, but I cannot recover it. Is there an easy way to reinstate all my Models, as I don't have old .squid files for every one of them?
[Extra Apat seg2.squid.zip](https://github.com/CIRDLES/Squid/files/10224028/Extra.Apat.seg2.squid.zip)

**Comment by bowring** [comment]
The SquidResources folder is rewritten whenever Squid runs as it contains files in a form that Squid depends on.   You should be able to use the parameters manager and the import  menu item to read in  your models' xml files.  If not, please provide an example.

**Comment by AllenKennedy** [comment]
Is it possible to batch import users Common Lead Models and Reference Material Models into the SQ3 Resources? This would make life easier for the user who has 50 RMM models and 10 CLM.

**Comment by bowring** [comment]
@AllenKennedy - 
I am not sure what the use case is.  Is the idea that another user might want quick access to your models?

If you make and save models in Squid3, they remain in your private library available through the parameters manager.  If you want to export them as xml models for some reason, you should not use the SQ3 Resources folder as that is for SQ3's internal use only - it gets re-created every execution from stored models.  It exists to aid SQ3 to run on all platforms.  Additional files saved in this folder will eventually be deleted.   Rather you should create your own separate folder for saving models if you want exported copies of them.

Thoughts?

**Comment by AllenKennedy** [comment]
Can we have a user private library that automatically loads along with the internal use only SQ3 Resources files. That way a user does not need to individually load parameter files. This just for ease of use. So it isn't an essential feature, just an enhancement.

**Comment by AllenKennedy** [comment]
The original zipped .squid file has a Common Pb Model that no longer exists. Can we warn the user that a model is missing?

**Comment by bowring** [comment]
There already is a private library that loads and is available via the parameters manager.  If you open a Squid file that has a parameter model in use, it adds it to the private library if it is missing.  Do you have an example file(s) you can supply?

**Comment by bowring** [comment]
@AllenKennedy - maybe we should schedule a zoom / skype call so I can see what is happening?

**Comment by AllenKennedy** [comment]
Hi Jim,
Sorry for the tardy reply. I have been on leave. I don't think we need a call as I am convinced this is my lack of knowledge of SQ3 or something happening with my MAC. I have had Java crash a couple of times today. Anyway, at present I can find the missing parameter models when I open a .squid file, so my problem seems to have disappeared.  If I get another .squid with no parameter models I will zip it and send it along.

**Comment by bowring** [comment]
Thanks. Closing for now.
