### ISSUE TITLE
Custom report builder trouble

### ISSUE THREAD

**Issue by TPestaj** [CIRDLES/Squid#745]
Squid3 Version: 1.10.6
Java Version: 1.8.0_361
JavaFX Version: 8.0.361-b09
OS: Windows 10 10.0

Issue details:
When creating a new report or modifying a copy of an existing one, I can create a new category, but cannot seem to populate it with any expressions.  I can drag expressions into categories that already have expressions in them, but not into empty ones.  This does not seem to be associated with any particular data file.

**Comment by bowring** [comment]
This bug was introduced in v1.10.2 .  Fixed soon.

**Comment by bowring** [comment]
@TPestaj  - this was a side-effect of drag n drop files.  Fixed in next release.
