### ISSUE TITLE
"Edit Current Task" button does not work after edit and replace current task.

### ISSUE THREAD

**Issue by PENGwxgeo** [CIRDLES/Squid#748]
Squid3 Version: 1.10.7
Java Version: 1.8.0_361
JavaFX Version: 8.0.361-b09
OS: Windows 11 22H2

Issue details:
When I "View Current Task", and click the button "Edit Current Task", then edit current task (add or remove mass or ratios) and click "Use to Replace Current Task", then it take me to the Task interface and changes take effect, but the button "Edit Current Task"  does not work unless I reopen the SQUID3 program. It means I can only edit current task once until I reopen the SQUID3.jar next time. This issue would occur when open a .squid file or a new SQUID3 GEOCHRON project from a single prawn .xml file. I just started to use SQUID3 and I am not sure whether this is a bug or I did something wrong?
![issue](https://github.com/CIRDLES/Squid/assets/66554723/8ae937a4-0e3c-4f66-a577-dc531a85d750)

**Comment by bowring** [comment]
@PENGwxgeo - good catch!  Fixed in next release v1.10.8.
