### ISSUE TITLE
Update SquidTask_ExpressionXMLSchema.xsd

### ISSUE THREAD

**Issue by bowring** [CIRDLES/Squid#75]
The schema needs the notes field added and also the list of functions and operations updated to match the names in the Function and Operation class.

**Comment by BryceBarrett** [comment]
Hey Dr. Bowring, I think you meant to assign my brother to this issue?

**Comment by bowring** [comment]
thanks!

**Comment by bowring** [comment]
This was handled in the task updating from fall 2020.
