### ISSUE TITLE
Loading XML file issue

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#754]
The latest SHRIMP software produces an  XML file with additional variables. 
SQUID 3  gives an error
<img width="788" alt="Screen Shot 2023-10-23 at 12 29 36 pm" src="https://github.com/CIRDLES/Squid/assets/33318855/7a037caa-120c-46f4-8790-4caaf629abef">

There is extra data in the XML file for each run...such as 
<pressure_names>
<pressures

The attached zip file contains a sample of the latest XML file that SQUID3 has problems loading.

[HO_AZ-1_23101610.30.zip](https://github.com/CIRDLES/Squid/files/13066734/HO_AZ-1_23101610.30.zip)

Is there a way to make SQUID3 usable with different versions of the XML data file produced by the SHRIMP software?

**Comment by AllenKennedy** [comment]
PS   The OP file works in SQUID3

**Comment by bowring** [comment]
Yes!  If possible supply a copy of the new SHRIMP schema file - it ends in “.xsd”

**Comment by peter-lanc** [comment]
Sorry I have had no need for XSD. Do you have one at the moment that you use with SQUID3?

**Comment by peter-lanc** [comment]
Found it here, I can see it has gone through some revision for SHRIMP software updates in the past. Last being 4 years ago. Is this the way forward? Revise the schema file when we add new data to the SHRIMP XML data file? Is this something you'd like me to do or maintain another XSD file together with the .XML coming from the SHRIMP? Or will as you have until now maintain/revise the XSD Jim?

**Comment by peter-lanc** [comment]
I have now modified your XSD to validate against the latest SHRIMP data file. Attached.
Note I have simplified the namespace definitions to be validated from:
   <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="https://raw.githubusercontent.com"
           xmlns="https://raw.githubusercontent.com">
     <xs:annotation>
to:
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
 Also had to change the SHRIMP XML datafile schema definition as shrimp.anu.edu.au does not exist anymore. I will make those changes to SHRIMP data file permanent in the SHRIMP software.
    <prawn_file
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="shrimp_prawn.xsd">
   <software_version>SHRIMP SW v4.0 SHR SI</software_version>
In any case, after those header changes and adding the missing data definitions to the XSD, the data file passes validation against attached schema.
[SHRIMP_PRAWN mod Peter Lanc 2023-10-25.zip](https://github.com/CIRDLES/Squid/files/13129855/SHRIMP_PRAWN.mod.Peter.Lanc.2023-10-25.zip)

**Comment by bowring** [comment]
@peter-lanc - Great!  Thanks for contributing. - @bowring
