### ISSUE TITLE
New version of single prawn .xml file cannot be imported into SQUID3

### ISSUE THREAD

**Issue by PENGwxgeo** [CIRDLES/Squid#759]
Squid3 Version: 2.0.3
Java Version: 1.8.0_391
OS: Windows 11 22H2

Several days ago, our lab updated the version of the SHRIMP II software. The software version shown in prawn .xml file changed from "<software_version>SHRIMP SW v3.55 SHR 2</software_version>" to "<software_version>SHRIMP SW v4.0 SHR 2</software_version>". Now, when I try to import the .xml file into the SQUID3, an error message is displayed (**as shown by following figure, sorry for the chinese words because my system cannot change the language to English**)
![image](https://github.com/CIRDLES/Squid/assets/66554723/e4c6b897-dd98-4f23-acd0-459ad0803fbb)
It means "csv-cpmlex-type.2.4.a: Find the invalid content starting with the element '{"https://raw.githubusercontent.com":project_number}'"

I tried to find out what happened. Finally, I found that the new version of .xml file contains some new texts that old version did not. For example:
![image](https://github.com/CIRDLES/Squid/assets/66554723/f5156714-9b30-4c34-90b1-d8df5c5cf3b8)
![image](https://github.com/CIRDLES/Squid/assets/66554723/7dd159e1-5d00-43df-8ba8-866c5cba47be)

There are  several differences between old version and new version. The new version of .xml file are attached.
[New version of prawn xml file.zip](https://github.com/CIRDLES/Squid/files/13400208/New.version.of.prawn.xml.file.zip)

By the way, the .op file can be imported but can not audit the RAW DATA.

**Comment by bowring** [comment]
@PENGwxgeo - Do you have the xml schema file or the new xml docs?  If not, it would be a great help if you could provide a PRAWN file with all the additions highlighted.  Thanks

**Comment by bowring** [comment]
@peter-lanc : do you have any insights here?  Seems like a major change to the xml.

**Comment by bowring** [comment]
My bad - just needed to add 2 lines to schema.  Stand by for new version of Squid.

**Comment by PENGwxgeo** [comment]
> My bad - just needed to add 2 lines to schema. Stand by for new version of Squid.

Yes, I just found 2 lines, "<project_number>" and "<session_number>". Other different lines are just comments like "<!-- xxxx>". I removed these 2 lines and the xml file can be imported.

Just a small bug. SQUID3 is a good software.

**Comment by bowring** [comment]
@PENGwxgeo- Thank you for the kudos!  Also, FYI, the ".op" files don't contain enough data for audit mode.  Cheers! 
- @bowring
