### ISSUE TITLE
Latest SHRIMP XML file fails to load.

### ISSUE THREAD

**Issue by AllenKennedy** [CIRDLES/Squid#761]
SQUID3 produces an error loading the latest SHRIMP XML file.  This issue was fixed before?

See attached files. Original (non loading) and edited (loads ok)

[GH3_Alphal Y 19_23112010.46.xml.zip](https://github.com/CIRDLES/Squid/files/13421201/GH3_Alphal.Y.19_23112010.46.xml.zip)

[GH3_Alphal Y 19_23112010.46 edit.xml.zip](https://github.com/CIRDLES/Squid/files/13421202/GH3_Alphal.Y.19_23112010.46.edit.xml.zip)

**Comment by bowring** [comment]
@AllenKennedy - the latest version of Squid v2.0.4 fixed this. 
See https://github.com/CIRDLES/Squid/issues/759
