### ISSUE TITLE
the CommonPb frame refresh when swapping

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Squid#778]
This was noted before (by you, but I never made an issue about this, so I am now).  The CommonPb frame does not refresh the SWAPCustomCorrection204 calculations - if they were already selected - unless forced to do so.  It should.

https://github.com/CIRDLES/Squid/issues/613#issuecomment-1728340728

I would need to actually test this with the new version where it isn't built in, so perhaps it is moot but I wanted to flag right away in case it can get solved before next release.

**Comment by bowring** [comment]
fixed, as noted, in v2.0.9 ... available later today.
